Repository NativeScript/NativeScript, pull requests merged in 2018-02, with the labels that each got.

#5408 fix(frame): root tabview with modal frame when suspend/resume app Fixes #5398
  tests/app/testRunner.ts
  tests/app/ui/page/page-tests-common.ts
  tns-core-modules/ui/core/view-base/view-base.d.ts
  tns-core-modules/ui/core/view-base/view-base.ts
  tns-core-modules/ui/core/view/view-common.ts
  tns-core-modules/ui/frame/frame-common.ts
  tns-core-modules/ui/frame/frame.android.ts
Labels: bug, cla: yes, in progress, ns 4.0, os: android

#5387 Cherry-pick onDisplayed event for iOS and TS 2.7 fixes
  tns-core-modules/application/application-common.ts
  tns-core-modules/application/application.ios.ts
  tns-core-modules/css/parser.ts
  tns-core-modules/package.json
  tns-core-modules/profiling/profiling.d.ts
  tns-core-modules/profiling/profiling.ts
  tns-core-modules/ui/styling/css-selector/css-selector.ts
  tns-platform-declarations/package.json
  unit-tests/css/parser.ts
Labels: cla: yes, in progress

#5418 feat: support intent replacement in the android activity (#5337)
  tns-core-modules/ui/frame/activity.android.ts
Labels: cla: yes, in progress

#5411 fix(ios-layouts): switch contentInsetAdjustmentBehavior on ScrollView
  apps/app/ui-tests-app/scroll-view/main-page.ts
  apps/app/ui-tests-app/scroll-view/safe-area-root-element.xml
  apps/app/ui-tests-app/scroll-view/safe-area-sub-element.xml
  tns-core-modules/ui/core/view-base/view-base.d.ts
  tns-core-modules/ui/core/view-base/view-base.ts
  tns-core-modules/ui/core/view/view.ios.ts
  tns-core-modules/ui/scroll-view/scroll-view.ios.ts
Labels: bug, in progress, ns 4.0

#5426 fix(ios-frame): do not update backstack when navigating the same page
  tns-core-modules/ui/frame/frame.ios.ts
  tns-core-modules/ui/page/page.ios.ts
Labels: bug, in progress, ns 4.0

#5425 fix(profiling): resetProfiles doesn't reset all profiles
  tests/app/profiling/profiling-tests.ts
  tns-core-modules/profiling/profiling.ts
Labels: cla: yes, in progress

#5430 docs(CONTRIBUTING): add commit message guidelines
  CONTRIBUTING.md
Labels: cla: yes, in progress

#5444 chore: 3.4.1 changelog
  CHANGELOG.md
Labels: cla: yes, in progress

#5404 hiding cookbook/ui/action-bar article in favor of ui/action-bar
  tests/app/ui/action-bar/action-bar.md
Labels: cla: yes, in progress

#5436 docs(PR-template): suggest following the commit message guidelines
  .github/PULL_REQUEST_TEMPLATE.md
Labels: cla: yes, in progress

#5437 test: add reset root view tests
  tests/app/navigation/reset-root-view-tests.ts
  tests/app/testRunner.ts
  tns-core-modules/application/application-common.ts
  tns-core-modules/application/application.android.ts
  tns-core-modules/application/application.ios.ts
  tns-core-modules/ui/core/view-base/view-base.d.ts
  tns-core-modules/ui/core/view-base/view-base.ts
  tns-core-modules/ui/frame/frame-common.ts
  tns-core-modules/ui/frame/frame.android.ts
Labels: cla: yes, in progress, ns 4.0

#5449 test: Fixed unstable timer test
  tests/app/timer/timer-tests.ts
Labels: cla: yes, in progress

#5446 fix-next(modal) fix crash when closing modal dialog with root tabview Fixes #5391
  tests/app/ui/page/page-tests-common.ts
  tests/app/ui/tab-view/tab-view-tests.ts
  tns-core-modules/ui/core/view/view.android.ts
  tns-core-modules/ui/tab-view/tab-view.android.ts
Labels: bug, cla: yes, in progress, ns 4.0, os: android

#5451 fix(ios-action-bar): NavigationButton cannot be hidden
  tns-core-modules/ui/action-bar/action-bar-common.ts
  tns-core-modules/ui/action-bar/action-bar.android.ts
  tns-core-modules/ui/action-bar/action-bar.d.ts
  tns-core-modules/ui/action-bar/action-bar.ios.ts
Labels: bug, in progress, ns 4.0

#5460 fix(inspector): Fix --debug-brk issue with Inspector
  tns-core-modules/debugger/devtools-elements.common.ts
Labels: bug, cla: no, in progress

#5459 Extend console tests for iOS
  apps/app/ui-tests-app/events/console.ts
Labels: cla: no, in progress

#5468 fix-next: ensure proper events on tab change
  tests/app/navigation/reset-root-view-tests.ts
  tests/app/testRunner.ts
  tests/app/ui/helper.ts
  tests/app/ui/tab-view/tab-view-root-tests.ts
  tns-core-modules/ui/frame/frame.android.ts
  tns-core-modules/ui/frame/frame.ios.ts
  tns-core-modules/ui/tab-view/tab-view.ios.ts
Labels: cla: yes, in progress, ns 4.0

#5110 Improve ImageAsset scaling
  apps/app/splashscreen.png
  apps/app/ui-tests-app/image-view/image-asset/image-asset.ts
  apps/app/ui-tests-app/image-view/image-asset/image-asset.xml
  apps/app/ui-tests-app/image-view/image-asset/view-model.ts
  apps/app/ui-tests-app/image-view/main-page.ts
  tests/app/App_Resources/Android/drawable-nodpi/splashscreen.9.png
  tests/app/App_Resources/Android/drawable-nodpi/splashscreen.png
  tests/app/App_Resources/iOS/splashscreen.png
  tests/app/image-source/image-source-tests.ts
  tests/app/splashscreen.png
  tests/app/ui/image/image-tests.ts
  tns-core-modules/image-asset/image-asset-common.ts
  tns-core-modules/image-asset/image-asset.android.ts
  tns-core-modules/image-asset/image-asset.ios.ts
  tns-core-modules/image-source/image-source.android.ts
  tns-core-modules/ui/image/image.android.ts
  tns-platform-declarations/android/org.nativescript.widgets.d.ts
Labels: cla: yes, in progress

#5458 fix(ios-action-bar): NavigationButton text change on first navigation
  tns-core-modules/ui/frame/frame.ios.ts
Labels: bug, in progress
