Repository NativeScript/NativeScript, pull requests merged in 2018-04, with the labels that each got.

#5607 chore(view): expose onBackPressed in d.ts
  tns-core-modules/ui/core/view/view.d.ts
Labels: cla: yes, in progress

#5608 feat(frame): handle back navigation when common layout is used as a root element
  e2e/modal-navigation/app/app.ts
  e2e/modal-navigation/app/home/home-page.ts
  e2e/modal-navigation/app/home/home-page.xml
  e2e/modal-navigation/app/layout-root.xml
  e2e/modal-navigation/app/modal-layout/modal-layout.ts
  e2e/modal-navigation/app/modal-layout/modal-layout.xml
  e2e/modal-navigation/e2e/screen.ts
  tns-core-modules/ui/core/view/view-common.ts
  tns-core-modules/ui/core/view/view.android.ts
  tns-core-modules/ui/core/view/view.d.ts
  tns-core-modules/ui/frame/frame-common.ts
  tns-core-modules/ui/frame/frame-stack.ts
Labels: cla: yes, in progress, ns 4.0

#5612 fix(style): Styles are not applied to dialogs
  tns-core-modules/ui/dialogs/dialogs-common.ts
  tns-core-modules/ui/dialogs/dialogs.android.ts
  tns-core-modules/ui/dialogs/dialogs.ios.ts
Labels: cla: yes, in progress

#5618 fix-next(ios-modal): fix empty modal view when using common layout as root
  tns-core-modules/ui/core/view/view.ios.ts
Labels: bug, in progress, ns 4.0

#5628 new tabview examples
  tests/app/ui/tab-view/tab-view.md
Labels: cla: yes, in progress

#5610 Tsenov/issue 3714
  apps/app/ui-tests-app/issues/issue-3714.ts
  apps/app/ui-tests-app/issues/issue-3714.xml
  apps/app/ui-tests-app/issues/main-page.ts
Labels: cla: yes, in progress

#5649 fix(navigation): fix frame.navigate call inside page.navigatedTo handler Fixes #5642
  tests/app/navigation/navigation-tests.ts
  tns-core-modules/ui/frame/frame-common.ts
Labels: cla: yes, in progress

#5629 chore(image): expose decode image properties for the public API
  tns-core-modules/ui/image/image.d.ts
Labels: in progress, ns 4.0

#5646 chore: Add 4.0 change-log
  CHANGELOG.md
Labels: cla: yes, in progress

#5658 fix(ios-searchbar): fix crash with auto-sized searchbar in iOS11 Fixes #5655
  apps/app/ui-tests-app/search-bar/issue-5655.xml
  apps/app/ui-tests-app/search-bar/main-page.ts
  tns-core-modules/ui/search-bar/search-bar.ios.ts
Labels: cla: yes, in progress

#5666 test: include new test page for issue 5470
  apps/app/ui-tests-app/tab-view/issue-5470.xml
  apps/app/ui-tests-app/tab-view/main-page.ts
Labels: cla: yes, in progress

#5668 feat(builder): enable reading xml from bundle
  tns-core-modules/ui/builder/builder.ts
Labels: cla: yes, in progress

#5693 fix(list-view-ios): fix rowHeight property to apply proper item size for iOS
  apps/app/ui-tests-app/list-view/main-page.ts
  apps/app/ui-tests-app/list-view/row-height.css
  apps/app/ui-tests-app/list-view/row-height.ts
  apps/app/ui-tests-app/list-view/row-height.xml
  tns-core-modules/ui/list-view/list-view.ios.ts
Labels: bug, in progress

#5697 Updated weak event listener tests for v8 6.5
  tests/app/ui/core/weak-event-listener/weak-event-listener-tests.ts
Labels: cla: yes, in progress

#5670 fix(android-connectivity): Add ethernet connection type
  tns-core-modules/connectivity/connectivity.android.ts
  tns-core-modules/connectivity/connectivity.d.ts
Labels: cla: yes, in progress

#5700 fix(android): crash on changing activity context after animated navigation Fixes #5674
  tns-core-modules/ui/frame/frame.android.ts
Labels: cla: yes, in progress

#5680 test(modal-navigation): add close modal, modal layout and root layout tests
  e2e/modal-navigation/.gitignore
  e2e/modal-navigation/.vscode/launch.json
  e2e/modal-navigation/README.md
  e2e/modal-navigation/app/home/home-page.ts
  e2e/modal-navigation/app/layout-root.android.xml
  e2e/modal-navigation/app/layout-root.ios.ts
  e2e/modal-navigation/app/layout-root.ios.xml
  e2e/modal-navigation/app/modal-layout/modal-layout.xml
  e2e/modal-navigation/app/modal-nested/modal-nested-page.xml
  e2e/modal-navigation/app/modal-second/modal-second-page.ts
  e2e/modal-navigation/app/modal-second/modal-second-page.xml
  e2e/modal-navigation/app/modal/modal-page.xml
  e2e/modal-navigation/e2e/config/appium.capabilities.json
  e2e/modal-navigation/e2e/e2e-spec-app-root/app-root-modal-frame.e2e-spec.ts
  e2e/modal-navigation/e2e/e2e-spec-app-root/app-root-modal-page.e2e-spec.ts
  e2e/modal-navigation/e2e/e2e-spec-app-root/app-root-modal-tab.e2e-spec.ts
  e2e/modal-navigation/e2e/e2e-spec-tab-root/tab-root-modal-frame.e2e-spec.ts
  e2e/modal-navigation/e2e/e2e-spec-tab-root/tab-root-modal-page.e2e-spec.ts
  e2e/modal-navigation/e2e/e2e-spec-tab-root/tab-root-modal-tab.e2e-spec.ts
  e2e/modal-navigation/e2e/modal-frame.e2e-spec.ts
  e2e/modal-navigation/e2e/modal-layout.e2e-spec.ts
  e2e/modal-navigation/e2e/modal-page.e2e-spec.ts
  e2e/modal-navigation/e2e/modal-tab.e2e-spec.ts
  e2e/modal-navigation/e2e/screen.ts
  e2e/modal-navigation/e2e/shared.e2e-spec.ts
  e2e/modal-navigation/package.json
  e2e/modal-navigation/webpack.config.js
Labels: cla: yes, in progress

#5710 feat(file-system): add ability to retrieve file size
  tests/app/file-system/file-system-tests.ts
  tns-core-modules/file-system/file-system-access.android.ts
  tns-core-modules/file-system/file-system-access.d.ts
  tns-core-modules/file-system/file-system-access.ios.ts
  tns-core-modules/file-system/file-system.d.ts
  tns-core-modules/file-system/file-system.ts
Labels: cla: yes, in progress

#5724 fix(layout): IOS Layout not invalidated with custom root
  tests/app/ui/root-view/mymodule/MyControl.ts
  tests/app/ui/root-view/root-modules/gridlayout-root.xml
  tests/app/ui/root-view/root-modules/tabview-root.xml
  tests/app/ui/root-view/root-view-tests.ts
  tns-core-modules/ui/core/view/view.ios.ts
Labels: cla: yes, in progress

#5709 test(platform): add missing properties to platform module documentation
  tests/app/platform/platform-tests.ts
Labels: cla: yes, in progress

#5705 fix(ios-image-asset): getImageAsync() can retrieve assets stored remotely in iCloud
  tns-core-modules/image-asset/image-asset.ios.ts
Labels: cla: yes, in progress

#5737 fix(modal): exception when calling ViewBase.showModal(...)
  tests/app/ui/page/page-tests-common.ts
  tns-core-modules/ui/core/view-base/view-base.ts
Labels: cla: yes, in progress

#5734 chore(modal): update d.ts for showModal(...) parameters
  tns-core-modules/ui/core/view-base/view-base.d.ts
  tns-core-modules/ui/core/view/view.d.ts
Labels: cla: yes, in progress

#5754 Add required inspector fields for Elements and Network
  tns-core-modules/debugger/debugger.ts
  tns-core-modules/debugger/dom-node.ts
Labels: cla: yes, in progress

#5758 test(platform): fix typo in platform module cookbook example
  tests/app/platform/platform-tests.ts
Labels: cla: yes, ♥ community PR

#5742 docs: update wording describing issue lifecycle
  .github/ISSUE_TEMPLATE.md
  CONTRIBUTING.md
Labels: cla: yes, in progress
