Repository NativeScript/NativeScript, pull requests merged in 2018-07, with the labels that each got.

#6015 fix(grunt): Add platforms folder to produced NPM package
  gruntfile.js
Labels: bug, cla: yes, in progress

#6004 fix(animations): avoid steady mem consumption rise
  tns-core-modules/ui/animation/keyframe-animation.ts
Labels: cla: yes, in progress

#6038 ignore transition-definitions.android.d.ts from typedoc
  tsconfig.typedoc.json
Labels: cla: yes, in progress

#6029 fix(action-bar): #5743 navController may be null
  tns-core-modules/ui/action-bar/action-bar.ios.ts
Labels: cla: yes, in progress

#6047 chore(listview-tests): add tests for width property with percentages
  apps/app/ui-tests-app/list-view/main-page.ts
  apps/app/ui-tests-app/list-view/width-percent.ts
  apps/app/ui-tests-app/list-view/width-percent.xml
Labels: in progress

#6056 Fixing onReceiveError for API level >= 23
  tns-core-modules/ui/web-view/web-view.android.ts
Labels: cla: yes, in progress

#6076 chore: add test for http gzip request
  tests/app/http/http-tests.ts
Labels: cla: yes, in progress

#6079 fix: require devtools-elements.js with the extension mentioned explicitly
  tns-core-modules/ui/frame/frame.android.ts
Labels: cla: yes, in progress

#6080 Add missing globalAndroid import
  tns-platform-declarations/android/android-declarations.d.ts
Labels: cla: yes, in progress

#6084 release: cut the 4.1.1 release
  CHANGELOG.md
  tns-core-modules/globals/globals.ts
  tns-core-modules/package.json
  tns-core-modules/ui/frame/frame.android.ts
Labels: cla: yes, in progress

#6077 feat(UI): Added animated scroll to index for ListView
  tns-core-modules/ui/list-view/list-view-common.ts
  tns-core-modules/ui/list-view/list-view.android.ts
  tns-core-modules/ui/list-view/list-view.d.ts
  tns-core-modules/ui/list-view/list-view.ios.ts
Labels: cla: yes, in progress

#6092 test(): add scenarios for listview scrolling
  apps/app/ui-tests-app/list-view/list-view.ts
  apps/app/ui-tests-app/list-view/list-view.xml
Labels: cla: yes, in progress

#6023 feat(CSS): import of relative paths
  tests/app/ui/styling/style-tests.ts
  tns-core-modules/ui/styling/style-scope.d.ts
  tns-core-modules/ui/styling/style-scope.ts
Labels: cla: yes, in progress

#6093 chore(android): update AndroidP sdk version check
  tns-core-modules/ui/frame/fragment.transitions.android.ts
Labels: cla: yes, in progress

#6033 feat(list-picker): add textField, valueField and selectedValue properties
  apps/app/ui-tests-app/list-picker/list-picker-json-array.ts
  apps/app/ui-tests-app/list-picker/list-picker-json-array.xml
  apps/app/ui-tests-app/list-picker/main-page.ts
  tns-core-modules/ui/list-picker/list-picker-common.ts
  tns-core-modules/ui/list-picker/list-picker.android.ts
  tns-core-modules/ui/list-picker/list-picker.ios.ts
Labels: cla: yes, in progress

#6116 fix: iOS TimePicker minuteInterval property
  tns-core-modules/ui/time-picker/time-picker.ios.ts
Labels: cla: yes, in progress

#6127 feat(image-asset-ios): add autoScaleFactor option to switch auto scaling
  tests/app/image-source/image-source-tests.ts
  tns-core-modules/image-asset/image-asset-common.ts
  tns-core-modules/image-asset/image-asset.d.ts
  tns-core-modules/image-asset/image-asset.ios.ts
  tns-core-modules/image-source/image-source.ios.ts
Labels: feature, in progress

#6135 chore: update file-system api reference
  tns-core-modules/file-system/file-system.d.ts
Labels: cla: yes, in progress

#6129 feat(android): migrate to support library apis
  tests/app/navigation/custom-transition.android.ts
  tns-core-modules/application/application.android.ts
  tns-core-modules/application/application.d.ts
  tns-core-modules/ui/core/view/view.android.ts
  tns-core-modules/ui/core/view/view.d.ts
  tns-core-modules/ui/editable-text-base/editable-text-base.android.ts
  tns-core-modules/ui/frame/activity.android.ts
  tns-core-modules/ui/frame/fragment.android.ts
  tns-core-modules/ui/frame/fragment.transitions.android.ts
  tns-core-modules/ui/frame/fragment.transitions.d.ts
  tns-core-modules/ui/frame/frame.android.ts
  tns-core-modules/ui/frame/frame.d.ts
  tns-core-modules/ui/page/page.android.ts
  tns-core-modules/ui/tab-view/tab-view.android.ts
  tns-core-modules/ui/transition/fade-transition.android.ts
  tns-core-modules/ui/transition/flip-transition.android.ts
  tns-core-modules/ui/transition/slide-transition.android.ts
  tns-core-modules/ui/transition/transition.android.ts
  tns-core-modules/ui/transition/transition.d.ts
  tns-core-modules/ui/transition/transition.ios.ts
  tns-core-modules/utils/utils.android.ts
Labels: cla: yes, in progress
