Repository NativeScript/NativeScript, pull requests merged in 2018-12, with the labels that each got.

#6646 update LICENSE
  LICENSE
Labels: cla: yes

#6652 feat(tabview): add androidSwipeEnabled property
  apps/app/ui-tests-app/tab-view/main-page.ts
  apps/app/ui-tests-app/tab-view/tab-view-android-swipe.xml
  tns-core-modules/ui/tab-view/tab-view-common.ts
  tns-core-modules/ui/tab-view/tab-view.android.ts
  tns-core-modules/ui/tab-view/tab-view.d.ts
Labels: cla: yes, e2e test needed, in progress, os: android

#6655 fix(modals): regression with modals in angular
  tns-core-modules/ui/core/view/view-common.ts
Labels: cla: yes, in progress

#6680 Merge release in master
  CHANGELOG.md
  tns-core-modules/package.json
Labels: cla: yes, in progress

#6681 chore: bump versions
  tns-core-modules/package.json
  tns-platform-declarations/package.json
Labels: cla: yes, in progress

#6683 svetoslavtsenov/update contrinuting
  CONTRIBUTING.md
Labels: cla: yes, in progress

#6677 fix(android): nested fragment disappears on parent fragment removal
  tns-core-modules/ui/frame/fragment.android.ts
  tns-core-modules/ui/frame/fragment.transitions.android.ts
  tns-core-modules/ui/frame/frame-common.ts
  tns-core-modules/ui/frame/frame.android.ts
  tns-core-modules/ui/tab-view/tab-view.android.ts
  tns-platform-declarations/android/org.nativescript.widgets.d.ts
Labels: cla: yes, in progress

#6409 feat(view): added iOS parameter for modal presentation style
  apps/app/ui-tests-app/modal-view/modal-view.ts
  tests/app/ui/page/page-tests-common.ts
  tns-core-modules/ui/core/view-base/view-base.d.ts
  tns-core-modules/ui/core/view/view-common.ts
  tns-core-modules/ui/core/view/view.android.ts
  tns-core-modules/ui/core/view/view.ios.ts
Labels: cla: yes, in progress, ♥ community PR

#6428 fix(ios delegate) Eliminate crash on selector looking for "Window"
  tns-core-modules/application/application.ios.ts
Labels: cla: yes, in progress

#6705 chore: restore tabroot/resetrootview tests
  tests/app/testRunner.ts
  tests/app/ui/root-view/reset-root-view-tests.ts
  tests/app/ui/tab-view/tab-view-root-tests.ts
  tests/package.json
Labels: cla: yes, in progress

#6665 feat(HMR): apply changes in application styles at runtime
  tests/app/app/app-new.css
  tests/app/app/app-new.scss
  tests/app/app/application.css
  tests/app/app/mainPage.ts
  tests/app/app/mainPage.xml
  tests/app/livesync/livesync-tests.ts
  tests/app/testRunner.ts
  tns-core-modules/application/application-common.ts
  tns-core-modules/application/application.android.ts
  tns-core-modules/application/application.ios.ts
  tns-core-modules/module.d.ts
  tns-core-modules/ui/frame/frame.android.ts
  tns-core-modules/ui/page/page-common.ts
  tns-core-modules/ui/styling/style-scope.d.ts
  tns-core-modules/ui/styling/style-scope.ts
Labels: cla: yes, in progress

#6458 feat(Cache): better error handling
  tns-core-modules/http/http-request/http-request.android.ts
  tns-core-modules/ui/image-cache/image-cache-common.ts
  tns-core-modules/ui/image-cache/image-cache.android.ts
  tns-core-modules/ui/image-cache/image-cache.d.ts
  tns-core-modules/ui/image-cache/image-cache.ios.ts
  tns-platform-declarations/android/org.nativescript.widgets.d.ts
Labels: cla: yes, in progress

#6717 chore(docs): Upgrade typedoc to version 0.13.0
  package.json
Labels: cla: yes, in progress

#6721 Fix some lint errors
  apps/app/css-perf-test/main-page.ts
  apps/app/cuteness.io/main-page.ts
Labels: cla: yes, in progress

#6726 Release 5.1.1
  CHANGELOG.md
  apps/app/css-perf-test/main-page.ts
  apps/app/cuteness.io/main-page.ts
  tns-core-modules/package.json
  tns-core-modules/ui/frame/frame.android.ts
  tns-platform-declarations/package.json
Labels: cla: no, in progress

#6723 fix(modal): Fix crash if modal is destroyed before dismissed in Android
  tns-core-modules/ui/core/view/view.android.ts
Labels: cla: yes, in progress

#6729 fix-next: undefined root view when reapplying styles
  tns-core-modules/application/application-common.ts
Labels: cla: yes, in progress

#6691 set the correct application theme while creating the dialog fragment
  tns-core-modules/ui/core/view/view.android.ts
Labels: cla: yes, in progress, os: android
