Repository NativeScript/NativeScript, pull requests merged in 2018-11, with the labels that each got.

#6484 chore: cut the 5.0.1 release
  tns-core-modules/package.json
Labels: cla: yes, in progress

#6464 fix: prevent errors on launching manual testing app
  apps/package.json
  apps/tsconfig.json
Labels: cla: yes, in progress

#6487 Resolve incorrect name of listener when unsubscribing causing Views to be leaked in memory
  tns-core-modules/ui/styling/style-scope.ts
Labels: cla: yes, in progress

#6489 fix(android): back navigation on app suspend/resume
  tns-core-modules/ui/frame/frame.android.ts
Labels: cla: yes, in progress

#6485 docs: add 5.0.0 changelog
  CHANGELOG.md
Labels: cla: yes, in progress

#6495 fix(android): IllegalStateException with tabview&nested frames
  tns-core-modules/ui/frame/frame.android.ts
Labels: cla: yes, in progress

#6517 test: add test for #6490
  tests/app/ui/helper.ts
  tests/app/ui/tab-view/tab-view-navigation-tests.ts
  tests/package.json
Labels: cla: yes, in progress

#6365 feat: add number & phone inputType for prompt dialog
  apps/app/ui-tests-app/dialogs/dialogs.xml
  apps/app/ui-tests-app/dialogs/view-model.ts
  tns-core-modules/ui/dialogs/dialogs-common.ts
  tns-core-modules/ui/dialogs/dialogs.android.ts
  tns-core-modules/ui/dialogs/dialogs.d.ts
  tns-core-modules/ui/dialogs/dialogs.ios.ts
Labels: cla: yes, docs needed, in progress, ♥ community PR

#6522 release: cut the 5.0.2 release
  CHANGELOG.md
  tns-core-modules/package.json
  tns-platform-declarations/package.json
Labels: cla: yes, in progress

#6453 fix(image): uncaught error in promise with image handling
  tns-core-modules/http/http-request/http-request.ios.ts
  tns-core-modules/http/http.ts
Labels: cla: yes, in progress

#6528 fix: nested frames order with tabs & suspend/resume
  tns-core-modules/ui/frame/frame-common.ts
  tns-core-modules/ui/frame/frame.d.ts
  tns-core-modules/ui/tab-view/tab-view.android.ts
  tns-core-modules/ui/tab-view/tab-view.ios.ts
Labels: cla: yes, in progress

#6467 fix: crash on Android Tab-View #6466
  tns-core-modules/ui/tab-view/tab-view.android.ts
Labels: cla: yes, in progress

#6556 chore: update to TS 3
  apps/package.json
  e2e/modal-navigation/package.json
  package.json
  tests/package.json
  tns-platform-declarations/package.json
Labels: cla: yes, in progress

#6561 fix(ios): safe area handling in scrollview
  apps/app/ui-tests-app/issues/issue-6439.css
  apps/app/ui-tests-app/issues/issue-6439.xml
  apps/app/ui-tests-app/issues/issue-ng-repo-1599.css
  apps/app/ui-tests-app/issues/issue-ng-repo-1599.xml
  apps/app/ui-tests-app/issues/main-page.ts
  apps/app/ui-tests-app/scroll-view/safe-area-sub-element.xml
  tns-core-modules/ui/core/view/view.ios.ts
Labels: cla: yes, e2e test needed, in progress

#6578 test(ios): add repeater and webview safe area tests
  tests/app/testRunner.ts
  tests/app/ui/repeater/repeater-safe-area-tests.ts
  tests/app/ui/web-view/web-view-safe-area-tests.ts
Labels: cla: yes, in progress

#6584 docs: cut the 5.0.3 release
  CHANGELOG.md
  apps/app/ui-tests-app/dialogs/dialogs.xml
  apps/app/ui-tests-app/dialogs/view-model.ts
  apps/app/ui-tests-app/issues/issue-6439.css
  apps/app/ui-tests-app/issues/issue-6439.xml
  apps/app/ui-tests-app/issues/issue-ng-repo-1599.css
  apps/app/ui-tests-app/issues/issue-ng-repo-1599.xml
  apps/app/ui-tests-app/issues/main-page.ts
  apps/app/ui-tests-app/scroll-view/safe-area-root-element.xml
  apps/app/ui-tests-app/scroll-view/safe-area-sub-element.xml
  apps/package.json
  e2e/modal-navigation/package.json
  package.json
  tests/app/testRunner.ts
  tests/app/ui/helper.ts
  tests/app/ui/layouts/safe-area-tests.ts
  tests/app/ui/list-view/list-view-tests.ts
  tests/app/ui/repeater/repeater-safe-area-tests.ts
  tests/app/ui/tab-view/tab-view-navigation-tests.ts
  tests/app/ui/web-view/web-view-safe-area-tests.ts
  tests/package.json
  tns-core-modules/http/http-request/http-request.ios.ts
  tns-core-modules/http/http.ts
  tns-core-modules/package.json
  tns-core-modules/ui/core/view/view.ios.ts
  tns-core-modules/ui/dialogs/dialogs-common.ts
  tns-core-modules/ui/dialogs/dialogs.android.ts
  tns-core-modules/ui/dialogs/dialogs.d.ts
  tns-core-modules/ui/dialogs/dialogs.ios.ts
  tns-core-modules/ui/frame/frame-common.ts
  tns-core-modules/ui/frame/frame.d.ts
  tns-core-modules/ui/scroll-view/scroll-view.ios.ts
  tns-core-modules/ui/tab-view/tab-view.android.ts
  tns-core-modules/ui/tab-view/tab-view.ios.ts
  tns-platform-declarations/package.json
Labels: cla: no, in progress

#6595 fix(back-navigation): app freeze on going back in parent frame
  tns-core-modules/ui/frame/frame-common.ts
Labels: bug, cla: yes, in progress

#6589 fix(android-fragment): child already has a parent
  tns-core-modules/ui/frame/frame.android.ts
Labels: cla: yes, in progress

#6617 Release 5.0.4
  CHANGELOG.md
  tns-core-modules/package.json
  tns-core-modules/ui/frame/frame-common.ts
  tns-core-modules/ui/frame/frame.android.ts
  tns-platform-declarations/package.json
Labels: cla: yes, in progress

#6619 Merge release in master
  CHANGELOG.md
Labels: cla: yes, in progress

#6622 release: cut the 5.0.5 release
  CHANGELOG.md
  tns-core-modules/package.json
  tns-platform-declarations/package.json
Labels: cla: yes, in progress

#6624 release
  CHANGELOG.md
Labels: cla: yes, in progress

#6342 fix(android-styling): correctly detect if drawable uses ColorFilter
  tests/app/ui/button/button-tests.ts
  tns-core-modules/ui/styling/background.android.ts
Labels: cla: yes, in progress, ♥ community PR

#6529 doc: update instruction on how to release tns-core-modules
  CONTRIBUTING.md
  merge-guidance-schema.png
  release-contribution-guide-schema.png
Labels: cla: yes, in progress

#6636 fix(searchbar): isEnabled and isUserInteractionEnabled
  tns-core-modules/ui/search-bar/search-bar.android.ts
  tns-core-modules/ui/search-bar/search-bar.ios.ts
Labels: cla: yes, in progress

#6635 fix(tests): Sporadic failures after upgrade to WebKit 12.0
  tests/app/ui/helper.ts
  tests/app/ui/text-field/text-field-tests.ts
Labels: cla: yes, in progress, os: ios

#6631 feat(ActionBar): apply text color when largeTitletextAttribute is set on iOS
  tns-core-modules/ui/action-bar/action-bar.ios.ts
Labels: cla: yes, in progress

#6639 fix(ui/enums) make exported enums compatible with TypeScript and the corresponding properties
  tns-core-modules/ui/enums/enums.d.ts
Labels: cla: yes, in progress

#6637 feat(modals): Enable modal dialog chaining in IOS
  apps/app/ui-tests-app/modal-view/login-page.ts
  apps/app/ui-tests-app/modal-view/login-page.xml
  apps/app/ui-tests-app/modal-view/modal-view.ts
  apps/app/ui-tests-app/modal-view/modal-view.xml
  tests/app/ui/page/page-tests-common.ts
  tests/app/ui/page/page-tests.ios.ts
  tns-core-modules/ui/core/view/view-common.ts
  tns-core-modules/ui/core/view/view.android.ts
  tns-core-modules/ui/core/view/view.ios.ts
Labels: cla: yes, e2e test needed, in progress

#6640 feat(scrollview): add isScrollEnabled property
  tns-core-modules/ui/core/view/view.android.ts
  tns-core-modules/ui/scroll-view/scroll-view-common.ts
  tns-core-modules/ui/scroll-view/scroll-view.android.ts
  tns-core-modules/ui/scroll-view/scroll-view.d.ts
  tns-core-modules/ui/scroll-view/scroll-view.ios.ts
  tns-platform-declarations/android/org.nativescript.widgets.d.ts
Labels: cla: yes, docs needed
