Repository NativeScript/NativeScript, pull requests merged in 2018-03, with the labels that each got.

#5473 fix(image-source.ios): case statement, allow jpg and jpeg
  tns-core-modules/image-source/image-source.ios.ts
Labels: cla: yes, ♥ community PR

#5479 fix(frame): add generic frame cleanup logic after modal dialog close
  tests/app/ui/page/modal-tab-page.ts
  tests/app/ui/page/modal-tab-page.xml
  tests/app/ui/page/modal-tab-root.ts
  tests/app/ui/page/modal-tab-root.xml
  tests/app/ui/page/page-tests-common.ts
  tns-core-modules/ui/core/view-base/view-base.ts
  tns-core-modules/ui/frame/frame-common.ts
Labels: bug, cla: yes

#5186 fix: throw if global css file is not found in webpack context
  tns-core-modules/application/application-common.ts
Labels: cla: yes, in progress

#5466 fix-next(css): CSS not applied to "drawerContent" when RadSideDrawer is used as root
  tests/app/testRunner.ts
  tests/app/ui/helper.ts
  tests/app/ui/root-view/mymodule/MyControl.css
  tests/app/ui/root-view/mymodule/MyControl.ts
  tests/app/ui/root-view/mymodule/package.json
  tests/app/ui/root-view/reset-root-view-tests.ts
  tests/app/ui/root-view/root-modules/custom-component-root.css
  tests/app/ui/root-view/root-modules/custom-component-root.xml
  tests/app/ui/root-view/root-modules/gridlayout-root.css
  tests/app/ui/root-view/root-modules/gridlayout-root.xml
  tests/app/ui/root-view/root-modules/tabview-root.css
  tests/app/ui/root-view/root-modules/tabview-root.xml
  tests/app/ui/root-view/root-view-tests.ts
  tns-core-modules/ui/builder/builder.ts
Labels: cla: yes, in progress, ns 4.0

#5435 fix-next(tabview): fix tab title layout in modal root tabview Fixes #5392
  apps/app/ui-tests-app/modal-view/login-page.xml
  tns-core-modules/ui/core/view/view.android.ts
Labels: bug, cla: yes, in progress, ns 4.0, os: android

#5490 fix(android-images): set decodeHeight/decodeWidth default values to dip
  tns-core-modules/ui/image/image-common.ts
  tns-core-modules/ui/image/image.android.ts
Labels: breaking-change, bug, in progress, ns 4.0

#5496 feat(modal): introduce stretched param to showModal method
  apps/app/ui-tests-app/modal-view/login-page.xml
  apps/app/ui-tests-app/modal-view/modal-view.ts
  apps/app/ui-tests-app/modal-view/modal-view.xml
  tns-core-modules/ui/core/view/view-common.ts
  tns-core-modules/ui/core/view/view.android.ts
  tns-core-modules/ui/core/view/view.d.ts
  tns-core-modules/ui/core/view/view.ios.ts
Labels: bug, in progress, ns 4.0

#5495 fix-next(tabview): visually pre-load tab items on android
  apps/app/ui-tests-app/app.ts
  tests/app/ui/tab-view/tab-view-navigation-tests.ts
  tests/app/ui/tab-view/tab-view-root-tests.ts
  tns-core-modules/ui/frame/frame.android.ts
  tns-core-modules/ui/tab-view/tab-view-common.ts
  tns-core-modules/ui/tab-view/tab-view.android.ts
  tns-core-modules/ui/tab-view/tab-view.ios.ts
Labels: cla: yes, in progress, ns 4.0

#5475 fix(animations): change throw -> trace to avoid unnecessary app crash
  tests/app/ui/animation/animation-tests.ts
  tns-core-modules/ui/animation/animation-common.ts
  tns-core-modules/ui/animation/animation.android.ts
  tns-core-modules/ui/animation/animation.ios.ts
  tns-core-modules/ui/animation/keyframe-animation.ts
Labels: cla: yes, ♥ community PR

#5257 feat(webpack): mark the CSS type for stylable views explicitly
  tns-core-modules/ui/action-bar/action-bar-common.ts
  tns-core-modules/ui/activity-indicator/activity-indicator-common.ts
  tns-core-modules/ui/border/border.ts
  tns-core-modules/ui/button/button-common.ts
  tns-core-modules/ui/core/view/view-common.ts
  tns-core-modules/ui/core/view/view.d.ts
  tns-core-modules/ui/date-picker/date-picker-common.ts
  tns-core-modules/ui/frame/frame-common.ts
  tns-core-modules/ui/html-view/html-view-common.ts
  tns-core-modules/ui/image/image-common.ts
  tns-core-modules/ui/label/label.android.ts
  tns-core-modules/ui/label/label.ios.ts
  tns-core-modules/ui/layouts/absolute-layout/absolute-layout-common.ts
  tns-core-modules/ui/layouts/dock-layout/dock-layout-common.ts
  tns-core-modules/ui/layouts/flexbox-layout/flexbox-layout-common.ts
  tns-core-modules/ui/layouts/grid-layout/grid-layout-common.ts
  tns-core-modules/ui/layouts/stack-layout/stack-layout-common.ts
  tns-core-modules/ui/layouts/wrap-layout/wrap-layout-common.ts
  tns-core-modules/ui/list-picker/list-picker-common.ts
  tns-core-modules/ui/list-view/list-view-common.ts
  tns-core-modules/ui/page/page-common.ts
  tns-core-modules/ui/placeholder/placeholder.android.ts
  tns-core-modules/ui/progress/progress-common.ts
  tns-core-modules/ui/proxy-view-container/proxy-view-container.ts
  tns-core-modules/ui/repeater/repeater.ts
  tns-core-modules/ui/scroll-view/scroll-view-common.ts
  tns-core-modules/ui/search-bar/search-bar-common.ts
  tns-core-modules/ui/segmented-bar/segmented-bar-common.ts
  tns-core-modules/ui/slider/slider-common.ts
  tns-core-modules/ui/switch/switch-common.ts
  tns-core-modules/ui/tab-view/tab-view-common.ts
  tns-core-modules/ui/text-field/text-field-common.ts
  tns-core-modules/ui/text-view/text-view.android.ts
  tns-core-modules/ui/text-view/text-view.ios.ts
  tns-core-modules/ui/time-picker/time-picker-common.ts
  tns-core-modules/ui/web-view/web-view-common.ts
Labels: cla: yes, in progress

#5445 test(e2e): add modal-navigation app tests
  .gitignore
  DevelopmentWorkflow.md
  e2e/modal-navigation/.vscode/launch.json
  e2e/modal-navigation/README.md
  e2e/modal-navigation/app/app.ts
  e2e/modal-navigation/app/bundle-config.ts
  e2e/modal-navigation/app/home/home-page.ts
  e2e/modal-navigation/app/modal-nested/modal-nested-page.xml
  e2e/modal-navigation/app/modal/modal-page.ts
  e2e/modal-navigation/app/modal/modal-page.xml
  e2e/modal-navigation/app/vendor-platform.android.ts
  e2e/modal-navigation/app/vendor-platform.ios.ts
  e2e/modal-navigation/app/vendor.ts
  e2e/modal-navigation/e2e/config/appium.capabilities.json
  e2e/modal-navigation/e2e/config/mocha.opts
  e2e/modal-navigation/e2e/e2e-spec-app-root/app-root-modal-frame.e2e-spec.ts
  e2e/modal-navigation/e2e/e2e-spec-app-root/app-root-modal-page.e2e-spec.ts
  e2e/modal-navigation/e2e/e2e-spec-app-root/app-root-modal-tab.e2e-spec.ts
  e2e/modal-navigation/e2e/e2e-spec-tab-root/tab-root-modal-frame.e2e-spec.ts
  e2e/modal-navigation/e2e/e2e-spec-tab-root/tab-root-modal-page.e2e-spec.ts
  e2e/modal-navigation/e2e/e2e-spec-tab-root/tab-root-modal-tab.e2e-spec.ts
  e2e/modal-navigation/e2e/screen.ts
  e2e/modal-navigation/e2e/setup.ts
  e2e/modal-navigation/e2e/shared.e2e-spec.ts
  e2e/modal-navigation/e2e/tsconfig.json
  e2e/modal-navigation/package.json
  e2e/modal-navigation/tsconfig.json
  e2e/modal-navigation/webpack.config.js
  package.json
  tsconfig.json
Labels: cla: yes, in progress

#5517 feat(ios-image-source): standardize quality scale in image-source
  tests/app/image-source/image-source-tests.ts
  tns-core-modules/image-source/image-source.d.ts
  tns-core-modules/image-source/image-source.ios.ts
Labels: cla: yes, ♥ community PR

#5489 chore(docs): Update writing-tests.md with note about code snippets comments
  WritingUnitTests.md
Labels: cla: yes, in progress

#5527 feat(frame): rework frame retrieval api
  package.json
  tests/app/ui/frame/frame-tests-common.ts
  tns-core-modules/ui/frame/frame-common.ts
  tns-core-modules/ui/frame/frame.android.ts
  tns-core-modules/ui/frame/frame.d.ts
  tns-core-modules/ui/tab-view/tab-view.android.ts
  tns-core-modules/ui/tab-view/tab-view.ios.ts
Labels: cla: yes, in progress, ns 4.0

#5537 feat(view): expose method for android back override
  tns-core-modules/ui/core/view/view-common.ts
  tns-core-modules/ui/core/view/view.android.ts
  tns-core-modules/ui/core/view/view.d.ts
  tns-core-modules/ui/frame/frame.android.ts
  tns-core-modules/ui/tab-view/tab-view.android.ts
Labels: cla: yes, in progress, ns 4.0

#5533 fix-next(frame): remove current entry fragment on reset root view
  e2e/modal-navigation/e2e/e2e-spec-tab-root/tab-root-modal-frame.e2e-spec.ts
  e2e/modal-navigation/e2e/e2e-spec-tab-root/tab-root-modal-page.e2e-spec.ts
  e2e/modal-navigation/e2e/e2e-spec-tab-root/tab-root-modal-tab.e2e-spec.ts
  e2e/modal-navigation/package.json
  e2e/modal-navigation/tsconfig.json
  tns-core-modules/ui/frame/frame.android.ts
Labels: cla: yes, in progress

#5544 fix(uilabel): line height setter should not break line break mode
  tns-core-modules/ui/text-base/text-base.ios.ts
Labels: cla: yes, in progress, ♥ community PR

#5531 zonedCallback in connectivity module
  tns-core-modules/connectivity/connectivity.android.ts
  tns-core-modules/connectivity/connectivity.ios.ts
Labels: cla: yes, in progress

#5546 fix(image): apply tintColor correctly on iOS
  tns-core-modules/ui/image/image.ios.ts
Labels: cla: yes, in progress, ♥ community PR

#5530 Update enums.d.ts
  tns-core-modules/ui/enums/enums.d.ts
Labels: cla: yes, ♥ community PR

#5548 refactor(e2e/modal-navigation): stretch modal tab view
  e2e/modal-navigation/app/home/home-page.ts
Labels: cla: yes, in progress

#5558 html-view: update reference to native iOS component in code comment
  tns-core-modules/ui/html-view/html-view.d.ts
Labels: cla: yes, ♥ community PR

#5551 Update http.ts ( To get this work in iOS )
  tns-core-modules/http/http.ts
Labels: cla: yes, ♥ community PR

#5556 fix(image): image aspect dimensions for ImageSource.fromAsset(...)
  tests/app/image-source/image-source-tests.ts
  tns-core-modules/image-asset/image-asset-common.ts
Labels: cla: yes, in progress

#5557 Feat(List-View) : Add the Ability to check if an item is visible or not.
  tests/app/ui/list-view/list-view-tests.ts
  tns-core-modules/ui/list-view/list-view-common.ts
  tns-core-modules/ui/list-view/list-view.android.ts
  tns-core-modules/ui/list-view/list-view.d.ts
  tns-core-modules/ui/list-view/list-view.ios.ts
Labels: cla: yes, ♥ community PR

#5563 fix(android/text ios/text): allow -1 to be a valid binding value
  tns-core-modules/ui/editable-text-base/editable-text-base-common.ts
  tns-core-modules/ui/editable-text-base/editable-text-base.android.ts
  tns-core-modules/ui/text-base/text-base-common.ts
  tns-core-modules/ui/text-base/text-base.android.ts
  tns-core-modules/ui/text-base/text-base.d.ts
  tns-core-modules/ui/text-base/text-base.ios.ts
Labels: cla: yes, ♥ community PR

#5524 add required interface for generalized listview comonent
  tns-core-modules/ui/list-view/list-view-common.ts
  tns-core-modules/ui/list-view/list-view.d.ts
Labels: cla: yes, in progress

#5573 fix(webpack): register wrap layout
  tns-core-modules/bundle-entry-points.ts
Labels: cla: yes, in progress

#5568 feat(ios-list-view): introduce iosEstimatedRowHeight property.
  apps/app/ui-tests-app/list-view/scrolling-and-sizing.xml
  tns-core-modules/ui/list-view/list-view-common.ts
  tns-core-modules/ui/list-view/list-view.d.ts
  tns-core-modules/ui/list-view/list-view.ios.ts
Labels: in progress, ns 4.0

#5581 refactor(ios): clean up iOS8 or lower specific checks in codebase
  tests/app/ui/list-view/list-view-tests.ts
  tns-core-modules/ui/core/view/view.ios.ts
  tns-core-modules/ui/dialogs/dialogs.ios.ts
  tns-core-modules/ui/list-view/list-view.ios.ts
Labels: cla: yes, in progress

#5584 refactor(ios-webview) Remove useless code
  tns-core-modules/ui/web-view/web-view.ios.ts
Labels: cla: yes, ♥ community PR
