Repository NativeScript/NativeScript, pull requests merged in 2018-06, with the labels that each got.

#5906 chore: Fix TS transpile error with 2.9
  tns-core-modules/globals/globals.ts
Labels: cla: yes, in progress

#5915 update LICENSE
  LICENSE
Labels: cla: yes, in progress

#5908 fix(ios): set current tab as topmost frame on load
  tests/app/ui/tab-view/tab-view-root-tests.ts
  tests/package.json
  tns-core-modules/ui/tab-view/tab-view.ios.ts
Labels: cla: yes, in progress

#5917 fix(android): label width shrinking on shorter text change
  tests/app/ui/label/label-tests.ts
  tns-core-modules/ui/text-base/text-base-common.ts
Labels: cla: yes, in progress

#5943 chore(modal-navigation): Add Dialogs tests
  e2e/modal-navigation/e2e/modal-frame.e2e-spec.ts
  e2e/modal-navigation/e2e/modal-layout.e2e-spec.ts
  e2e/modal-navigation/e2e/modal-page.e2e-spec.ts
  e2e/modal-navigation/e2e/modal-tab.e2e-spec.ts
  e2e/modal-navigation/e2e/screen.ts
  e2e/modal-navigation/e2e/shared.e2e-spec.ts
Labels: in progress

#5856 fix(Image): catch Response content may not be converted to an Image
  tns-core-modules/http/http.ts
  tns-core-modules/ui/image/image-common.ts
Labels: cla: yes, in progress

#5947 fix(android): prevent error during tear down
  tns-core-modules/ui/frame/frame.android.ts
Labels: cla: yes, in progress

#5949 fix(android): NavigationButton was read as "Button" by screenreaders.
  tests/app/ui/action-bar/action-bar-tests.android.ts
  tns-core-modules/ui/action-bar/action-bar.android.ts
Labels: cla: yes, in progress

#5953 test(): add more timeout to tab navigations tests
  tests/app/ui/tab-view/tab-view-root-tests.ts
Labels: cla: yes, in progress

#5957 test(): move the tab view tests before frame tests
  tests/app/testRunner.ts
Labels: cla: yes, in progress

#5929 feat: Flexible Error/Exception handling
  CONTRIBUTING.md
  HandlingErrors.md
  tests/app/testRunner.ts
  tests/app/trace/trace-error-tests.ts
  tns-core-modules/trace/trace.d.ts
  tns-core-modules/trace/trace.ts
Labels: cla: yes, in progress

#5791 fix(core/properties): Fix typings for nativeValueChange
  tns-core-modules/ui/core/properties/properties.d.ts
Labels: cla: yes, in progress

#5968 refactor: animation app
  e2e/animation/app/App_Resources/Android/app.gradle
  e2e/animation/app/chaining-with-animation-set/page.ts
  e2e/animation/app/chaining-with-animation-set/page.xml
  e2e/animation/app/home/home-page.ts
  e2e/animation/app/home/home-page.xml
  e2e/animation/e2e/animation.e2e-spec.ts
  e2e/animation/e2e/screen.ts
  e2e/animation/package.json
Labels: cla: yes, in progress

#5960 fix(ios): safeAreaLayoutGuide fallback for iOS 10 cases
  tns-core-modules/ui/core/view/view.ios.ts
Labels: cla: yes, in progress

#5966 fix(modal): parent page invalid hierarchy handling [extended]
  tns-core-modules/ui/core/bindable/bindable.d.ts
  tns-core-modules/ui/core/bindable/bindable.ts
  tns-core-modules/ui/core/view/view.d.ts
  tns-core-modules/ui/core/view/view.ios.ts
  tns-core-modules/ui/dialogs/dialogs.ios.ts
Labels: cla: yes, in progress

#5979 fix normalisation formula
  tns-core-modules/image-source/image-source.ios.ts
Labels: cla: yes, in progress

#5967 feat: Pass NS app to the native app instead of presenting it over the root VC
  .gitignore
  tns-core-modules/application/application.ios.ts
  tns-core-modules/platforms/README.md
  tns-core-modules/platforms/ios/src/NativeScriptEmbedder.h
  tns-core-modules/platforms/ios/src/NativeScriptEmbedder.m
  tns-core-modules/platforms/ios/src/module.modulemap
  tns-core-modules/tns-core-modules.d.ts
  tns-core-modules/utils/utils.d.ts
  tns-core-modules/utils/utils.ios.ts
Labels: cla: yes, feature, in progress

#6007 fix(build): Add platforms/ios folder to produced NPM package
  tns-core-modules/package.json
Labels: bug, cla: yes, in progress
