Repository NativeScript/NativeScript, pull requests merged in 2018-10, with the labels that each got.

#6337 fix-next(flexbox): flex end for justify content
  tests/app/ui/layouts/layout-tests-helper.ts
  tests/app/ui/layouts/safe-area-tests.ts
  tests/app/ui/list-view/list-view-safe-area-tests.ts
  tests/app/ui/scroll-view/scroll-view-safe-area-tests.ts
  tns-core-modules/ui/layouts/flexbox-layout/flexbox-layout.ios.ts
Labels: cla: yes, in progress

#6344 fix-next: apply repeater onLayout initial values
  tns-core-modules/ui/repeater/repeater.ts
Labels: cla: yes, in progress

#6339 fix(android): nested frames on app suspend/resume
  tns-core-modules/ui/frame/frame.android.ts
Labels: cla: yes, in progress

#6330 fix(android): second livesync
  tns-core-modules/ui/frame/fragment.transitions.android.ts
Labels: cla: yes, in progress

#6354 chore: add iOS 12 entry
  e2e/config/appium.capabilities.json
Labels: in progress

#6358 chore: update n-dev- appium deps
  e2e/animation/package.json
  e2e/modal-navigation/package.json
Labels: cla: yes, in progress

#6350 chore: unify issue templates
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: cla: yes, in progress

#6351 feat(tslib): add tslib helpers to global
  package.json
  tests/package.json
  tns-core-modules/globals/decorators.ts
  tns-core-modules/globals/globals.ts
  tns-core-modules/globals/ts-helpers.ts
  tns-core-modules/inspector_modules.ios.ts
  tns-core-modules/package.json
  tns-core-modules/ui/styling/style-properties.ts
  tns-platform-declarations/package.json
Labels: cla: yes, in progress

#6325 feat: implement capitalization type option for prompt dialogs
  apps/app/ui-tests-app/dialogs/dialogs.xml
  apps/app/ui-tests-app/dialogs/view-model.ts
  tns-core-modules/ui/dialogs/dialogs-common.ts
  tns-core-modules/ui/dialogs/dialogs.android.ts
  tns-core-modules/ui/dialogs/dialogs.d.ts
  tns-core-modules/ui/dialogs/dialogs.ios.ts
Labels: cla: yes, e2e test needed, in progress

#6364 fix-next: ios 10 safe area backwards compat
  tns-core-modules/ui/core/view/view.ios.ts
  tns-core-modules/ui/page/page.ios.ts
Labels: cla: yes, in progress

#6374 chore: fix nav tests with cli next
  tests/app/navigation/navigation-tests.ts
  tests/app/testRunner.ts
  tests/app/ui/layouts/flexbox-layout-tests.ts
Labels: cla: yes, in progress

#6379 fix-next: drawer plugin viewcontroller init
  tns-core-modules/application/application.ios.ts
Labels: cla: yes, in progress

#6293 fix: nested fragments interact thru child fragment manager
  tests/app/ui/tab-view/tab-view-root-tests.ts
  tns-core-modules/ui/core/view/view.android.ts
  tns-core-modules/ui/frame/frame.android.ts
  tns-core-modules/ui/frame/frame.d.ts
  tns-core-modules/ui/tab-view/tab-view.android.ts
Labels: cla: yes, in progress

#6399 refactor(android): root fragment manager usage
  tns-core-modules/ui/core/view/view.android.ts
Labels: cla: yes, in progress

#6388 fix: Don't crash on missing resources in tab-view and action-bar
  tns-core-modules/ui/action-bar/action-bar-common.ts
  tns-core-modules/ui/action-bar/action-bar.android.ts
  tns-core-modules/ui/action-bar/action-bar.ios.ts
  tns-core-modules/ui/tab-view/tab-view-common.ts
  tns-core-modules/ui/tab-view/tab-view.android.ts
  tns-core-modules/ui/tab-view/tab-view.ios.ts
Labels: cla: yes, in progress

#6371 feat(application-settings): implemented allKeys method
  tests/app/application-settings/application-settings-tests.ts
  tns-core-modules/application-settings/application-settings.android.ts
  tns-core-modules/application-settings/application-settings.d.ts
  tns-core-modules/application-settings/application-settings.ios.ts
Labels: cla: yes, in progress

#6405 fix-next: restrict to safe area when transform
  tns-core-modules/ui/core/view/view.ios.ts
Labels: cla: yes, in progress

#6413 chore: bump versions to 5.0.0
  tns-core-modules/package.json
  tns-platform-declarations/package.json
Labels: cla: yes, in progress

#6415 chore: fix animations e2e app layout import
  e2e/animation/app/slide-in-effect/page.ts
Labels: cla: yes, in progress

#6403 refactor: restore animators api usage
  tests/app/navigation/custom-transition.android.ts
  tns-core-modules/ui/frame/fragment.android.ts
  tns-core-modules/ui/frame/fragment.transitions.android.ts
  tns-core-modules/ui/frame/fragment.transitions.d.ts
  tns-core-modules/ui/frame/frame.android.ts
  tns-core-modules/ui/frame/frame.d.ts
  tns-core-modules/ui/transition/fade-transition.android.ts
  tns-core-modules/ui/transition/flip-transition.android.ts
  tns-core-modules/ui/transition/slide-transition.android.ts
  tns-core-modules/ui/transition/transition.android.ts
  tns-core-modules/ui/transition/transition.d.ts
  tns-core-modules/ui/transition/transition.ios.ts
Labels: cla: yes, in progress

#6418 test(safe-area): add ui tests
  apps/app/ui-tests-app/layouts/main-page.ts
  apps/app/ui-tests-app/layouts/safe-area.xml
  apps/app/ui-tests-app/list-view/main-page.ts
  apps/app/ui-tests-app/list-view/safe-area.ts
  apps/app/ui-tests-app/list-view/safe-area.xml
  apps/app/ui-tests-app/resources/images/woods.jpg
  apps/app/ui-tests-app/scroll-view/main-page.ts
  apps/app/ui-tests-app/scroll-view/safe-area-images-overflow.xml
  apps/app/ui-tests-app/scroll-view/safe-area-images.xml
Labels: cla: yes, e2e test needed, in progress

#6422 chore: bump versions to 5.1.0
  tns-core-modules/package.json
  tns-platform-declarations/package.json
Labels: cla: yes, in progress

#6406 tests: Frame tests refactor
  tests/app/ui/frame/frame-tests-common.ts
Labels: cla: yes, in progress

#6423 docs: 5.0.0-rc changelog
  CHANGELOG.md
Labels: cla: yes, in progress

#6402 fix(observable-array): reduce no longer ignores zero as initial value
  tests/app/data/observable-array-tests.ts
  tns-core-modules/data/observable-array/observable-array.ts
Labels: cla: yes, in progress

#6434 test(safe-area): fix ios 12 landscape tests
  tests/app/ui/layouts/layout-tests-helper.ts
  tests/app/ui/layouts/safe-area-tests.ts
  tests/app/ui/list-view/list-view-safe-area-tests.ts
  tests/app/ui/page/page-tests-common.ts
  tests/app/ui/scroll-view/scroll-view-safe-area-tests.ts
Labels: cla: yes, in progress

#6373 fix(connectivity): making startMonitoring() behave on iOS as on Android
  tns-core-modules/connectivity/connectivity.ios.ts
Labels: cla: yes, in progress, ♥ community PR

#6443 fix-next: apply ios safe area before transform
  tns-core-modules/ui/core/view/view.ios.ts
Labels: cla: yes, in progress

#6445 refactor: fix ts compilation errors
  tns-core-modules/css/parser.ts
  tns-core-modules/ui/core/dependency-observable/dependency-observable.d.ts
  tns-core-modules/ui/core/dependency-observable/dependency-observable.ts
Labels: cla: yes, in progress

#6446 feat(frame): back in parent frame when back states available
  tests/app/navigation/navigation-tests.ts
  tns-core-modules/ui/frame/frame-common.ts
  tns-core-modules/ui/frame/frame.android.ts
  tns-core-modules/ui/frame/frame.ios.ts
Labels: in progress

#6449 feat(frame): add new actionBarVisibility property
  tests/app/ui/action-bar/action-bar-tests-common.ts
  tests/app/ui/action-bar/action-bar-tests.ios.ts
  tns-core-modules/ui/frame/frame-common.ts
  tns-core-modules/ui/frame/frame.android.ts
  tns-core-modules/ui/frame/frame.d.ts
  tns-core-modules/ui/frame/frame.ios.ts
Labels: cla: yes, in progress

#6450 chore: bump widgets version to 5.0.1
  tns-core-modules/package.json
Labels: cla: yes, in progress

#6421 fix-next(android): popExit fragment animation
  tns-core-modules/ui/frame/fragment.transitions.android.ts
  tns-core-modules/ui/frame/frame.android.ts
  tns-core-modules/ui/tab-view/tab-view.android.ts
Labels: cla: yes, in progress

#6455 fix-next: handle action bar safe area nesting
  apps/app/ui-tests-app/main-page.ts
  apps/app/ui-tests-app/nested-frames/full-screen-n-n.xml
  apps/app/ui-tests-app/nested-frames/full-screen-n-y.xml
  apps/app/ui-tests-app/nested-frames/full-screen-y-n.xml
  apps/app/ui-tests-app/nested-frames/full-screen-y-y.xml
  apps/app/ui-tests-app/nested-frames/main-page.ts
  apps/app/ui-tests-app/nested-frames/main-page.xml
  apps/app/ui-tests-app/nested-frames/mid-screen-n-n.xml
  apps/app/ui-tests-app/nested-frames/mid-screen-n-y.xml
  apps/app/ui-tests-app/nested-frames/mid-screen-y-n.xml
  apps/app/ui-tests-app/nested-frames/mid-screen-y-y.xml
  apps/app/ui-tests-app/nested-frames/nested-page.xml
  apps/app/ui-tests-app/nested-frames/tab-n-n.xml
  apps/app/ui-tests-app/nested-frames/tab-n-y.xml
  apps/app/ui-tests-app/nested-frames/tab-y-n.xml
  apps/app/ui-tests-app/nested-frames/tab-y-y.xml
  tns-core-modules/ui/core/view/view.ios.ts
  tns-core-modules/ui/frame/frame.ios.ts
  tns-core-modules/ui/page/page.ios.ts
Labels: cla: yes, e2e test needed, in progress

#6335 docs: updated iOS support documentation link for HtmlView
  tns-core-modules/ui/html-view/html-view.d.ts
Labels: cla: yes, ♥ community PR

#6457 fix-next: correct raising of layoutChanged event
  tns-core-modules/ui/core/view/view.ios.ts
Labels: cla: yes, in progress

#6463 fix-next(android): restore fade animation for simulated nav
  tns-core-modules/ui/frame/frame.android.ts
Labels: cla: yes, in progress

#6473 fix-next: revert "fix-next(android): restore fade animation for simulated nav"
  tns-core-modules/ui/frame/frame.android.ts
Labels: cla: yes, in progress

#6475 fix-next(ios): handle nesting in proxyViewContainer ng
  tns-core-modules/ui/core/view/view.ios.ts
  tns-core-modules/ui/page/page.ios.ts
Labels: cla: yes, in progress
