Repository NativeScript/NativeScript, pull requests merged in 2018-09, with the labels that each got.

#6240 refactor: remove obsolete ViewHelper.setBackground method
  tns-core-modules/ui/core/view/view.android.ts
  tns-core-modules/ui/search-bar/search-bar.android.ts
  tns-core-modules/ui/segmented-bar/segmented-bar.android.ts
  tns-core-modules/ui/styling/background.android.ts
Labels: cla: yes, in progress

#6246 fix: include mocha and chai typings
  e2e/modal-navigation/package.json
Labels: cla: yes, in progress

#6261 fix(modals): application activityBackPressed event not fired for modals
  e2e/modal-navigation/app/android-back-button/android-back-button-page.ts
  e2e/modal-navigation/app/android-back-button/android-back-button-page.xml
  e2e/modal-navigation/app/home/home-page.ts
  e2e/modal-navigation/app/home/home-page.xml
  tns-core-modules/ui/core/view/view.android.ts
Labels: cla: yes, in progress

#6255 fix: Page and Frame isLoaded undefined checks
  tns-core-modules/ui/core/view-base/view-base.ts
  tns-core-modules/ui/core/view/view.android.ts
  tns-core-modules/ui/frame/frame.android.ts
  tns-core-modules/ui/styling/style-scope.ts
Labels: cla: yes, in progress

#6266 docs: gather snippets from apps app folder only
  build-docs.sh
Labels: cla: yes, in progress

#6269 tests: include e2e test for "Android Back Btn Events"
  e2e/config/appium.capabilities.json
  e2e/modal-navigation/app/app.android.css
  e2e/modal-navigation/app/app.css
  e2e/modal-navigation/app/app.ios.css
  e2e/modal-navigation/app/home/home-page.xml
  e2e/modal-navigation/app/modal-no-page/modal-no-page.xml
  e2e/modal-navigation/e2e/android-back-button.e2e-spec.ts
  e2e/modal-navigation/e2e/modal-frame.e2e-spec.ts
  e2e/modal-navigation/e2e/modal-layout.e2e-spec.ts
  e2e/modal-navigation/e2e/modal-page.e2e-spec.ts
  e2e/modal-navigation/e2e/modal-tab.e2e-spec.ts
  e2e/modal-navigation/package.json
Labels: cla: no, in progress

#6171 fix(gestures)propagate touch to parent so that gestures can work
  apps/app/ui-tests-app/events/main-page.ts
  apps/app/ui-tests-app/events/swipe-event-passtrough.ts
  apps/app/ui-tests-app/events/swipe-event-passtrough.xml
  tns-core-modules/ui/core/view/view.android.ts
Labels: cla: yes, in progress

#6253 docs: document eachChild callback function
  tns-core-modules/ui/core/view-base/view-base.d.ts
  tns-core-modules/ui/core/view/view.d.ts
Labels: cla: yes, in progress

#6278 chore: extend swipe-event test
  apps/app/ui-tests-app/events/swipe-event-passtrough.xml
Labels: cla: no, in progress

#6204 feat: add ability to pass touch event thru parent view
  apps/app/ui-tests-app/layouts/main-page.ts
  apps/app/ui-tests-app/layouts/passThroughParent.ts
  apps/app/ui-tests-app/layouts/passThroughParent.xml
  tns-core-modules/ui/core/view/view-common.ts
  tns-core-modules/ui/core/view/view.android.ts
  tns-core-modules/ui/core/view/view.ios.ts
  tns-core-modules/ui/layouts/layout-base-common.ts
  tns-core-modules/ui/layouts/layout-base.android.ts
  tns-core-modules/ui/layouts/layout-base.d.ts
  tns-core-modules/ui/layouts/layout-base.ios.ts
Labels: cla: yes, e2e test needed, in progress

#6276 refactor: guard livesync for cases the app is not yet started
  tns-core-modules/ui/frame/frame-common.ts
Labels: cla: yes, in progress

#6102 refactor(core-modules): implement createNativeView and initNativeView for all components
  tests/app/ui/view/view-tests-common.ts
  tns-core-modules/application/application.ios.ts
  tns-core-modules/ui/action-bar/action-bar.android.ts
  tns-core-modules/ui/activity-indicator/activity-indicator.ios.ts
  tns-core-modules/ui/button/button.android.ts
  tns-core-modules/ui/button/button.ios.ts
  tns-core-modules/ui/core/view-base/view-base.ts
  tns-core-modules/ui/core/view/view-common.ts
  tns-core-modules/ui/core/view/view.ios.ts
  tns-core-modules/ui/date-picker/date-picker.android.ts
  tns-core-modules/ui/date-picker/date-picker.ios.ts
  tns-core-modules/ui/dialogs/dialogs-common.ts
  tns-core-modules/ui/editable-text-base/editable-text-base.android.ts
  tns-core-modules/ui/editable-text-base/editable-text-base.ios.ts
  tns-core-modules/ui/frame/frame.ios.ts
  tns-core-modules/ui/html-view/html-view.ios.ts
  tns-core-modules/ui/image/image.android.ts
  tns-core-modules/ui/image/image.ios.ts
  tns-core-modules/ui/label/label.android.ts
  tns-core-modules/ui/label/label.ios.ts
  tns-core-modules/ui/list-picker/list-picker.android.ts
  tns-core-modules/ui/list-picker/list-picker.ios.ts
  tns-core-modules/ui/list-view/list-view.android.ts
  tns-core-modules/ui/list-view/list-view.ios.ts
  tns-core-modules/ui/page/page.ios.ts
  tns-core-modules/ui/progress/progress.ios.ts
  tns-core-modules/ui/scroll-view/scroll-view.android.ts
  tns-core-modules/ui/scroll-view/scroll-view.ios.ts
  tns-core-modules/ui/search-bar/search-bar.android.ts
  tns-core-modules/ui/search-bar/search-bar.ios.ts
  tns-core-modules/ui/segmented-bar/segmented-bar.android.ts
  tns-core-modules/ui/segmented-bar/segmented-bar.ios.ts
  tns-core-modules/ui/slider/slider.android.ts
  tns-core-modules/ui/slider/slider.ios.ts
  tns-core-modules/ui/switch/switch.android.ts
  tns-core-modules/ui/switch/switch.ios.ts
  tns-core-modules/ui/tab-view/tab-view.ios.ts
  tns-core-modules/ui/text-base/text-base-common.ts
  tns-core-modules/ui/text-base/text-base.android.ts
  tns-core-modules/ui/text-base/text-base.d.ts
  tns-core-modules/ui/text-base/text-base.ios.ts
  tns-core-modules/ui/text-field/text-field.ios.ts
  tns-core-modules/ui/text-view/text-view.android.ts
  tns-core-modules/ui/text-view/text-view.ios.ts
  tns-core-modules/ui/time-picker/time-picker.android.ts
  tns-core-modules/ui/time-picker/time-picker.ios.ts
  tns-core-modules/ui/web-view/web-view.android.ts
  tns-core-modules/ui/web-view/web-view.ios.ts
Labels: cla: yes, in progress

#6230 feat(iOS): Safe Area Support
  .gitignore
  apps/app/ui-tests-app/button/background.xml
  apps/app/ui-tests-app/button/issue-4287.xml
  apps/app/ui-tests-app/css/clip-path.xml
  apps/app/ui-tests-app/css/margins-paddings-with-percentage.ts
  apps/app/ui-tests-app/issues/issue-1639.xml
  apps/app/ui-tests-app/issues/issue-3007.xml
  package.json
  tests/app/testRunner.ts
  tests/app/ui/helper.ts
  tests/app/ui/layouts/flexbox-layout-tests.ts
  tests/app/ui/layouts/grid-layout-tests.ts
  tests/app/ui/layouts/layout-tests-helper.ts
  tests/app/ui/layouts/safe-area-tests.ts
  tests/app/ui/list-view/list-view-safe-area-tests.ts
  tests/app/ui/list-view/list-view-view-model.ts
  tests/app/ui/page/page-tests-common.ts
  tests/app/ui/page/page-tests.ios.ts
  tests/app/ui/scroll-view/scroll-view-safe-area-tests.ts
  tests/app/ui/styling/style-tests.ts
  tests/app/ui/view/view-tests-common.ts
  tests/package.json
  tns-core-modules/ui/core/view/view-common.ts
  tns-core-modules/ui/core/view/view.android.ts
  tns-core-modules/ui/core/view/view.d.ts
  tns-core-modules/ui/core/view/view.ios.ts
  tns-core-modules/ui/layouts/absolute-layout/absolute-layout.ios.ts
  tns-core-modules/ui/layouts/dock-layout/dock-layout.ios.ts
  tns-core-modules/ui/layouts/flexbox-layout/flexbox-layout.ios.ts
  tns-core-modules/ui/layouts/grid-layout/grid-layout.ios.ts
  tns-core-modules/ui/layouts/layout-base.ios.ts
  tns-core-modules/ui/layouts/stack-layout/stack-layout.ios.ts
  tns-core-modules/ui/layouts/wrap-layout/wrap-layout.ios.ts
  tns-core-modules/ui/list-view/list-view-common.ts
  tns-core-modules/ui/list-view/list-view.ios.ts
  tns-core-modules/ui/page/page.ios.ts
  tns-core-modules/ui/repeater/repeater.ts
  tns-core-modules/ui/scroll-view/scroll-view.ios.ts
  tns-core-modules/ui/web-view/web-view-common.ts
Labels: cla: yes, docs needed, in progress
