Repository NativeScript/NativeScript, pull requests merged in 2019-04, with the labels that each got.

#7092 feat(android): implement a 'activityNewIntent' event
  tests/app/app/app.ts
  tns-core-modules/application/application.android.ts
  tns-core-modules/application/application.d.ts
  tns-core-modules/ui/frame/activity.android.ts
  tns-core-modules/ui/frame/frame.android.ts
  tns-core-modules/ui/frame/frame.d.ts
Labels: cla: yes, docs needed, in progress

#7099 docs: update widgets build script, readme, travis
  .travis.yml
  package.json
  tns-core-modules-widgets/CODE_OF_CONDUCT.md
  tns-core-modules-widgets/CONTRIBUTING.md
  tns-core-modules-widgets/README.md
  tns-core-modules-widgets/package.json
  tns-core-modules/package.json
Labels: cla: yes, in progress

#7098 chore: add deprecation console warnings
  tns-core-modules/ui/core/view/view-common.ts
  tns-core-modules/ui/frame/frame.android.ts
Labels: cla: yes, in progress

#7102 chore: merge release in master
  .travis.yml
  package.json
  tns-core-modules-widgets/CODE_OF_CONDUCT.md
  tns-core-modules-widgets/CONTRIBUTING.md
  tns-core-modules-widgets/README.md
  tns-core-modules-widgets/package.json
  tns-core-modules/package.json
Labels: in progress

#7055 feat(android): implement BorderDrawable outline
  apps/app/ui-tests-app/button/button-border.css
  apps/app/ui-tests-app/css/pixels.xml
  apps/app/ui-tests-app/flexbox/flexbox.css
  apps/app/ui-tests-app/issues/issue-3113.css
  tns-core-modules-widgets/android/widgets/src/main/java/org/nativescript/widgets/BorderDrawable.java
Labels: cla: yes, in progress

#7123 fix(label-android): numeric text ignores text-transform
  apps/app/ui-tests-app/issues/issue-5125.ts
  apps/app/ui-tests-app/issues/issue-5125.xml
  apps/app/ui-tests-app/issues/main-page.ts
  tns-core-modules/ui/text-base/text-base.android.ts
Labels: cla: yes, e2e test needed, in progress, patch

#7124 chore: merge release to master
  apps/app/ui-tests-app/issues/issue-5125.ts
  apps/app/ui-tests-app/issues/issue-5125.xml
  apps/app/ui-tests-app/issues/main-page.ts
  tns-core-modules/ui/text-base/text-base.android.ts
Labels: cla: yes, in progress

#7135 fix: no trace message on empty app.css
  tns-core-modules/ui/styling/style-scope.ts
Labels: cla: yes, in progress, patch

#7137 chore: merge release to master (#7135)
  tns-core-modules/ui/styling/style-scope.ts
Labels: cla: yes, in progress

#7147 chore: update gradlew
  tns-core-modules-widgets/android/gradlew
  tns-core-modules-widgets/android/gradlew.bat
  tns-core-modules-widgets/android/widgets/gradlew
  tns-core-modules-widgets/android/widgets/gradlew.bat
Labels: in progress

#7141 fix(ios): application.displayedEvent does not depend on trace to fire
  tests/app/app/app.ts
  tests/app/application/application-tests-common.ts
  tns-core-modules/application/application.ios.ts
Labels: in progress, patch

#7138 feat(switch): add property for off state background color
  apps/app/ui-tests-app/css/progress-switch.xml
  tns-core-modules/ui/switch/switch-common.ts
  tns-core-modules/ui/switch/switch.android.ts
  tns-core-modules/ui/switch/switch.d.ts
  tns-core-modules/ui/switch/switch.ios.ts
Labels: cla: yes, docs needed, e2e test needed, in progress

#7156 chore: merge release to master
  tests/app/app/app.ts
  tests/app/application/application-tests-common.ts
  tns-core-modules/application/application.ios.ts
Labels: cla: yes, in progress
