Repository NativeScript/NativeScript, pull requests merged in 2019-01, with the labels that each got.

#6732 refactor: cleanup unused elements
  tns-core-modules/ui/action-bar/action-bar.ios.ts
  tns-core-modules/ui/core/view/view.ios.ts
  tns-core-modules/ui/dialogs/dialogs.ios.ts
  tns-core-modules/ui/list-view/list-view-common.ts
  tns-core-modules/ui/list-view/list-view.ios.ts
  tns-core-modules/ui/scroll-view/scroll-view.ios.ts
  tns-core-modules/utils/utils.ios.ts
Labels: cla: yes, in progress

#6755 fix(tab-view): remove onBackPressed override
  tns-core-modules/ui/tab-view/tab-view.android.ts
Labels: bug, in progress

#6763 update LICENSE year
  LICENSE
Labels: cla: yes, in progress

#6761 chore: update LICENSE for tns-core-modules
  tns-core-modules/LICENSE
Labels: cla: yes, in progress

#6634 fix(list-view-android): app crashes on ListView item template change
  apps/app/ui-tests-app/list-view/dynamic-templates.ts
  apps/app/ui-tests-app/list-view/dynamic-templates.xml
  apps/app/ui-tests-app/list-view/main-page.ts
  apps/app/ui-tests-app/list-view/main-view-model.ts
  tns-core-modules/ui/list-view/list-view-common.ts
Labels: bug, in progress

#6731 chore: merge release in master
  CHANGELOG.md
Labels: cla: no, in progress

#6766 fix(android): raise resume event on activity.onPostResume()
  tns-core-modules/application/application.android.ts
  tns-core-modules/ui/frame/activity.android.ts
  tns-core-modules/ui/frame/frame.android.ts
  tns-core-modules/ui/frame/frame.d.ts
Labels: cla: yes, in progress

#6765 feat(modals): option to make dialogs cancelable in Android
  tns-core-modules/ui/core/view-base/view-base.d.ts
  tns-core-modules/ui/core/view/view.android.ts
  tns-core-modules/ui/core/view/view.ios.ts
Labels: cla: yes, in progress

#6756 fix(Android): a crash on application restart after livesync changes
  tns-core-modules/ui/frame/frame.android.ts
Labels: cla: yes, in progress

#6775 refactor: enable e2e tests with mixed animation nav
  e2e/nested-frame-navigation/e2e/frame-root.e2e-spec.ts
  e2e/nested-frame-navigation/e2e/frame-tab-root.e2e-spec.ts
  e2e/nested-frame-navigation/e2e/layout-root.e2e-spec.ts
  e2e/nested-frame-navigation/e2e/screen.ts
  e2e/nested-frame-navigation/package.json
Labels: cla: yes, in progress

#6777 feat: OnDiscardedError typings and event
  apps/app/ui-tests-app/app.ts
  tests/app/app/app.ts
  tns-core-modules/application/application-common.ts
  tns-core-modules/application/application.d.ts
  tns-core-modules/module.d.ts
Labels: cla: yes

#6779 tests: update driver default wait time
  e2e/modal-navigation/e2e/android-back-button.e2e-spec.ts
  e2e/modal-navigation/e2e/modal-frame.e2e-spec.ts
  e2e/modal-navigation/e2e/modal-layout.e2e-spec.ts
  e2e/modal-navigation/e2e/modal-page.e2e-spec.ts
  e2e/modal-navigation/e2e/modal-tab.e2e-spec.ts
  e2e/modal-navigation/e2e/screen.ts
Labels: cla: yes, in progress

#6796 fix(tab-view): remove onBackPressed override (#6755)
  tns-core-modules/ui/tab-view/tab-view.android.ts
Labels: cla: yes, in progress

#6786 docs(coding-convention): if-statements examples not respecting the coding convention
  CodingConvention.md
Labels: cla: yes, ♥ community PR

#6802 Merge release in master
  CHANGELOG.md
Labels: cla: no, in progress

#6812 fix-next: avoid circular reference
  tns-core-modules/application/application-common.ts
  tns-core-modules/application/application.android.ts
  tns-core-modules/application/application.ios.ts
Labels: cla: yes, in progress

#6809 fix(ios): native view frame optimizations in nested scenario
  tns-core-modules/ui/core/view/view.ios.ts
Labels: cla: yes, in progress

#6824 test: circular deps
  tests/circular-check.js
  tests/package.json
Labels: cla: yes, in progress

#6819 feat: add rebeccapurple to known CSS colors
  tests/app/xml-declaration/tns.xsd
  tns-core-modules/color/known-colors.d.ts
  tns-core-modules/color/known-colors.ts
  tns-core-modules/css/parser.ts
Labels: cla: yes, in progress

#6805 feat(dialog): add decimal input type for prompt dialog
  apps/app/ui-tests-app/dialogs/dialogs.xml
  apps/app/ui-tests-app/dialogs/main-page-common.css
  apps/app/ui-tests-app/dialogs/main-page.android.css
  apps/app/ui-tests-app/dialogs/main-page.ios.css
  apps/app/ui-tests-app/dialogs/main-page.ts
  apps/app/ui-tests-app/dialogs/main-page.xml
  apps/app/ui-tests-app/dialogs/view-model.ts
  apps/app/ui-tests-app/main-page.ts
  tns-core-modules/ui/dialogs/dialogs-common.ts
  tns-core-modules/ui/dialogs/dialogs.android.ts
  tns-core-modules/ui/dialogs/dialogs.d.ts
  tns-core-modules/ui/dialogs/dialogs.ios.ts
Labels: cla: yes, in progress

#6843 refactor: rename HmrContext to ModuleContext
  tests/app/livesync/livesync-tests.ts
  tns-core-modules/application/application-common.ts
  tns-core-modules/application/application.android.ts
  tns-core-modules/application/application.ios.ts
  tns-core-modules/module.d.ts
Labels: cla: yes, in progress
