Repository NativeScript/NativeScript, pull requests merged in 2019-02, with the labels that each got.

#6830 Remove unnecessary hyperlink
  README.md
Labels: cla: yes, ♥ community PR

#6852 fix(view-android): clear dialog fragment when closing modal view
  tns-core-modules/ui/core/view/view.android.ts
Labels: in progress

#6862 feat(action-bar): flat mode breaks ios safe area
  apps/app/ui-tests-app/action-bar/flat-scrollview.xml
  apps/app/ui-tests-app/action-bar/flat-tab.xml
  apps/app/ui-tests-app/action-bar/main-page.ts
  apps/app/ui-tests-app/nested-frames/full-screen-n-y-flat.xml
  apps/app/ui-tests-app/nested-frames/full-screen-y-n-flat.xml
  apps/app/ui-tests-app/nested-frames/full-screen-y-y-flat.xml
  apps/app/ui-tests-app/nested-frames/main-page.ts
  apps/app/ui-tests-app/nested-frames/mid-screen-n-y-flat.xml
  apps/app/ui-tests-app/nested-frames/mid-screen-y-n-flat.xml
  apps/app/ui-tests-app/nested-frames/mid-screen-y-y-flat.xml
  apps/app/ui-tests-app/nested-frames/nested-page-flat.xml
  apps/app/ui-tests-app/nested-frames/tab-n-y-flat.xml
  apps/app/ui-tests-app/nested-frames/tab-y-n-flat.xml
  apps/app/ui-tests-app/nested-frames/tab-y-y-flat.xml
  tns-core-modules/ui/page/page.ios.ts
Labels: cla: yes, e2e test needed, in progress

#6864 fix(ios): textview content clipped on every other newline
  tns-core-modules/ui/text-view/text-view.ios.ts
Labels: cla: yes, in progress

#6858 Remove incomplete declaration of Array#filter.
  tns-core-modules/tns-core-modules.d.ts
Labels: cla: yes, in progress

#6784 refactor(stack-layout-ios): add warning when measuring unsized scrollable child
  tns-core-modules/ui/layouts/stack-layout/stack-layout.ios.ts
Labels: in progress

#6817 fix(ios-frame): tearDownUI and reset UINavigationController
  tns-core-modules/ui/frame/frame.ios.ts
Labels: bug, in progress

#6815 Prevent app crash for css text-transform
  tns-core-modules/ui/text-base/text-base.android.ts
  tns-core-modules/ui/text-base/text-base.ios.ts
Labels: cla: yes, in progress

#6873 feat: Provide API to release the native object wrapped by a JS one
  tests/app/TKUnit.ts
  tests/app/testRunner.ts
  tests/app/utils/utils-tests.ts
  tns-core-modules/utils/utils.android.ts
  tns-core-modules/utils/utils.d.ts
  tns-core-modules/utils/utils.ios.ts
  tns-platform-declarations/android/android-declarations.d.ts
  tns-platform-declarations/ios/ios.d.ts
  tns-platform-declarations/ios/runtime.d.ts
  tns-platform-declarations/typings-gen.sh
Labels: cla: yes, in progress

#6877 chore: bump package versions to 5.3.0
  tns-core-modules/package.json
  tns-platform-declarations/package.json
Labels: in progress

#6879 fix: app launch with app.css hot module update
  tns-core-modules/application/application.ios.ts
Labels: cla: yes, in progress

#6878 release: cut the 5.2.0 release
  CHANGELOG.md
  tns-core-modules/package.json
Labels: cla: yes, in progress

#6887 Merge release in master
  CHANGELOG.md
  tns-core-modules/application/application.ios.ts
Labels: cla: yes, in progress

#6889 fix(css): widget properties in css didn't work
  tests/app/ui/search-bar/search-bar-tests-native.android.ts
  tests/app/ui/search-bar/search-bar-tests-native.d.ts
  tests/app/ui/search-bar/search-bar-tests-native.ios.ts
  tests/app/ui/search-bar/search-bar-tests.ts
  tns-core-modules/ui/styling/style-scope.ts
Labels: cla: yes, docs needed, in progress, patch

#6892 fix(ios-frame): tearDownUI and reset UINavigationController
  tests/app/navigation/navigation-tests.ts
  tns-core-modules/ui/frame/frame.ios.ts
Labels: in progress, patch

#6857 feat(HMR): apply changes in page styles at runtime
  tests/app/ui/styling/style-tests.ts
  tns-core-modules/application/application-common.ts
  tns-core-modules/application/application.ios.ts
  tns-core-modules/module.d.ts
  tns-core-modules/ui/core/view/view-common.ts
  tns-core-modules/ui/core/view/view.d.ts
  tns-core-modules/ui/frame/frame-common.ts
  tns-core-modules/ui/frame/frame.android.ts
  tns-core-modules/ui/styling/style-scope.d.ts
  tns-core-modules/ui/styling/style-scope.ts
Labels: cla: yes, in progress

#6903 fix(ios-textview): text alignment reset to default on blur
  tns-core-modules/ui/text-base/text-base.ios.ts
Labels: cla: yes, in progress, patch

#6902 fix(ios): searcbar hint color before hint property
  tests/app/ui/search-bar/search-bar-tests-native.ios.ts
  tests/app/ui/search-bar/search-bar-tests.ts
  tns-core-modules/ui/search-bar/search-bar.ios.ts
Labels: cla: yes, in progress, patch

#6904 fix(debugger): Enable iOS inspector modules on creation
  tns-core-modules/debugger/webinspector-css.ios.ts
  tns-core-modules/debugger/webinspector-dom.ios.ts
  tns-core-modules/debugger/webinspector-network.ios.ts
Labels: bug, cla: yes, in progress

#6925 release: cut the 5.2.1 release
  CHANGELOG.md
  tns-core-modules/package.json
  tns-platform-declarations/package.json
Labels: cla: yes, in progress

#6926 Merge release master 5.2.1
  CHANGELOG.md
  tests/app/navigation/navigation-tests.ts
  tests/app/ui/search-bar/search-bar-tests-native.android.ts
  tests/app/ui/search-bar/search-bar-tests-native.d.ts
  tests/app/ui/search-bar/search-bar-tests-native.ios.ts
  tests/app/ui/search-bar/search-bar-tests.ts
  tns-core-modules/ui/frame/frame.ios.ts
  tns-core-modules/ui/search-bar/search-bar.ios.ts
  tns-core-modules/ui/styling/style-scope.ts
  tns-core-modules/ui/text-base/text-base.ios.ts
Labels: cla: yes, in progress

#6927 fix(docs): Move `NativeScriptError` declaration to a separate file
  tns-core-modules/application/application-common.ts
  tns-core-modules/application/application.d.ts
  tns-core-modules/module.d.ts
  tns-core-modules/nativescript-error.d.ts
  tns-core-modules/ui/core/view/view.d.ts
  tns-core-modules/ui/page/page.d.ts
Labels: cla: yes, docs, in progress

#6949 fix(angular): Re-add references to `tns-core-modules.d.ts`
  tns-core-modules/application/application.d.ts
  tns-core-modules/ui/core/view/view.d.ts
  tns-core-modules/ui/page/page.d.ts
Labels: bug, cla: yes, in progress, regression

#6938 Update CodingConvention.md
  CodingConvention.md
Labels: cla: yes, in progress

#6937 Update WritingUnitTests.md
  WritingUnitTests.md
Labels: cla: yes, in progress

#6930 fix(android-animations): reuse animatorSet to prevent high memory usage
  tns-core-modules/ui/animation/animation.android.ts
  tns-core-modules/ui/animation/animation.d.ts
  tns-core-modules/ui/animation/keyframe-animation.ts
Labels: in progress, patch

#6870 docs: update release diagram
  release-contribution-guide-schema.png
Labels: cla: yes, in progress

#6946 chore: include readme.md in package
  gruntfile.js
Labels: cla: yes, in progress

#6942 fix(android-bottom-tabs): transition type on programmatic selectedIndex change
  tns-core-modules/ui/tab-view/tab-view.android.ts
Labels: cla: yes, e2e test needed, in progress

#6955 fix(android): resource ID #0xffffffec not found on nav
  tns-core-modules/ui/frame/fragment.transitions.android.ts
Labels: cla: yes, in progress, patch

#6950 chore: merge release to master
  tns-core-modules/ui/animation/animation.android.ts
  tns-core-modules/ui/animation/animation.d.ts
  tns-core-modules/ui/animation/keyframe-animation.ts
Labels: cla: yes, in progress

#6952 chore: bump version to 5.2.2
  tns-core-modules/package.json
  tns-platform-declarations/package.json
Labels: cla: yes, in progress

#6954 chore: merge release in master
  gruntfile.js
Labels: cla: yes, in progress

#6958 chore: merge release in master
  tns-core-modules/ui/frame/fragment.transitions.android.ts
Labels: cla: yes, in progress

#6962 Make NodeRequire declaration match the latest webpack-env one.
  tns-core-modules/tns-core-modules.d.ts
Labels: cla: yes, ♥ community PR

#6947 fix(ios-webview): loading of local-file dependency
  tns-core-modules/ui/web-view/web-view.ios.ts
Labels: cla: yes, in progress

#6965 fix(ios): resize of scrollview content breaks layout
  apps/app/ui-tests-app/scroll-view/layout-outside-scroll-view-model.ts
  apps/app/ui-tests-app/scroll-view/layout-outside-scroll.ts
  apps/app/ui-tests-app/scroll-view/layout-outside-scroll.xml
  apps/app/ui-tests-app/scroll-view/main-page.ts
  tns-core-modules/ui/core/view/view.ios.ts
Labels: cla: yes, e2e test needed, in progress, patch

#6970 fix(ios): resize of scrollview content breaks layout (#6965)
  apps/app/ui-tests-app/scroll-view/layout-outside-scroll-view-model.ts
  apps/app/ui-tests-app/scroll-view/layout-outside-scroll.ts
  apps/app/ui-tests-app/scroll-view/layout-outside-scroll.xml
  apps/app/ui-tests-app/scroll-view/main-page.ts
  tns-core-modules/ui/core/view/view.ios.ts
Labels: cla: yes, in progress
