Repository NativeScript/NativeScript, pull requests merged in 2019-09, with the labels that each got.

#7773 docs: cut the 6.1.0 release
  CHANGELOG.md
Labels: cla: yes

#7790 fix(android-list-picker): NoSuchFieldException on api29
  tns-core-modules/ui/list-picker/list-picker.android.ts
Labels: cla: yes, patch

#7787 fix(css-calc): reduce_css_calc_1.default is not a function
  tns-core-modules/ui/core/properties/properties.ts
Labels: cla: yes, ♥ community PR

#7776 chore: hardcode tslib version to 1.10.0
  package.json
  tns-core-modules/package.json
Labels: cla: yes, patch

#7750 docs: update workflow info - tns-core-modules
  DevelopmentWorkflow.md
Labels: cla: yes

#7801 fix(css-calc): reduce_css_calc_1.default is not a function (#7787)
  tns-core-modules/ui/core/properties/properties.ts
Labels: cla: yes, patch, ♥ community PR

#7808 release: cut the 6.1.1 release
  CHANGELOG.md
  tns-core-modules/package.json
  tns-platform-declarations/package.json
Labels: cla: yes

#7730 feat(css): Add HSL/HSLA support
  tns-core-modules/color/color-common.ts
  tns-core-modules/css/parser.ts
  unit-tests/css/parser.ts
Labels: cla: yes, css, feature

#7819 chore: update dev workflow
  DevelopmentWorkflow.md
Labels: cla: yes

#7813 fix(android/application-settings): possible uninitialized sharedPreferences variable usage
  tns-core-modules/application-settings/application-settings.android.ts
Labels: cla: yes

#7832 fix: expose orientation to application module
  tests/app/application/application-tests-common.ts
  tns-core-modules/application/application.android.ts
  tns-core-modules/application/application.d.ts
  tns-core-modules/application/application.ios.ts
Labels: cla: yes, patch

#7858 chore: add highlight color to api reference
  tns-core-modules/ui/tab-navigation-base/tab-strip/tab-strip.d.ts
  tns-core-modules/ui/tab-navigation-base/tab-strip/tab-strip.ts
Labels: cla: yes, patch

#7842 fix(android/action-bar): process Icon Fonts in NavigationButton the same way as in ActionItem
  e2e/ui-tests-app/app/action-bar/font-icons-page.xml
  tns-core-modules/ui/action-bar/action-bar.android.ts
Labels: cla: yes, docs needed

#7875 Escape amp in tests release
  tests/app/ui/test-pages/bindingExpressions_logicalComparisonOperators_testPage.xml
Labels: cla: yes
