Repository NativeScript/NativeScript, pull requests merged in 2019-08, with the labels that each got.

#7621 chore: merge release in master 6.0.4
  CHANGELOG.md
  e2e/ui-tests-app/README.md
  e2e/ui-tests-app/app/action-bar/action-item-position-page.xml
  e2e/ui-tests-app/app/action-bar/action-view-page.xml
  e2e/ui-tests-app/app/action-bar/all-page.xml
  e2e/ui-tests-app/app/action-bar/background-css-page.xml
  e2e/ui-tests-app/app/action-bar/background-page.xml
  e2e/ui-tests-app/app/action-bar/clean-page.xml
  e2e/ui-tests-app/app/action-bar/color-page.xml
  e2e/ui-tests-app/app/action-bar/flat-layout-page.xml
  e2e/ui-tests-app/app/action-bar/flat-page.xml
  e2e/ui-tests-app/app/action-bar/flat-scrollview-page.xml
  e2e/ui-tests-app/app/action-bar/flat-tab-opaque-bar-page.xml
  e2e/ui-tests-app/app/action-bar/flat-tab-page.xml
  e2e/ui-tests-app/app/action-bar/font-icons-page.xml
  e2e/ui-tests-app/app/action-bar/icons-page.xml
  e2e/ui-tests-app/app/action-bar/local-icons-page.xml
  e2e/ui-tests-app/app/action-bar/modal-page-hidden-action-bar-page.xml
  e2e/ui-tests-app/app/action-bar/modal-test-hidden-action-bar-page.xml
  e2e/ui-tests-app/app/action-bar/modal-test-with-action-bar-page.xml
  e2e/ui-tests-app/app/action-bar/system-icons-page.xml
  e2e/ui-tests-app/app/action-bar/transparent-bg-css-page.xml
  e2e/ui-tests-app/e2e/helpers/image-helper.ts
  e2e/ui-tests-app/e2e/helpers/navigation-helper.ts
  e2e/ui-tests-app/e2e/suites/action-bar/action-bar-base-page.ts
  e2e/ui-tests-app/e2e/suites/action-bar/action-bar-tests.e2e-spec.ts
  e2e/ui-tests-app/e2e/suites/button/background/button-background-page.ts
  e2e/ui-tests-app/e2e/suites/button/background/button-background.e2e-spec.ts
  e2e/ui-tests-app/e2e/suites/tab-navigation/bottom-navigation/bottom-navigation-css-properties.e2e-spec.ts
  e2e/ui-tests-app/e2e/suites/tab-navigation/tab-navigation-base-page.ts
  e2e/ui-tests-app/e2e/suites/tab-navigation/tab-view/issues-from-git.ts
  e2e/ui-tests-app/e2e/suites/tab-navigation/tabs/tabs-tests.e2e-spec.ts
  gruntfile.js
  tns-core-modules-widgets/.gitignore
  tns-core-modules-widgets/android/widgets/src/main/java/org/nativescript/widgets/TabStrip.java
  tns-core-modules-widgets/build.ios.sh
  tns-core-modules-widgets/ios/TNSWidgets/Podfile
  tns-core-modules-widgets/ios/TNSWidgets/Podfile.lock
  tns-core-modules-widgets/ios/TNSWidgets/TNSWidgets.xcodeproj/project.pbxproj
  tns-core-modules-widgets/ios/TNSWidgets/TNSWidgets.xcworkspace/contents.xcworkspacedata
  tns-core-modules-widgets/ios/TNSWidgets/TNSWidgets.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  tns-core-modules-widgets/ios/build.sh
  tns-core-modules/package.json
  tns-core-modules/platforms/ios/Podfile
Labels: cla: yes

#7617 fix(tabs-android): tabStripItem color not applied
  tns-core-modules-widgets/android/widgets/src/main/java/org/nativescript/widgets/TabStrip.java
  tns-core-modules-widgets/android/widgets/src/main/java/org/nativescript/widgets/TabsBar.java
  tns-core-modules/ui/tabs/tabs.android.ts
  tns-platform-declarations/android/org.nativescript.widgets.d.ts
Labels: cla: yes, patch

#7431 fix: added missing openFile method in ios utils
  tns-core-modules/utils/utils.ios.ts
Labels: cla: yes

#7624 fix(bottom-navigation): created dynamically does not show tabstrip
  tns-core-modules/ui/bottom-navigation/bottom-navigation.ios.ts
  tns-core-modules/ui/tab-navigation-base/tab-navigation-base/tab-navigation-base.ts
Labels: cla: yes, patch

#7626 fix: prevent plugin podfile platform version clash
  tns-core-modules/platforms/ios/Podfile
Labels: cla: yes, patch

#7628 release: cut the 6.0.5 release
  CHANGELOG.md
  tns-core-modules/package.json
  tns-platform-declarations/package.json
Labels: cla: yes, patch

#7505 feat: smaller worker chunks
  tns-core-modules/application/application-common.ts
  tns-core-modules/globals/core/globals-core.ts
  tns-core-modules/globals/core/package.json
  tns-core-modules/globals/decorators.ts
  tns-core-modules/globals/globals.ts
  tns-core-modules/globals/polyfills/dialogs/dialogs.ts
  tns-core-modules/globals/polyfills/dialogs/package.json
  tns-core-modules/globals/polyfills/fetch/fetch.ts
  tns-core-modules/globals/polyfills/fetch/package.json
  tns-core-modules/globals/polyfills/polyfill-helpers/package.json
  tns-core-modules/globals/polyfills/polyfill-helpers/polyfill-helpers.ts
  tns-core-modules/globals/polyfills/timers/package.json
  tns-core-modules/globals/polyfills/timers/timers.ts
  tns-core-modules/globals/polyfills/xhr/package.json
  tns-core-modules/globals/polyfills/xhr/xhr.ts
  tns-core-modules/module.d.ts
  tns-core-modules/ui/frame/activity.android.ts
  tns-core-modules/xml/xml.js
  tns-core-modules/xml/xml.ts
Labels: cla: yes

#7569 fix(timer): setTimeout/setInterval support for boolean period
  tests/app/timer/timer-tests.ts
  tns-core-modules/timer/timer.android.ts
  tns-core-modules/timer/timer.ios.ts
Labels: bug, cla: yes

#7641 feat(GridLayout): Add synonym property column for col in GridLayout
  e2e/ui-tests-app/app/layouts/grid-7295-page.ts
  e2e/ui-tests-app/app/layouts/grid-7295-page.xml
  e2e/ui-tests-app/app/layouts/main-page.ts
  tests/app/ui/layouts/grid-layout-tests.ts
  tns-core-modules/ui/core/view-base/view-base.d.ts
  tns-core-modules/ui/core/view-base/view-base.ts
  tns-core-modules/ui/layouts/grid-layout/grid-layout-common.ts
Labels: cla: yes, docs needed

#7631 refactor: Enable missing css check and test
  e2e/file-qualifiers/app/App_Resources/Android/src/main/res/values/strings.xml
  e2e/file-qualifiers/app/app.css
  e2e/file-qualifiers/app/app.land.css
  e2e/file-qualifiers/app/main/main-page.land.xml
  e2e/file-qualifiers/app/main/main-page.xml
  e2e/file-qualifiers/app/other/other-page.land.xml
  e2e/file-qualifiers/app/other/other-page.xml
  e2e/file-qualifiers/nsconfig.json
  e2e/file-qualifiers/package.json
  e2e/file-qualifiers/webpack.config.js
  tests/app/ui/label/label-tests.ts
  tns-core-modules/module-name-resolver/module-name-resolver.ts
  tns-core-modules/module-name-resolver/non-bundle-workflow-compat.ts
  tns-core-modules/trace/trace.d.ts
  tns-core-modules/trace/trace.ts
  tns-core-modules/ui/builder/module-name-sanitizer.ts
  tns-core-modules/ui/styling/style-scope.ts
Labels: cla: yes

#7651 chore: fix ui tests typo
  e2e/ui-tests-app/e2e/page-object-base-model.ts
  e2e/ui-tests-app/e2e/suites/tab-navigation/bottom-navigation/bottom-navigation-css-properties.e2e-spec.ts
  e2e/ui-tests-app/e2e/suites/tab-navigation/bottom-navigation/bottom-navigation.e2e-spec.ts
  e2e/ui-tests-app/e2e/suites/tab-navigation/tab-navigation-base-page.ts
  e2e/ui-tests-app/e2e/suites/tab-navigation/tab-view/tab-view-base-page.ts
Labels: cla: yes

#7649 fix: handle empty folders in non-bundle-compat
  tns-core-modules/module-name-resolver/non-bundle-workflow-compat.ts
Labels: cla: yes

#7653 chore: merge release in master
  CHANGELOG.md
  e2e/ui-tests-app/e2e/page-object-base-model.ts
  e2e/ui-tests-app/e2e/suites/tab-navigation/bottom-navigation/bottom-navigation-css-properties.e2e-spec.ts
  e2e/ui-tests-app/e2e/suites/tab-navigation/bottom-navigation/bottom-navigation.e2e-spec.ts
  e2e/ui-tests-app/e2e/suites/tab-navigation/tab-navigation-base-page.ts
  e2e/ui-tests-app/e2e/suites/tab-navigation/tab-view/tab-view-base-page.ts
  tns-core-modules-widgets/android/widgets/src/main/java/org/nativescript/widgets/TabStrip.java
  tns-core-modules-widgets/android/widgets/src/main/java/org/nativescript/widgets/TabsBar.java
  tns-core-modules/platforms/ios/Podfile
  tns-core-modules/ui/bottom-navigation/bottom-navigation.ios.ts
  tns-core-modules/ui/tab-navigation-base/tab-navigation-base/tab-navigation-base.ts
  tns-core-modules/ui/tabs/tabs.android.ts
  tns-platform-declarations/android/org.nativescript.widgets.d.ts
Labels: cla: yes

#7660 chore: make cuteness compatible with 6.0 cli
  e2e/cuteness.io/package.json
Labels: cla: yes

#7661 chore: bump versions 6.0.6
  tns-core-modules-widgets/package.json
  tns-core-modules/package.json
  tns-platform-declarations/package.json
Labels: cla: yes

#7662 release: cut the 6.0.6 release
  CHANGELOG.md
  tns-core-modules/package.json
Labels: cla: yes

#7478 Added fix for dialog not showing in ios modal
  tns-core-modules/ui/dialogs/dialogs.ios.ts
Labels: cla: yes

#7652 feat: apply styles when adding them to the application scope
  e2e/ui-tests-app/app/app.css
  e2e/ui-tests-app/app/button/main-page.ts
  e2e/ui-tests-app/app/button/styles-page.ts
  e2e/ui-tests-app/app/css/main-page.ts
  e2e/ui-tests-app/app/css/styles-page.css
  e2e/ui-tests-app/app/css/styles-page.ts
  e2e/ui-tests-app/app/css/styles-page.xml
  e2e/ui-tests-app/e2e/suites/css/styles/styles-page.ts
  e2e/ui-tests-app/e2e/suites/css/styles/styles.e2e-spec.ts
  tns-core-modules/application/application-common.ts
  tns-core-modules/application/application.android.ts
  tns-core-modules/application/application.d.ts
  tns-core-modules/application/application.ios.ts
Labels: cla: yes

#7675 tests: fix tab-navigation-tests for android api level < 23
  e2e/ui-tests-app/.gitignore
  e2e/ui-tests-app/e2e/suites/tab-navigation/bottom-navigation/bottom-navigation-base-page.ts
  e2e/ui-tests-app/e2e/suites/tab-navigation/bottom-navigation/bottom-navigation.e2e-spec.ts
  e2e/ui-tests-app/e2e/suites/tab-navigation/tab-navigation-base-page.ts
  e2e/ui-tests-app/e2e/suites/tab-navigation/tab-view/tab-view-common-tests.e2e-spec.ts
  e2e/ui-tests-app/e2e/suites/tab-navigation/tab-view/tab-view-css-properties.e2e-spec.ts
  e2e/ui-tests-app/e2e/suites/tab-navigation/tabs/tabs-tests.e2e-spec.ts
  e2e/ui-tests-app/e2e/suites/tab-navigation/tabs/tabs-view-base-page.ts
Labels: cla: yes

#7678 chore: merger release in master
  CHANGELOG.md
  e2e/cuteness.io/package.json
  e2e/ui-tests-app/.gitignore
  e2e/ui-tests-app/e2e/suites/tab-navigation/bottom-navigation/bottom-navigation-base-page.ts
  e2e/ui-tests-app/e2e/suites/tab-navigation/bottom-navigation/bottom-navigation.e2e-spec.ts
  e2e/ui-tests-app/e2e/suites/tab-navigation/tab-navigation-base-page.ts
  e2e/ui-tests-app/e2e/suites/tab-navigation/tab-view/tab-view-common-tests.e2e-spec.ts
  e2e/ui-tests-app/e2e/suites/tab-navigation/tab-view/tab-view-css-properties.e2e-spec.ts
  e2e/ui-tests-app/e2e/suites/tab-navigation/tabs/tabs-tests.e2e-spec.ts
  e2e/ui-tests-app/e2e/suites/tab-navigation/tabs/tabs-view-base-page.ts
Labels: cla: yes

#7602 feat: expose application orientation
  tests/app/application/application-tests-common.ts
  tests/app/application/application-tests.android.ts
  tests/app/application/application-tests.d.ts
  tests/app/application/application-tests.ios.ts
  tests/app/application/application.md
  tests/app/platform/platform-tests.ts
  tns-core-modules/application/application-common.ts
  tns-core-modules/application/application.android.ts
  tns-core-modules/application/application.d.ts
  tns-core-modules/application/application.ios.ts
  tns-core-modules/platform/platform.android.ts
  tns-core-modules/platform/platform.d.ts
  tns-core-modules/platform/platform.ios.ts
  tns-core-modules/utils/utils.d.ts
  tns-core-modules/utils/utils.ios.ts
Labels: cla: yes

#7580 feat(tab): add support for no tabstrip
  e2e/ui-tests-app/app/bottom-navigation/custom-tabstrip-page.css
  e2e/ui-tests-app/app/bottom-navigation/custom-tabstrip-page.ts
  e2e/ui-tests-app/app/bottom-navigation/custom-tabstrip-page.xml
  e2e/ui-tests-app/app/bottom-navigation/main-page.ts
  e2e/ui-tests-app/app/tabs/custom-tabstrip-page.css
  e2e/ui-tests-app/app/tabs/custom-tabstrip-page.ts
  e2e/ui-tests-app/app/tabs/custom-tabstrip-page.xml
  e2e/ui-tests-app/app/tabs/main-page.ts
  e2e/ui-tests-app/e2e/suites/tab-navigation/bottom-navigation/bottom-navigation.e2e-spec.ts
  e2e/ui-tests-app/e2e/suites/tab-navigation/tab-navigation-base-page.ts
  e2e/ui-tests-app/e2e/suites/tab-navigation/tabs/tabs-tests.e2e-spec.ts
  tests/app/ui/bottom-navigation/bottom-navigation-tests.ts
  tns-core-modules/ui/bottom-navigation/bottom-navigation.android.ts
  tns-core-modules/ui/bottom-navigation/bottom-navigation.ios.ts
  tns-core-modules/ui/tabs/tabs.android.ts
  tns-core-modules/ui/tabs/tabs.ios.ts
Labels: cla: yes

#7629 feat(tab-content-view): change tabContentItem to View
  e2e/ui-tests-app/app/bottom-navigation/bottom-navigation-view-model.ts
  e2e/ui-tests-app/app/tabs/tabs-binding-view-model.ts
  tests/app/ui/bottom-navigation/bottom-navigation-navigation-tests.ts
  tests/app/ui/bottom-navigation/bottom-navigation-root-tests.ts
  tests/app/ui/bottom-navigation/bottom-navigation-tests.ts
  tests/app/ui/tabs/tabs-navigation-tests.ts
  tests/app/ui/tabs/tabs-root-tests.ts
  tests/app/ui/tabs/tabs-tests.ts
  tns-core-modules/ui/bottom-navigation/bottom-navigation.android.ts
  tns-core-modules/ui/bottom-navigation/bottom-navigation.ios.ts
  tns-core-modules/ui/tab-navigation-base/tab-content-item/tab-content-item-common.ts
  tns-core-modules/ui/tab-navigation-base/tab-content-item/tab-content-item.android.ts
  tns-core-modules/ui/tab-navigation-base/tab-content-item/tab-content-item.d.ts
  tns-core-modules/ui/tab-navigation-base/tab-navigation-base/tab-navigation-base.ts
  tns-core-modules/ui/tabs/tabs.android.ts
  tns-core-modules/ui/tabs/tabs.ios.ts
Labels: cla: yes

#7676 docs: update changelog
  CHANGELOG.md
Labels: cla: yes

#7679 fix(hmr): close modal views during livesync #7668
  tests/app/livesync/livesync-modal-view-page.css
  tests/app/livesync/livesync-modal-view-page.scss
  tests/app/livesync/livesync-modal-view-page.ts
  tests/app/livesync/livesync-modal-view-page.xml
  tests/app/livesync/livesync-tests.ts
  tns-core-modules/ui/core/view/view-common.ts
  tns-core-modules/ui/core/view/view.d.ts
Labels: cla: yes, patch

#7672 feat: flexbile font icon usage in tab navigation
  e2e/ui-tests-app/app/bottom-navigation/color-page.css
  e2e/ui-tests-app/app/bottom-navigation/color-page.xml
  e2e/ui-tests-app/app/bottom-navigation/font-icons-page.css
  e2e/ui-tests-app/app/bottom-navigation/font-icons-page.xml
  e2e/ui-tests-app/app/bottom-navigation/font-page.css
  e2e/ui-tests-app/app/bottom-navigation/font-page.xml
  e2e/ui-tests-app/app/bottom-navigation/icon-change-page.ts
  e2e/ui-tests-app/app/bottom-navigation/icon-change-page.xml
  e2e/ui-tests-app/app/bottom-navigation/text-transform-page.css
  e2e/ui-tests-app/app/bottom-navigation/text-transform-page.xml
  e2e/ui-tests-app/app/tabs/color-page.css
  e2e/ui-tests-app/app/tabs/color-page.xml
  e2e/ui-tests-app/app/tabs/font-icons-page.css
  e2e/ui-tests-app/app/tabs/font-icons-page.xml
  e2e/ui-tests-app/app/tabs/font-page.css
  e2e/ui-tests-app/app/tabs/font-page.xml
  e2e/ui-tests-app/app/tabs/icon-change-page.ts
  e2e/ui-tests-app/app/tabs/icon-change-page.xml
  e2e/ui-tests-app/app/tabs/text-transform-page.css
  e2e/ui-tests-app/app/tabs/text-transform-page.xml
  tns-core-modules-widgets/android/widgets/src/main/java/org/nativescript/widgets/BottomNavigationBar.java
  tns-core-modules-widgets/android/widgets/src/main/java/org/nativescript/widgets/TabItemSpec.java
  tns-core-modules-widgets/android/widgets/src/main/java/org/nativescript/widgets/TabStrip.java
  tns-core-modules-widgets/android/widgets/src/main/java/org/nativescript/widgets/TabsBar.java
  tns-core-modules/ui/bottom-navigation/bottom-navigation.android.ts
  tns-core-modules/ui/bottom-navigation/bottom-navigation.ios.ts
  tns-core-modules/ui/tab-navigation-base/tab-content-item/tab-content-item.android.ts
  tns-core-modules/ui/tab-navigation-base/tab-navigation-base/tab-navigation-base.d.ts
  tns-core-modules/ui/tab-navigation-base/tab-navigation-base/tab-navigation-base.ts
  tns-core-modules/ui/tab-navigation-base/tab-strip-item/tab-strip-item.ts
  tns-core-modules/ui/tab-navigation-base/tab-strip/tab-strip.ts
  tns-core-modules/ui/tabs/tabs.android.ts
  tns-core-modules/ui/tabs/tabs.ios.ts
  tns-platform-declarations/android/org.nativescript.widgets.d.ts
Labels: cla: yes

#7681 fix(ios): handle tabs extended layout for ios 10
  tns-core-modules/ui/tabs/tabs.ios.ts
Labels: cla: yes

#7677 chore(e2e): update config files
  .gitignore
  .travis.yml
  e2e/animation/.gitignore
  e2e/animation/README.md
  e2e/animation/nsconfig.json
  e2e/animation/package.json
  e2e/animation/tsconfig.json
  e2e/animation/webpack.config.js
  e2e/cuteness.io/.gitignore
  e2e/cuteness.io/LICENSE
  e2e/cuteness.io/nsconfig.json
  e2e/cuteness.io/package.json
  e2e/cuteness.io/tsconfig.json
  e2e/cuteness.io/webpack.config.js
  e2e/file-qualifiers/.gitignore
  e2e/file-qualifiers/README.md
  e2e/file-qualifiers/nsconfig.json
  e2e/file-qualifiers/package.json
  e2e/file-qualifiers/tsconfig.json
  e2e/file-qualifiers/webpack.config.js
  e2e/modal-navigation/.gitignore
  e2e/modal-navigation/README.md
  e2e/modal-navigation/app/home/home-page.ts
  e2e/modal-navigation/nsconfig.json
  e2e/modal-navigation/package.json
  e2e/modal-navigation/references.d.ts
  e2e/modal-navigation/tsconfig.json
  e2e/nested-frame-navigation/.gitignore
  e2e/nested-frame-navigation/README.md
  e2e/nested-frame-navigation/nsconfig.json
  e2e/nested-frame-navigation/package.json
  e2e/nested-frame-navigation/tsconfig.json
  e2e/ui-tests-app/.gitignore
  e2e/ui-tests-app/nsconfig.json
  e2e/ui-tests-app/package.json
  e2e/ui-tests-app/references.d.ts
  e2e/ui-tests-app/tsconfig.json
  e2e/ui-tests-app/webpack.config.js
  package.json
  tests/.gitignore
  tests/nsconfig.json
  tests/reference.d.ts
  tests/tsconfig.json
  tests/webpack.config.js
Labels: cla: yes

#7606 feat: add CSS classes to app/modal root views to target platform/device/orientation/type
  tests/app/test-runner.ts
  tests/app/ui/page/page-tests-common.ts
  tests/app/ui/styling/root-views-css-classes-tests.ts
  tns-core-modules/application/application-common.ts
  tns-core-modules/application/application.android.ts
  tns-core-modules/application/application.d.ts
  tns-core-modules/application/application.ios.ts
  tns-core-modules/ui/core/view/view-common.ts
  tns-core-modules/ui/core/view/view.android.ts
  tns-core-modules/ui/frame/frame.android.ts
Labels: cla: yes, docs needed

#7697 chore: fix-travis
  .travis.yml
Labels: cla: yes

#7696 tests: fix-nested-frame-tests
  e2e/nested-frame-navigation/e2e/bottom-navigation-root.e2e-spec.ts
  e2e/nested-frame-navigation/e2e/frame-bottom-navigation-root.e2e-spec.ts
  e2e/nested-frame-navigation/e2e/frame-root.e2e-spec.ts
  e2e/nested-frame-navigation/e2e/frame-tab-root.e2e-spec.ts
  e2e/nested-frame-navigation/e2e/frame-tabs-root.e2e-spec.ts
  e2e/nested-frame-navigation/e2e/issues.e2e.spec.ts
  e2e/nested-frame-navigation/e2e/layout-root.e2e-spec.ts
  e2e/nested-frame-navigation/e2e/screen.ts
  e2e/nested-frame-navigation/e2e/tab-navigation-screen.ts
  e2e/nested-frame-navigation/e2e/tab-root.e2e-spec.ts
  e2e/nested-frame-navigation/e2e/tabs-root.e2e-spec.ts
  e2e/nested-frame-navigation/e2e/tabview-navigation-screen.ts
  e2e/nested-frame-navigation/package.json
Labels: cla: yes

#7553 feat: implement css-variables and css-calc
  package.json
  tests/app/ui/styling/style-tests.ts
  tns-core-modules/package.json
  tns-core-modules/ui/core/properties/properties.d.ts
  tns-core-modules/ui/core/properties/properties.ts
  tns-core-modules/ui/styling/style-scope.ts
  tns-core-modules/ui/styling/style/style.d.ts
  tns-core-modules/ui/styling/style/style.ts
Labels: cla: yes, docs needed, ♥ community PR

#7698 chore: merge release in master
  e2e/nested-frame-navigation/e2e/bottom-navigation-root.e2e-spec.ts
  e2e/nested-frame-navigation/e2e/frame-bottom-navigation-root.e2e-spec.ts
  e2e/nested-frame-navigation/e2e/frame-root.e2e-spec.ts
  e2e/nested-frame-navigation/e2e/frame-tab-root.e2e-spec.ts
  e2e/nested-frame-navigation/e2e/frame-tabs-root.e2e-spec.ts
  e2e/nested-frame-navigation/e2e/issues.e2e.spec.ts
  e2e/nested-frame-navigation/e2e/layout-root.e2e-spec.ts
  e2e/nested-frame-navigation/e2e/screen.ts
  e2e/nested-frame-navigation/e2e/tab-navigation-screen.ts
  e2e/nested-frame-navigation/e2e/tab-root.e2e-spec.ts
  e2e/nested-frame-navigation/e2e/tabs-root.e2e-spec.ts
  e2e/nested-frame-navigation/e2e/tabview-navigation-screen.ts
  e2e/nested-frame-navigation/package.json
  tests/app/livesync/livesync-modal-view-page.css
  tests/app/livesync/livesync-modal-view-page.scss
  tests/app/livesync/livesync-modal-view-page.ts
  tests/app/livesync/livesync-modal-view-page.xml
  tests/app/livesync/livesync-tests.ts
  tns-core-modules/ui/core/view/view-common.ts
  tns-core-modules/ui/core/view/view.d.ts
Labels: cla: yes

#7695 chore(grunt): setup script is no more
  gruntfile.js
Labels: cla: yes

#7693 feat(ios-tabs): emit tabStripItem tap event
  tns-core-modules/ui/tabs/tabs.ios.ts
Labels: cla: yes, e2e test needed

#7655 fix: dots can now be used in module names
  .gitignore
  tests/app/ui/builder/builder-tests.ts
  tns-core-modules/ui/builder/module-name-sanitizer.ts
Labels: cla: yes

#7686 fix(view): respect animated option for showModal()
  tns-core-modules/ui/core/view/view.android.ts
Labels: cla: yes, ♥ community PR

#7706 fix-next: Add accidentally removed System.import
  tests/app/globals/globals-tests.ts
  tests/app/test-runner.ts
  tns-core-modules/globals/core/globals-core.ts
Labels: cla: yes

#7691 feat: introduce fixed font icons to tab navigation
  tns-core-modules/image-source/image-source.android.ts
  tns-core-modules/ui/bottom-navigation/bottom-navigation.android.ts
  tns-core-modules/ui/bottom-navigation/bottom-navigation.ios.ts
  tns-core-modules/ui/tab-navigation-base/tab-navigation-base/tab-navigation-base.d.ts
  tns-core-modules/ui/tab-navigation-base/tab-navigation-base/tab-navigation-base.ts
  tns-core-modules/ui/tab-navigation-base/tab-strip-item/tab-strip-item.ts
  tns-core-modules/ui/tab-navigation-base/tab-strip/tab-strip.d.ts
  tns-core-modules/ui/tab-navigation-base/tab-strip/tab-strip.ts
  tns-core-modules/ui/tabs/tabs.android.ts
  tns-core-modules/ui/tabs/tabs.ios.ts
Labels: cla: yes, docs needed

#7715 chore: bump widgets version to 6.0.7
  tns-core-modules-widgets/package.json
Labels: cla: yes

#7714 docs: cut the 6.0.7 release
  CHANGELOG.md
  tns-core-modules/package.json
  tns-platform-declarations/package.json
Labels: cla: yes

#7719 chore: merge release in master
  CHANGELOG.md
Labels: cla: yes

#7711 feat(TabStrip): add itemTap event
  e2e/ui-tests-app/app/app-root.xml
  e2e/ui-tests-app/app/app.ts
  e2e/ui-tests-app/app/bottom-navigation/events-page.ts
  e2e/ui-tests-app/app/bottom-navigation/events-page.xml
  e2e/ui-tests-app/app/bottom-navigation/first-page.ts
  e2e/ui-tests-app/app/bottom-navigation/first-page.xml
  e2e/ui-tests-app/app/bottom-navigation/main-page.ts
  e2e/ui-tests-app/app/bottom-navigation/reselect-page.ts
  e2e/ui-tests-app/app/bottom-navigation/reselect-page.xml
  e2e/ui-tests-app/app/bottom-navigation/second-page.ts
  e2e/ui-tests-app/app/bottom-navigation/second-page.xml
  e2e/ui-tests-app/app/tabs/default-page.xml
  e2e/ui-tests-app/app/tabs/events-page.ts
  e2e/ui-tests-app/app/tabs/events-page.xml
  e2e/ui-tests-app/app/tabs/first-page.ts
  e2e/ui-tests-app/app/tabs/first-page.xml
  e2e/ui-tests-app/app/tabs/main-page.ts
  e2e/ui-tests-app/app/tabs/reselect-page.ts
  e2e/ui-tests-app/app/tabs/reselect-page.xml
  e2e/ui-tests-app/app/tabs/second-page.ts
  e2e/ui-tests-app/app/tabs/second-page.xml
  tests/app/pages/navigation/pageA-new-activity.ts
  tests/app/pages/navigation/pageA.ts
  tests/app/pages/navigation/pageB-new-activity.ts
  tests/app/pages/navigation/pageB.ts
  tests/app/pages/navigation/pageC-new-activity.ts
  tests/app/pages/navigation/pageC.ts
  tns-core-modules/ui/bottom-navigation/bottom-navigation.android.ts
  tns-core-modules/ui/bottom-navigation/bottom-navigation.ios.ts
  tns-core-modules/ui/tab-navigation-base/tab-strip/tab-strip.d.ts
  tns-core-modules/ui/tab-navigation-base/tab-strip/tab-strip.ts
  tns-core-modules/ui/tabs/tabs.android.ts
  tns-core-modules/ui/tabs/tabs.ios.ts
Labels: cla: yes, docs needed

#7689 fix(css): parse css selectors with escape sequences
  tests/app/ui/styling/style-tests.ts
  tns-core-modules/css/parser.ts
Labels: cla: yes, ♥ community PR

#7737 feat(android): fit tab resource icon size based on spec
  tns-core-modules/ui/bottom-navigation/bottom-navigation.android.ts
  tns-core-modules/ui/tabs/tabs.android.ts
Labels: cla: yes, patch

#7726 chore: bump version to 6.2.0
  tns-core-modules-widgets/package.json
  tns-core-modules/package.json
  tns-platform-declarations/package.json
Labels: cla: yes

#7738 feat(ios): add icon rendering mode for bottom navigation
  e2e/ui-tests-app/app/bottom-navigation/binding-page.xml
  e2e/ui-tests-app/app/bottom-navigation/bottom-navigation-page.xml
  e2e/ui-tests-app/app/bottom-navigation/fancy-fonts-page.xml
  e2e/ui-tests-app/app/bottom-navigation/icon-change-page.xml
  tns-core-modules/ui/bottom-navigation/bottom-navigation.ios.ts
  tns-core-modules/ui/tabs/tabs.ios.ts
Labels: cla: yes, patch

#7743 fix(ios-tabs): crash when add tabstrip in loaded event
  tns-core-modules/ui/tabs/tabs.ios.ts
Labels: cla: yes, patch

#7732 fix(css): parse css selectors with escape sequences (#7689)
  tests/app/ui/styling/style-tests.ts
  tns-core-modules/css/parser.ts
Labels: cla: yes, patch

#7755 fix(ios-tabs): handle nesting proxy view container
  tns-core-modules/ui/tabs/tabs.ios.ts
Labels: cla: yes, patch

#7725 fix-next(css): className to preserve root views classes
  tests/app/ui/styling/root-views-css-classes-tests.ts
  tests/app/ui/styling/style-tests.ts
  tns-core-modules/application/application-common.ts
  tns-core-modules/application/application.d.ts
  tns-core-modules/application/application.ios.ts
  tns-core-modules/css/system-classes.d.ts
  tns-core-modules/css/system-classes.ts
  tns-core-modules/ui/core/view-base/view-base.ts
  tns-core-modules/ui/core/view/view-common.ts
  tns-core-modules/ui/frame/frame.android.ts
  tns-core-modules/ui/utils.android.ts
  tns-core-modules/ui/utils.d.ts
  tns-core-modules/ui/utils.ios.ts
Labels: cla: yes, patch

#7759 docs: remove obsolete Waffle.io links from the README
  README.md
Labels: cla: yes
