Repository NativeScript/NativeScript, pull requests merged in 2019-11, with the labels that each got.

#8035 test: ignore None transition scenario for api19
  e2e/nested-frame-navigation/e2e/frame-root/bottom-navigation.e2e-spec.ts
  e2e/nested-frame-navigation/e2e/frame-root/multi-frames.e2e-spec.ts
  e2e/nested-frame-navigation/e2e/frame-root/single-frame.e2e-spec.ts
  e2e/nested-frame-navigation/e2e/frame-root/tab-view.e2e-spec.ts
  e2e/nested-frame-navigation/e2e/frame-root/tabs.e2e-spec.ts
  e2e/nested-frame-navigation/e2e/layout-root/multi-frames.e2e-spec.ts
  e2e/nested-frame-navigation/e2e/layout-root/single-frame.e2e-spec.ts
  e2e/nested-frame-navigation/e2e/screens/shared.ts
  e2e/nested-frame-navigation/e2e/tab-navigation-root/bottom-navigation-root.e2e-spec.ts
  e2e/nested-frame-navigation/e2e/tab-navigation-root/tabs-root.e2e-spec.ts
  e2e/nested-frame-navigation/e2e/tab-view-root/tab-view-root.e2e-spec.ts
Labels: cla: yes

#8034 feat(application): add system appearance changed event to typings
  nativescript-core/application/application.d.ts
  nativescript-core/ui/enums/enums.d.ts
Labels: cla: yes, patch

#8063 fix(gradient): import LinearGradient with alias
  nativescript-core/ui/styling/gradient.d.ts
Labels: cla: yes, patch

#8066 chore: merge 6.2.0 release in master
  CHANGELOG.md
  CONTRIBUTING.md
  build/generate-tns-compat.ts
  e2e/modal-navigation/.vscode/launch.json
  e2e/modal-navigation/e2e/screen.ts
  e2e/nested-frame-navigation/.vscode/launch.json
  e2e/nested-frame-navigation/app/package.json
  e2e/nested-frame-navigation/e2e/config.ts
  e2e/nested-frame-navigation/e2e/frame-root/bottom-navigation.e2e-spec.ts
  e2e/nested-frame-navigation/e2e/frame-root/multi-frames.e2e-spec.ts
  e2e/nested-frame-navigation/e2e/frame-root/single-frame.e2e-spec.ts
  e2e/nested-frame-navigation/e2e/frame-root/tab-view.e2e-spec.ts
  e2e/nested-frame-navigation/e2e/frame-root/tabs.e2e-spec.ts
  e2e/nested-frame-navigation/e2e/frame-tab-root.e2e-spec.ts
  e2e/nested-frame-navigation/e2e/issues/issues.e2e.spec.ts
  e2e/nested-frame-navigation/e2e/layout-root/multi-frames.e2e-spec.ts
  e2e/nested-frame-navigation/e2e/layout-root/single-frame.e2e-spec.ts
  e2e/nested-frame-navigation/e2e/screens/screen.ts
  e2e/nested-frame-navigation/e2e/screens/shared.ts
  e2e/nested-frame-navigation/e2e/screens/tab-navigation-screen.ts
  e2e/nested-frame-navigation/e2e/screens/tabview-navigation-screen.ts
  e2e/nested-frame-navigation/e2e/tab-navigation-root/bottom-navigation-root.e2e-spec.ts
  e2e/nested-frame-navigation/e2e/tab-navigation-root/tabs-root.e2e-spec.ts
  e2e/nested-frame-navigation/e2e/tab-root.e2e-spec.ts
  e2e/nested-frame-navigation/e2e/tab-view-root/tab-view-root.e2e-spec.ts
  e2e/scoped-packages/app/generated-tests/tests.ts
  e2e/scoped-packages/package.json
  e2e/ui-tests-app/app/package.json
  e2e/ui-tests-app/e2e/suites/gestures-events/gestures/gestures.e2e-spec.ts
  nativescript-core/application/application-common.ts
  nativescript-core/application/application.d.ts
  nativescript-core/application/application.ios.ts
  nativescript-core/cli-hooks/before-checkForChanges.js
  nativescript-core/css/system-classes.d.ts
  nativescript-core/css/system-classes.ts
  nativescript-core/debugger/devtools-elements.common.ts
  nativescript-core/ui/bottom-navigation/bottom-navigation.android.ts
  nativescript-core/ui/bottom-navigation/bottom-navigation.ios.ts
  nativescript-core/ui/core/view/view.android.ts
  nativescript-core/ui/enums/enums.d.ts
  nativescript-core/ui/frame/fragment.transitions.android.ts
  nativescript-core/ui/frame/frame.android.ts
  nativescript-core/ui/styling/gradient.d.ts
  nativescript-core/ui/styling/style-scope.d.ts
  nativescript-core/ui/styling/style-scope.ts
  nativescript-core/ui/tab-navigation-base/tab-strip-item/tab-strip-item.d.ts
  nativescript-core/ui/tab-navigation-base/tab-strip-item/tab-strip-item.ts
  nativescript-core/ui/tabs/tabs.android.ts
  nativescript-core/ui/tabs/tabs.ios.ts
Labels: cla: yes

#8033 chore: add no android.R tslint rule
  build/tslint.json
  package.json
Labels: cla: yes

#8031 fix(dark-mode): formatted string and html view text color
  nativescript-core/ui/html-view/html-view.ios.ts
  nativescript-core/ui/text-base/text-base.ios.ts
Labels: cla: yes, patch

#8044 chore: d.ts file cleanup
  tns-core-modules-package/tns-core-modules.d.ts
Labels: cla: yes

#8025 fix: Make sure all the native methods with @CallSuper calls the superFunc method
  nativescript-core/ui/frame/frame.android.ts
Labels: cla: yes, patch

#7987 fix(7986): nested css-calc and css-variables with fallback give incorrect result
  nativescript-core/ui/core/properties/properties.ts
  tests/app/ui/styling/style-tests.ts
Labels: cla: yes

#8071 fix(dev-tools): use app root in getDocument()
  nativescript-core/debugger/devtools-elements.common.ts
Labels: cla: yes

#8072 refactor(ios): Chrome DevTools Runtime domain
  nativescript-core/debugger/webinspector-network.ios.ts
Labels: bug, cla: yes, debugger

#8087 docs: cut the 6.2.1 release
  CHANGELOG.md
  nativescript-core/package.json
  tns-core-modules-package/package.json
  tns-core-modules-widgets/package.json
  tns-platform-declarations/package.json
Labels: cla: yes

#8061 fix(android): Fatal Exception: java.lang.OutOfMemoryError
  tns-core-modules-widgets/android/widgets/src/main/java/org/nativescript/widgets/Async.java
Labels: cla: yes

#8098 fix(android): Fatal Exception: java.lang.OutOfMemoryError (#8061)
  tns-core-modules-widgets/android/widgets/src/main/java/org/nativescript/widgets/Async.java
Labels: cla: yes, patch

#8095 fix(frame): nested frame wrong background after parent navigation
  nativescript-core/ui/frame/frame.android.ts
Labels: cla: yes, patch

#8093 fix(iOS): check for iOS 13 APIs
  nativescript-core/application/application.ios.ts
  nativescript-core/ui/activity-indicator/activity-indicator.ios.ts
  nativescript-core/ui/bottom-navigation/bottom-navigation.ios.ts
  nativescript-core/ui/core/view/view.ios.ts
  nativescript-core/ui/frame/frame.ios.ts
  nativescript-core/ui/html-view/html-view.ios.ts
  nativescript-core/ui/page/page.ios.ts
  nativescript-core/ui/tab-view/tab-view.ios.ts
  nativescript-core/ui/tabs/tabs.ios.ts
  nativescript-core/ui/text-base/text-base.ios.ts
  nativescript-core/ui/text-view/text-view.ios.ts
  tests/app/ui/page/page-tests-common.ts
Labels: cla: yes, patch

#8117 chore: update nativescript.api.md
  api-reports/NativeScript.api.md
Labels: cla: yes

#7982 fix(iOS): Opening alert/confirm on top most of modal dialogs
  nativescript-core/ui/dialogs/dialogs.ios.ts
Labels: cla: yes

#8024 feat(modal-view-ios): handle iOS 13 dismiss modal gesture
  nativescript-core/ui/core/view-base/view-base.d.ts
  nativescript-core/ui/core/view/view.android.ts
  nativescript-core/ui/core/view/view.ios.ts
Labels: cla: yes

#8121 docs(changelog): typo
  CHANGELOG.md
Labels: cla: yes

#8088 chore: merge 6.2.1 release in master
  CHANGELOG.md
  nativescript-core/debugger/devtools-elements.common.ts
  nativescript-core/ui/frame/frame.android.ts
  nativescript-core/ui/html-view/html-view.ios.ts
  nativescript-core/ui/text-base/text-base.ios.ts
Labels: cla: yes

#8123 test: execute api-extractor on CI properly
  api-reports/NativeScript.api.md
  build/prepare-core.sh
  package.json
Labels: cla: yes

#8116 docs: add test report info in the contribution guidelines
  CONTRIBUTING.md
Labels: cla: yes

#8016 fix: tab navigations don't work with lowercase xml
  api-reports/NativeScript.api.md
  nativescript-core/ui/tab-navigation-base/tab-navigation-base/tab-navigation-base.ts
  nativescript-core/ui/tab-navigation-base/tab-strip-item/tab-strip-item.ts
  nativescript-core/ui/tab-navigation-base/tab-strip/tab-strip.ts
  nativescript-core/ui/tab-view/tab-view-common.ts
  tests/app/package.json
  tests/app/test-runner.ts
  tests/app/ui/bottom-navigation/bottom-navigation-tests-new.ts
  tests/app/ui/tab-view/tab-view-tests-new.ts
  tests/app/ui/tabs/tabs-tests-new.ts
  tests/webpack.config.js
Labels: cla: yes, patch

#8127 chore: stabilize iOS13 unit tests
  nativescript-core/ui/tab-view/tab-view.android.ts
  nativescript-core/ui/tabs/tabs.android.ts
  nativescript-core/ui/tabs/tabs.ios.ts
  tests/app/platform/platform-tests.ts
  tests/app/ui/list-view/list-view-tests.ts
Labels: cla: yes

#8129 chore: housekeeping
  .vscode/launch.json
  .vscode/tasks.json
  e2e/animation/app/package.json
  e2e/cuteness.io/app/package.json
  e2e/file-qualifiers/app/package.json
  e2e/modal-navigation/app/package.json
  tests/app/package.json
  unit-tests/css/parser.ts
  unit-tests/ui/styling/css-selector.ts
Labels: cla: yes

#8128 chore: fix a typo in a comment
  nativescript-core/index.ts
Labels: cla: yes

#8124 test: fix private nativescript-dev-webpack API usage
  .vscode/launch.json
  tests/app/livesync/livesync-tests.ts
Labels: cla: yes

#8096 fix(frame): push recreated frame back in frameStack when Don't Keep Activities enabled
  nativescript-core/ui/frame/frame-common.ts
  nativescript-core/ui/frame/frame.android.ts
Labels: cla: yes, patch

#8138 chore: cut the 6.2.2 release
  CHANGELOG.md
  nativescript-core/package.json
  tns-platform-declarations/package.json
Labels: cla: yes

#8144 chore: cut 6.2.3 release
  nativescript-core/package.json
  tns-core-modules-package/package.json
  tns-core-modules-widgets/package.json
  tns-platform-declarations/package.json
Labels: cla: yes

#8112 feat: support requestAnimationFrame
  nativescript-core/animation-frame/animation-frame.d.ts
  nativescript-core/animation-frame/animation-frame.ts
  nativescript-core/animation-frame/animation-native.android.ts
  nativescript-core/animation-frame/animation-native.d.ts
  nativescript-core/animation-frame/animation-native.ios.ts
  nativescript-core/animation-frame/package.json
  nativescript-core/globals/globals.ts
  nativescript-core/globals/polyfills/animation/animation.d.ts
  nativescript-core/globals/polyfills/animation/animation.ts
  nativescript-core/globals/polyfills/animation/package.json
  tests/app/animation-frame/animation-frame.ts
  tests/app/test-runner.ts
Labels: cla: yes, ♥ community PR

#8042 fix(grid-layout): value parser will now accept strings or numbers
  nativescript-core/ui/layouts/grid-layout/grid-layout-common.ts
Labels: cla: yes, ♥ community PR
