Repository NativeScript/NativeScript, pull requests merged in 2019-05, with the labels that each got.

#7182 fix(ios): add null check to TouchGestureRecognizer
  tns-core-modules/ui/gestures/gestures.ios.ts
Labels: cla: yes, ♥ community PR

#7186 fix: throw if failed to load component
  tests/app/ui/builder/builder-tests.ts
  tests/app/xml-declaration/xml-declaration-tests.ts
  tns-core-modules/ui/builder/builder.ts
Labels: cla: yes, in progress

#7199 chore: remove http-server dependency
  package.json
Labels: cla: yes, in progress

#7175 fix(ios-http-get): http failure during parsing xml
  tns-core-modules/http/http-request/http-request.ios.ts
Labels: cla: yes, in progress, patch

#7200 release: cut the 5.3.2 release
  CHANGELOG.md
  tns-core-modules/package.json
  tns-platform-declarations/package.json
Labels: cla: yes, in progress

#7208 tests: add mochawesome reporter
  e2e/config/mocha.opts
  e2e/modal-navigation/.gitignore
  e2e/modal-navigation/e2e/android-back-button.e2e-spec.ts
  e2e/modal-navigation/e2e/modal-frame.e2e-spec.ts
  e2e/modal-navigation/e2e/modal-layout.e2e-spec.ts
  e2e/modal-navigation/e2e/modal-page.e2e-spec.ts
  e2e/modal-navigation/e2e/modal-tab.e2e-spec.ts
  e2e/modal-navigation/e2e/setup.ts
  e2e/modal-navigation/package.json
  e2e/nested-frame-navigation/.gitignore
  e2e/nested-frame-navigation/e2e/frame-root.e2e-spec.ts
  e2e/nested-frame-navigation/e2e/frame-tab-root.e2e-spec.ts
  e2e/nested-frame-navigation/e2e/issues.e2e.spec.ts
  e2e/nested-frame-navigation/e2e/layout-root.e2e-spec.ts
  e2e/nested-frame-navigation/e2e/setup.ts
  e2e/nested-frame-navigation/e2e/tab-root.e2e-spec.ts
  e2e/nested-frame-navigation/package.json
Labels: cla: yes, in progress

#7204 chore: merge release to master
  CHANGELOG.md
  package.json
  tns-core-modules/http/http-request/http-request.ios.ts
Labels: cla: yes, in progress

#7215 tests: include mochawesome reporter
  e2e/animation/.gitignore
  e2e/animation/e2e/animation.e2e-spec.ts
  e2e/animation/e2e/setup.ts
  e2e/animation/package.json
  e2e/modal-navigation/package.json
  e2e/nested-frame-navigation/package.json
Labels: cla: yes, in progress

#7216 chore: merge release in master
  e2e/animation/.gitignore
  e2e/animation/e2e/animation.e2e-spec.ts
  e2e/animation/e2e/setup.ts
  e2e/animation/package.json
  e2e/config/mocha.opts
  e2e/modal-navigation/.gitignore
  e2e/modal-navigation/e2e/android-back-button.e2e-spec.ts
  e2e/modal-navigation/e2e/modal-frame.e2e-spec.ts
  e2e/modal-navigation/e2e/modal-layout.e2e-spec.ts
  e2e/modal-navigation/e2e/modal-page.e2e-spec.ts
  e2e/modal-navigation/e2e/modal-tab.e2e-spec.ts
  e2e/modal-navigation/e2e/setup.ts
  e2e/modal-navigation/package.json
  e2e/nested-frame-navigation/.gitignore
  e2e/nested-frame-navigation/e2e/frame-root.e2e-spec.ts
  e2e/nested-frame-navigation/e2e/frame-tab-root.e2e-spec.ts
  e2e/nested-frame-navigation/e2e/issues.e2e.spec.ts
  e2e/nested-frame-navigation/e2e/layout-root.e2e-spec.ts
  e2e/nested-frame-navigation/e2e/setup.ts
  e2e/nested-frame-navigation/e2e/tab-root.e2e-spec.ts
  e2e/nested-frame-navigation/package.json
Labels: cla: yes, in progress

#7188 fix(ios-tabview): crash when setting tab text color
  apps/app/ui-tests-app/tab-view/main-page.ts
  apps/app/ui-tests-app/tab-view/tab-text-color.xml
  tns-core-modules/ui/tab-view/tab-view.ios.ts
Labels: cla: yes, e2e test needed, in progress, patch

#7189 fix(ios-modal): closeCallback not being called with popover presentation style
  e2e/modal-navigation/app/home/home-page.ts
  e2e/modal-navigation/app/home/home-page.xml
  e2e/modal-navigation/app/modal-no-page/modal-no-page.ts
  e2e/modal-navigation/app/modal/modal-page.ts
  e2e/modal-navigation/package.json
  e2e/modal-navigation/references.d.ts
  tns-core-modules/ui/core/view/view-common.ts
  tns-core-modules/ui/core/view/view.ios.ts
Labels: cla: yes, e2e test needed, in progress, patch

#7171 fix(iOS): Image cache module not longer sets null in NSCache
  AUTHORS
  tests/app/testRunner.ts
  tests/app/ui/image-cache/image-cache-tests.ts
  tns-core-modules/ui/image-cache/image-cache.ios.ts
Labels: cla: yes, in progress

#7190 fix(android/button): possible incorrect button visual state
  tns-core-modules/ui/button/button.android.ts
Labels: cla: yes, in progress

#7218 chore: merge release to master
  apps/app/ui-tests-app/tab-view/main-page.ts
  apps/app/ui-tests-app/tab-view/tab-text-color.xml
  e2e/modal-navigation/app/home/home-page.ts
  e2e/modal-navigation/app/home/home-page.xml
  e2e/modal-navigation/app/modal-no-page/modal-no-page.ts
  e2e/modal-navigation/app/modal/modal-page.ts
  e2e/modal-navigation/package.json
  e2e/modal-navigation/references.d.ts
  tns-core-modules/ui/core/view/view-common.ts
  tns-core-modules/ui/core/view/view.ios.ts
  tns-core-modules/ui/tab-view/tab-view.ios.ts
Labels: cla: yes, in progress

#7225 chore: remove clashing typings
  e2e/animation/package.json
  e2e/modal-navigation/package.json
  e2e/nested-frame-navigation/package.json
Labels: in progress

#7224 chore(android): disable test_ImageCache_ValidUrl on api19
  tests/app/ui/image-cache/image-cache-tests.ts
Labels: cla: yes, in progress

#7220 fix(devtools-ios): Ensure UI modifications run on main thread
  tests/app/utils/utils-tests.ts
  tns-core-modules/debugger/devtools-elements.common.ts
  tns-core-modules/utils/mainthread-helper.android.ts
  tns-core-modules/utils/mainthread-helper.d.ts
  tns-core-modules/utils/mainthread-helper.ios.ts
  tns-core-modules/utils/utils-common.ts
  tns-core-modules/utils/utils.d.ts
Labels: bug, cla: yes, in progress, os: ios

#7203 fix-next(HMR): apply changes in page styles when app root is frame
  tns-core-modules/application/application.ios.ts
  tns-core-modules/module.d.ts
  tns-core-modules/ui/core/view/view-common.ts
  tns-core-modules/ui/core/view/view.d.ts
  tns-core-modules/ui/frame/frame-common.ts
  tns-core-modules/ui/frame/frame.android.ts
  tns-core-modules/ui/frame/frame.ios.ts
  tns-core-modules/ui/page/page-common.ts
Labels: cla: yes, in progress

#7136 feat(android): elevation shadow support
  apps/app/ui-tests-app/css/elevation.css
  apps/app/ui-tests-app/css/elevation.ts
  apps/app/ui-tests-app/css/elevation.xml
  apps/app/ui-tests-app/css/main-page.ts
  tns-core-modules/ui/button/button.android.ts
  tns-core-modules/ui/core/view-base/view-base.ts
  tns-core-modules/ui/core/view/view-common.ts
  tns-core-modules/ui/core/view/view.android.ts
  tns-core-modules/ui/core/view/view.d.ts
  tns-core-modules/ui/styling/style-properties.ts
  tns-core-modules/ui/styling/style/style.d.ts
  tns-core-modules/ui/styling/style/style.ts
Labels: cla: yes, e2e test needed, in progress

#7228 tests: fix require mainthread-module
  unit-tests/polyfills/mainthread-helper.ts
  unit-tests/runtime.ts
Labels: cla: yes, in progress

#7231 chore: update ui tests with androidElevation
  apps/app/ui-tests-app/button/button-border.css
  apps/app/ui-tests-app/css/pixels.xml
  apps/app/ui-tests-app/flexbox/flexbox.css
  apps/app/ui-tests-app/issues/issue-3113.css
Labels: cla: yes, in progress

#7236 chore: bump versions to 6.0.0
  tns-core-modules-widgets/package.json
  tns-core-modules/package.json
  tns-platform-declarations/package.json
Labels: in progress

#7237 fix(text): crash when removing FormattedText
  tests/app/ui/label/label-tests.ts
  tns-core-modules/ui/text-base/text-base.android.ts
  tns-core-modules/ui/text-base/text-base.ios.ts
Labels: cla: yes, in progress

#7235 release: cut the 5.4.0 release
  CHANGELOG.md
  tns-core-modules/package.json
Labels: cla: yes, in progress

#7244 chore: merge release to master
  CHANGELOG.md
  tests/app/ui/label/label-tests.ts
  tns-core-modules/ui/text-base/text-base.android.ts
  tns-core-modules/ui/text-base/text-base.ios.ts
Labels: cla: yes, in progress

#7250 fix(android): elevation should not require explicit dynamic elevation
  tns-core-modules/ui/button/button.android.ts
  tns-core-modules/ui/core/view/view.android.ts
Labels: e2e test needed, in progress, patch

#7253 chore: merge release to master
  tns-core-modules/ui/button/button.android.ts
  tns-core-modules/ui/core/view/view.android.ts
Labels: cla: yes, in progress

#7254 chore: return http server with npx
  package.json
Labels: cla: yes, in progress

#7255 refactor: platform specific logic from view common
  tns-core-modules/ui/core/view/view-common.ts
  tns-core-modules/ui/core/view/view.ios.ts
Labels: cla: yes, in progress, patch

#5147 feat(animation): support animating width/height properties
  apps/app/ui-tests-app/animation/animation-army-100.ts
  apps/app/ui-tests-app/animation/animation-army-100.xml
  apps/app/ui-tests-app/animation/animation-curves.ts
  apps/app/ui-tests-app/animation/animation-curves.xml
  apps/app/ui-tests-app/animation/effect-summary-details.ts
  apps/app/ui-tests-app/animation/effect-summary-details.xml
  apps/app/ui-tests-app/animation/height-basic.ts
  apps/app/ui-tests-app/animation/height-basic.xml
  apps/app/ui-tests-app/animation/layout-stack-height.ts
  apps/app/ui-tests-app/animation/layout-stack-height.xml
  apps/app/ui-tests-app/animation/main-page.ts
  apps/app/ui-tests-app/animation/main-page.xml
  apps/app/ui-tests-app/main-page.ts
  apps/app/ui-tests-app/test-page-main-view-model.ts
  tests/app/ui/animation/animation-tests.ts
  tests/app/ui/styling/style-properties-tests.ts
  tns-core-modules/ui/animation/animation-common.ts
  tns-core-modules/ui/animation/animation.android.ts
  tns-core-modules/ui/animation/animation.d.ts
  tns-core-modules/ui/animation/animation.ios.ts
  tns-core-modules/ui/animation/keyframe-animation.ts
  tns-core-modules/ui/styling/style-properties.d.ts
  tns-core-modules/ui/styling/style-properties.ts
Labels: docs needed, e2e test needed

#7269 chore: merge release to master
  tns-core-modules/ui/core/view/view-common.ts
  tns-core-modules/ui/core/view/view.ios.ts
Labels: cla: yes

#7251 fix(hmr): quick fade upon replace navigation
  tests/app/livesync/livesync-tests.ts
  tns-core-modules/ui/core/view/view-common.ts
  tns-core-modules/ui/frame/fragment.transitions.android.ts
  tns-core-modules/ui/frame/frame.android.ts
  tns-core-modules/ui/frame/frame.ios.ts
  tns-core-modules/ui/page/page.ios.ts
Labels: cla: yes, e2e test needed, in progress, patch

#7275 chore: merge release to master
  tests/app/livesync/livesync-tests.ts
  tns-core-modules/ui/core/view/view-common.ts
  tns-core-modules/ui/frame/fragment.transitions.android.ts
  tns-core-modules/ui/frame/frame.android.ts
  tns-core-modules/ui/frame/frame.ios.ts
  tns-core-modules/ui/page/page.ios.ts
Labels: cla: yes

#7271 fix(android): CommonLayoutParams measure/layout child guard
  tns-core-modules-widgets/android/widgets/src/main/java/org/nativescript/widgets/CommonLayoutParams.java
Labels: cla: yes, os: android, patch

#7232 refactor: update access modifier
  tns-core-modules/ui/styling/style-scope.ts
Labels: cla: yes, in progress

#7276 chore: merge release to master
  tns-core-modules-widgets/android/widgets/src/main/java/org/nativescript/widgets/CommonLayoutParams.java
Labels: cla: yes

#7278 release: cut the 5.4.1 release
  CHANGELOG.md
  tns-core-modules-widgets/package.json
  tns-core-modules/package.json
  tns-platform-declarations/package.json
Labels: cla: yes

#7230 fix(ios): undefined is not an object (evaluating 'measureSpec.setColumn')
  tns-core-modules/ui/layouts/grid-layout/grid-layout-common.ts
  tns-core-modules/ui/layouts/grid-layout/grid-layout.ios.ts
  tns-core-modules/ui/proxy-view-container/proxy-view-container.ts
Labels: cla: yes, ♥ community PR
