Repository NativeScript/NativeScript, pull requests merged in 2019-10, with the labels that each got.

#7881 chore: merge release to master
  tests/app/application/application-tests-common.ts
  tests/app/ui/test-pages/bindingExpressions_logicalComparisonOperators_testPage.xml
  tns-core-modules/application/application.android.ts
  tns-core-modules/application/application.d.ts
  tns-core-modules/application/application.ios.ts
  tns-core-modules/ui/tab-navigation-base/tab-strip/tab-strip.d.ts
  tns-core-modules/ui/tab-navigation-base/tab-strip/tab-strip.ts
Labels: cla: yes

#7889 docs: Updated slack channel link
  README.md
Labels: cla: yes

#7671 feat(file-system): async read/write
  tests/app/file-system/file-system-tests.ts
  tns-core-modules-widgets/android/widgets/src/main/java/org/nativescript/widgets/Async.java
  tns-core-modules-widgets/ios/TNSWidgets/TNSWidgets.xcodeproj/project.pbxproj
  tns-core-modules-widgets/ios/TNSWidgets/TNSWidgets/NSData+Async.h
  tns-core-modules-widgets/ios/TNSWidgets/TNSWidgets/NSData+Async.m
  tns-core-modules-widgets/ios/TNSWidgets/TNSWidgets/NSString+Async.h
  tns-core-modules-widgets/ios/TNSWidgets/TNSWidgets/NSString+Async.m
  tns-core-modules-widgets/ios/TNSWidgets/TNSWidgets/TNSWidgets.h
  tns-core-modules/file-system/file-system-access.android.ts
  tns-core-modules/file-system/file-system-access.d.ts
  tns-core-modules/file-system/file-system-access.ios.ts
  tns-core-modules/file-system/file-system.d.ts
  tns-core-modules/file-system/file-system.ts
  tns-platform-declarations/android/org.nativescript.widgets.d.ts
Labels: cla: yes, docs needed, ♥ community PR

#7805 feat(ActionBar): add Android inset ActionBar property to control the titleView content insets
  tns-core-modules/ui/action-bar/action-bar-common.ts
  tns-core-modules/ui/action-bar/action-bar.android.ts
  tns-core-modules/ui/action-bar/action-bar.d.ts
  tns-core-modules/ui/styling/style/style.d.ts
  tns-core-modules/ui/styling/style/style.ts
Labels: cla: yes, docs needed

#7893 docs: update readme
  README.md
Labels: cla: yes

#7754 chore(travis-ci): add circular references check
  .travis.yml
  tests/package.json
  tests/webpack.config.js
Labels: cla: yes

#7880 feat: adding support for the new selectedSegmentTintColor property
  tns-core-modules/ui/segmented-bar/segmented-bar.ios.ts
Labels: cla: yes

#7847 chore: remove short imports
  tns-core-modules/bundle-entry-points.ts
  tns-core-modules/color/color-common.ts
  tns-core-modules/fetch/fetch.js
  tns-core-modules/js-libs/polymer-expressions/polymer-expressions.js
  tns-core-modules/ui/frame/frame-common.ts
Labels: cla: yes

#7845 chore: remove grunt and clean-up
  .gitignore
  CONTRIBUTING.md
  build-docs.sh
  expect.exp
  gruntfile.js
  package.json
  tns-core-modules/package.json
  tsconfig.json
  tsconfig.modules.json
  tsconfig.public.es2016.json
  tsconfig.public.es6.json
  tsconfig.shared.json
  tsconfig.tslint.json
  tsconfig.unit-tests.json
  unit-tests/tsconfig.json
Labels: cla: yes

#7826 feat(ios-dark-mode): adapt dynamic system colors
  tests/app/ui/page/page-tests-common.ts
  tns-core-modules/application/application.ios.ts
  tns-core-modules/ui/activity-indicator/activity-indicator.ios.ts
  tns-core-modules/ui/page/page.ios.ts
  tns-core-modules/ui/tabs/tabs.ios.ts
  tns-core-modules/ui/text-base/text-base.ios.ts
  tns-core-modules/ui/text-view/text-view.ios.ts
Labels: cla: yes

#7789 fix(css-android): restore elements' native features if offending css is removed while the app is running
  tns-core-modules/ui/styling/background.android.ts
Labels: cla: yes

#7906 chore: update dev workflow
  DevelopmentWorkflow.md
Labels: cla: yes

#7887 feat(dark-mode): add system appearance property, event and CSS classes
  tns-core-modules/application/application-common.ts
  tns-core-modules/application/application.android.ts
  tns-core-modules/application/application.d.ts
  tns-core-modules/application/application.ios.ts
  tns-core-modules/css/system-classes.d.ts
  tns-core-modules/css/system-classes.ts
  tns-core-modules/ui/bottom-navigation/bottom-navigation.ios.ts
  tns-core-modules/ui/core/view/view.d.ts
  tns-core-modules/ui/core/view/view.ios.ts
  tns-core-modules/ui/enums/enums.d.ts
  tns-core-modules/ui/enums/enums.ts
  tns-core-modules/ui/frame/frame.android.ts
  tns-core-modules/ui/frame/frame.ios.ts
  tns-core-modules/ui/page/page.ios.ts
  tns-core-modules/ui/tab-view/tab-view.ios.ts
  tns-core-modules/ui/tabs/tabs.ios.ts
Labels: cla: yes

#7907 feat(css): add attribute scoped css without global refresh
  tns-core-modules/application/application.android.ts
  tns-core-modules/application/application.d.ts
  tns-core-modules/application/application.ios.ts
Labels: cla: yes

#7910 fix: change the way we import 'esprima' to avoid wrong path resolution in Angular projects
  tns-core-modules/js-libs/polymer-expressions/polymer-expressions.js
Labels: cla: yes

#7916 fix: xml parsing when input value is reported as object instead of string
  tns-core-modules/ui/builder/builder.ts
Labels: cla: yes

#7918 fix(action-bar-ios): navigation button support for font icons
  e2e/ui-tests-app/e2e/suites/tab-navigation/tab-view/tab-view-css-properties.e2e-spec.ts
  tns-core-modules/ui/action-bar/action-bar-common.ts
  tns-core-modules/ui/action-bar/action-bar.android.ts
  tns-core-modules/ui/action-bar/action-bar.ios.ts
Labels: cla: yes

#7870 svetoslavtsenov/extend gestures tests
  e2e/ui-tests-app/.vscode/launch.json
  e2e/ui-tests-app/app/events/gestures-page.ts
  e2e/ui-tests-app/app/events/handlers-page.ts
  e2e/ui-tests-app/app/events/handlers-page.xml
  e2e/ui-tests-app/e2e/suites/css/styles/styles-page.ts
  e2e/ui-tests-app/e2e/suites/gestures-events/common/common-tests.ts
  e2e/ui-tests-app/e2e/suites/gestures-events/events-gestures-base-page.ts
  e2e/ui-tests-app/e2e/suites/gestures-events/gestures/gestures-page.ts
  e2e/ui-tests-app/e2e/suites/gestures-events/gestures/gestures.e2e-spec.ts
  e2e/ui-tests-app/e2e/suites/tab-navigation/bottom-navigation/bottom-navigation.e2e-spec.ts
  e2e/ui-tests-app/e2e/suites/tab-navigation/tab-view/tab-view-css-properties.e2e-spec.ts
  e2e/ui-tests-app/e2e/suites/tab-navigation/tabs/tabs-tests.e2e-spec.ts
Labels: cla: yes

#7929 chore: update readme
  tns-platform-declarations/README.md
Labels: cla: yes

#7937 test: fix navigate to handlers
  e2e/ui-tests-app/e2e/suites/gestures-events/common/common-tests.ts
Labels: cla: yes

#7936 feat: update material components dependency to 92.3
  tns-core-modules/platforms/ios/Podfile
Labels: cla: yes

#7940 chore: merge release master tests
  e2e/ui-tests-app/.vscode/launch.json
  e2e/ui-tests-app/app/events/gestures-page.ts
  e2e/ui-tests-app/app/events/handlers-page.ts
  e2e/ui-tests-app/app/events/handlers-page.xml
  e2e/ui-tests-app/e2e/suites/css/styles/styles-page.ts
  e2e/ui-tests-app/e2e/suites/gestures-events/common/common-tests.ts
  e2e/ui-tests-app/e2e/suites/gestures-events/events-gestures-base-page.ts
  e2e/ui-tests-app/e2e/suites/gestures-events/gestures/gestures-page.ts
  e2e/ui-tests-app/e2e/suites/gestures-events/gestures/gestures.e2e-spec.ts
  e2e/ui-tests-app/e2e/suites/tab-navigation/bottom-navigation/bottom-navigation.e2e-spec.ts
  e2e/ui-tests-app/e2e/suites/tab-navigation/tabs/tabs-tests.e2e-spec.ts
Labels: cla: yes

#7947 feat(css): add attribute scoped css without global refresh (#7907)
  tns-core-modules/application/application.android.ts
  tns-core-modules/application/application.d.ts
  tns-core-modules/application/application.ios.ts
Labels: cla: yes, patch

#7948 fix(frame-android): IllegalStateException: The specified child already has a parent
  tns-core-modules/ui/frame/frame.android.ts
Labels: cla: yes, patch

#7837 fix(tabs-ios9): no view controller managing visible view error
  tests/app/ui/image-cache/image-cache-tests.ts
  tests/app/xml-parser-tests/xml-parser-tests.ts
  tns-core-modules/ui/tabs/tabs.ios.ts
Labels: cla: yes, patch

#7960 docs: cut the 6.1.2 release
  CHANGELOG.md
  tns-core-modules-widgets/package.json
  tns-core-modules/package.json
  tns-platform-declarations/package.json
Labels: cla: yes

#7925 feat: overhaul and streamline Android page navigation transitions
  tests/app/ui/tab-view/tab-view-root-tests.ts
  tests/webpack.config.js
  tns-core-modules-widgets/android/widgets/build.gradle
  tns-core-modules-widgets/android/widgets/src/main/java/org/nativescript/widgets/CustomTransition.java
  tns-core-modules-widgets/android/widgets/src/main/java/org/nativescript/widgets/FragmentBase.java
  tns-core-modules/ui/bottom-navigation/bottom-navigation.android.ts
  tns-core-modules/ui/core/view/view-common.ts
  tns-core-modules/ui/core/view/view.android.ts
  tns-core-modules/ui/core/view/view.d.ts
  tns-core-modules/ui/frame/fragment.android.ts
  tns-core-modules/ui/frame/fragment.transitions.android.ts
  tns-core-modules/ui/frame/fragment.transitions.d.ts
  tns-core-modules/ui/frame/frame.android.ts
  tns-core-modules/ui/frame/frame.d.ts
  tns-core-modules/ui/tab-navigation-base/tab-navigation-base/tab-navigation-base.ts
  tns-core-modules/ui/tab-view/tab-view.android.ts
  tns-core-modules/ui/tabs/tabs.android.ts
  tns-core-modules/ui/transition/fade-transition.android.ts
  tns-core-modules/ui/transition/flip-transition.android.ts
  tns-platform-declarations/android/org.nativescript.widgets.d.ts
Labels: cla: yes

#7944 fix(android): check for root view on configuration changed
  tns-core-modules/application/application-common.ts
  tns-core-modules/application/application.android.ts
Labels: cla: yes

#7961 chore: merge release in master patch
  CHANGELOG.md
  tests/app/ui/image-cache/image-cache-tests.ts
  tests/app/xml-parser-tests/xml-parser-tests.ts
  tns-core-modules/ui/tabs/tabs.ios.ts
Labels: cla: yes

#7965 fix(action-bar-ios13): action bar items population
  tns-core-modules/ui/action-bar/action-bar.ios.ts
Labels: cla: yes

#7931 fix: UIUserInterfaceStyle is undefined for iOS <= 11
  tests/app/application/application-tests-common.ts
  tests/app/application/application-tests.android.ts
  tests/app/application/application-tests.ios.ts
  tests/app/ui/styling/root-views-css-classes-tests.ts
  tns-core-modules/application/application.d.ts
  tns-core-modules/application/application.ios.ts
Labels: cla: yes

#7972 chore: bump tns-core-modules-compat
  tns-core-modules-package/package.json
Labels: cla: yes

#7973 chore: bump version to 6.3.0
  nativescript-core/package.json
  tns-core-modules-package/package.json
  tns-core-modules-widgets/package.json
  tns-platform-declarations/package.json
Labels: cla: yes

#7981 chore: add thumbs.db to .gitignore
  .gitignore
Labels: cla: yes

#7975 tests: update gesture test for api19 and api29
  CONTRIBUTING.md
  e2e/ui-tests-app/app/package.json
  e2e/ui-tests-app/e2e/suites/gestures-events/gestures/gestures.e2e-spec.ts
Labels: cla: yes

#7992 fix-next(css-classes): increase application CSS selector version at runtime
  nativescript-core/application/application-common.ts
  nativescript-core/ui/styling/style-scope.d.ts
  nativescript-core/ui/styling/style-scope.ts
Labels: cla: yes

#7997 test: fix modal navigation tests
  e2e/modal-navigation/.vscode/launch.json
  e2e/modal-navigation/e2e/screen.ts
Labels: cla: yes

#7993 chore: add re-exports for ts files
  build/generate-tns-compat.ts
  e2e/scoped-packages/app/generated-tests/tests.ts
  e2e/scoped-packages/package.json
Labels: cla: yes

#8003 refactor: android.R to const for perf reasons
  nativescript-core/ui/core/view/view.android.ts
  nativescript-core/ui/frame/fragment.transitions.android.ts
Labels: cla: yes

#8002 refactor: deprecated goBack() usage
  nativescript-core/ui/frame/frame.android.ts
Labels: cla: yes, patch

#7998 chore(hook): Check for min required webpack version
  nativescript-core/cli-hooks/before-checkForChanges.js
Labels: cla: yes, patch

#8005 fix(iOS): set root viewe css classes before setup UI
  nativescript-core/application/application.ios.ts
  nativescript-core/css/system-classes.d.ts
  nativescript-core/css/system-classes.ts
Labels: cla: yes

#8009 chore: More forgiving version check hook
  nativescript-core/cli-hooks/before-checkForChanges.js
Labels: cla: yes

#8013 refactor(dev-tools): replace topmost() usage
  nativescript-core/debugger/devtools-elements.common.ts
Labels: cla: yes

#8022 fix(css-class): set class before showing window
  nativescript-core/application/application.ios.ts
Labels: cla: yes

#8019 chore: update README.md
  README.md
Labels: cla: yes

#8023 chore: add api-report check to travis
  .travis.yml
  CONTRIBUTING.md
  package.json
Labels: cla: yes

#8030 fix: bot nav android crash when change tab and suspend
  nativescript-core/ui/bottom-navigation/bottom-navigation.android.ts
Labels: cla: yes

#8011 chore: cut the 6.2.0 release
  CHANGELOG.md
Labels: cla: yes

#8012 test: refactor frames root tests
  e2e/nested-frame-navigation/.vscode/launch.json
  e2e/nested-frame-navigation/app/package.json
  e2e/nested-frame-navigation/e2e/config.ts
  e2e/nested-frame-navigation/e2e/frame-root/bottom-navigation.e2e-spec.ts
  e2e/nested-frame-navigation/e2e/frame-root/multi-frames.e2e-spec.ts
  e2e/nested-frame-navigation/e2e/frame-root/single-frame.e2e-spec.ts
  e2e/nested-frame-navigation/e2e/frame-root/tab-view.e2e-spec.ts
  e2e/nested-frame-navigation/e2e/frame-root/tabs.e2e-spec.ts
  e2e/nested-frame-navigation/e2e/frame-tab-root.e2e-spec.ts
  e2e/nested-frame-navigation/e2e/issues/issues.e2e.spec.ts
  e2e/nested-frame-navigation/e2e/layout-root/multi-frames.e2e-spec.ts
  e2e/nested-frame-navigation/e2e/layout-root/single-frame.e2e-spec.ts
  e2e/nested-frame-navigation/e2e/screens/screen.ts
  e2e/nested-frame-navigation/e2e/screens/shared.ts
  e2e/nested-frame-navigation/e2e/screens/tab-navigation-screen.ts
  e2e/nested-frame-navigation/e2e/screens/tabview-navigation-screen.ts
  e2e/nested-frame-navigation/e2e/tab-navigation-root/bottom-navigation-root.e2e-spec.ts
  e2e/nested-frame-navigation/e2e/tab-navigation-root/tabs-root.e2e-spec.ts
  e2e/nested-frame-navigation/e2e/tab-root.e2e-spec.ts
  e2e/nested-frame-navigation/e2e/tab-view-root/tab-view-root.e2e-spec.ts
Labels: cla: yes

#8043 fix: fixing API ref build script - docs
  build-docs.sh
Labels: cla: yes
