Repository NativeScript/NativeScript, pull requests merged in 2019-06, with the labels that each got.

#7299 chore: cherry-pick community pr #7230
  tns-core-modules/ui/layouts/grid-layout/grid-layout-common.ts
  tns-core-modules/ui/layouts/grid-layout/grid-layout.ios.ts
  tns-core-modules/ui/proxy-view-container/proxy-view-container.ts
Labels: patch

#7280 updating broken links
  CodingConvention.md
Labels: cla: yes

#7298 fix(ios): potential memory leak with propertybag implementation
  tns-core-modules-widgets/ios/TNSWidgets/TNSWidgets.xcodeproj/project.pbxproj
  tns-core-modules-widgets/ios/TNSWidgets/TNSWidgets/UIView+PassThroughParent.m
  tns-core-modules-widgets/ios/TNSWidgets/TNSWidgets/UIView+PropertyBag.h
  tns-core-modules-widgets/ios/TNSWidgets/TNSWidgets/UIView+PropertyBag.m
Labels: cla: yes, patch

#7301 chore: merge release to master
  CHANGELOG.md
  tns-core-modules-widgets/ios/TNSWidgets/TNSWidgets.xcodeproj/project.pbxproj
  tns-core-modules-widgets/ios/TNSWidgets/TNSWidgets/UIView+PassThroughParent.m
  tns-core-modules-widgets/ios/TNSWidgets/TNSWidgets/UIView+PropertyBag.h
  tns-core-modules-widgets/ios/TNSWidgets/TNSWidgets/UIView+PropertyBag.m
Labels: cla: yes

#7293 fix(hmr): support for multi module replacement
  tests/app/livesync/livesync-button-page.scss
  tests/app/livesync/livesync-tests.ts
  tns-core-modules/ui/frame/fragment.transitions.android.ts
  tns-core-modules/ui/frame/frame-common.ts
  tns-core-modules/ui/frame/frame.android.ts
  tns-core-modules/ui/frame/frame.d.ts
  tns-core-modules/ui/frame/frame.ios.ts
  tns-core-modules/ui/page/page.ios.ts
Labels: cla: yes, patch

#7314 fix(platform-declarations-ios): Change 2^64-1 enum values to -1
  tns-platform-declarations/ios/objc-x86_64/objc!MediaPlayer.d.ts
  tns-platform-declarations/ios/objc-x86_64/objc!PassKit.d.ts
  tns-platform-declarations/ios/objc-x86_64/objc!SceneKit.d.ts
  tns-platform-declarations/ios/objc-x86_64/objc!UIKit.d.ts
  tns-platform-declarations/ios/objc-x86_64/objc!WebKit.d.ts
Labels: bug, cla: yes, os: ios, patch

#7315 chore(widgets): Build TNSWidgets.framework.dSYM package
  tns-core-modules-widgets/build.ios.sh
  tns-core-modules-widgets/ios/build.sh
Labels: cla: yes, feature

#7326 release: cut the 5.4.2 release
  CHANGELOG.md
  tns-core-modules-widgets/package.json
  tns-core-modules/package.json
  tns-platform-declarations/package.json
Labels: cla: yes

#7318 chore: merge release to master
  tests/app/livesync/livesync-button-page.scss
  tests/app/livesync/livesync-tests.ts
  tns-core-modules-widgets/build.ios.sh
  tns-core-modules-widgets/ios/build.sh
  tns-core-modules/ui/frame/fragment.transitions.android.ts
  tns-core-modules/ui/frame/frame-common.ts
  tns-core-modules/ui/frame/frame.android.ts
  tns-core-modules/ui/frame/frame.d.ts
  tns-core-modules/ui/frame/frame.ios.ts
  tns-core-modules/ui/page/page.ios.ts
  tns-platform-declarations/ios/objc-x86_64/objc!MediaPlayer.d.ts
  tns-platform-declarations/ios/objc-x86_64/objc!PassKit.d.ts
  tns-platform-declarations/ios/objc-x86_64/objc!SceneKit.d.ts
  tns-platform-declarations/ios/objc-x86_64/objc!UIKit.d.ts
  tns-platform-declarations/ios/objc-x86_64/objc!WebKit.d.ts
Labels: cla: yes

#7330 chore: merge release to master
  CHANGELOG.md
Labels: cla: yes

#7039 feat(android): androidX support
  apps/app/App_Resources/Android/AndroidManifest.xml
  apps/app/App_Resources/Android/app.gradle
  apps/app/perf-app/recycling/main-page.ts
  apps/package.json
  tests/app/App_Resources/Android/app.gradle
  tests/app/ui/action-bar/action-bar-tests.android.ts
  tests/app/ui/tab-view/tab-view-navigation-tests.ts
  tests/app/ui/tab-view/tab-view-tests-native.android.ts
  tests/app/ui/tab-view/tab-view-tests.ts
  tns-core-modules-widgets/android/build.gradle
  tns-core-modules-widgets/android/widgets/build.gradle
  tns-core-modules-widgets/android/widgets/src/main/java/org/nativescript/widgets/BorderDrawable.java
  tns-core-modules-widgets/android/widgets/src/main/java/org/nativescript/widgets/FlexboxLayout.java
  tns-core-modules-widgets/android/widgets/src/main/java/org/nativescript/widgets/FragmentBase.java
  tns-core-modules-widgets/android/widgets/src/main/java/org/nativescript/widgets/Image/Cache.java
  tns-core-modules-widgets/android/widgets/src/main/java/org/nativescript/widgets/SegmentedBarColorDrawable.java
  tns-core-modules-widgets/android/widgets/src/main/java/org/nativescript/widgets/TabLayout.java
  tns-core-modules-widgets/android/widgets/src/main/java/org/nativescript/widgets/TabViewPager.java
  tns-core-modules/application/application.android.ts
  tns-core-modules/application/application.d.ts
  tns-core-modules/package.json
  tns-core-modules/ui/action-bar/action-bar.android.ts
  tns-core-modules/ui/animation/animation.android.ts
  tns-core-modules/ui/core/view/view.android.ts
  tns-core-modules/ui/core/view/view.d.ts
  tns-core-modules/ui/editable-text-base/editable-text-base.android.ts
  tns-core-modules/ui/frame/activity.android.ts
  tns-core-modules/ui/frame/fragment.transitions.android.ts
  tns-core-modules/ui/frame/frame.android.ts
  tns-core-modules/ui/frame/frame.d.ts
  tns-core-modules/ui/gestures/gestures.android.ts
  tns-core-modules/ui/page/page.android.ts
  tns-core-modules/ui/search-bar/search-bar.android.ts
  tns-core-modules/ui/styling/background.android.ts
  tns-core-modules/ui/tab-view/tab-view.android.ts
  tns-core-modules/ui/tab-view/tab-view.d.ts
  tns-core-modules/utils/utils.android.ts
  tns-platform-declarations/android-17.d.ts
  tns-platform-declarations/android-18.d.ts
  tns-platform-declarations/android-19.d.ts
  tns-platform-declarations/android-20.d.ts
  tns-platform-declarations/android-21.d.ts
  tns-platform-declarations/android-22.d.ts
  tns-platform-declarations/android-23.d.ts
  tns-platform-declarations/android-24.d.ts
  tns-platform-declarations/android-25.d.ts
  tns-platform-declarations/android-26.d.ts
  tns-platform-declarations/android-27.d.ts
  tns-platform-declarations/android-28.d.ts
  tns-platform-declarations/android/android-support-17.d.ts
  tns-platform-declarations/android/android-support-23.d.ts
  tns-platform-declarations/android/android-support-26.d.ts
  tns-platform-declarations/android/android-support-28.d.ts
  tns-platform-declarations/android/androidx-17.d.ts
  tns-platform-declarations/android/androidx-23.d.ts
  tns-platform-declarations/android/androidx-26.d.ts
  tns-platform-declarations/android/androidx-28.d.ts
  tns-platform-declarations/android/org.nativescript.widgets.d.ts
  tns-platform-declarations/tsconfig.json
  tsconfig.json
Labels: cla: yes, feature, in progress

#7296 feat: cancel contradictory gesture events
  apps/app/ui-tests-app/events/gestures.ts
  tns-core-modules/ui/gestures/gestures.android.ts
  tns-core-modules/ui/gestures/gestures.ios.ts
Labels: cla: yes, docs needed, e2e test needed

#7352 chore: move typing for material design in tns-platform-declarations
  .travis.yml
  package.json
  tns-core-modules-widgets/.gitignore
  tns-core-modules-widgets/.npmignore
  tns-core-modules-widgets/build.android.sh
  tns-core-modules-widgets/build.ios.sh
  tns-core-modules-widgets/build.sh
  tns-core-modules-widgets/ios/TNSWidgets/Podfile
  tns-core-modules-widgets/ios/TNSWidgets/Podfile.lock
  tns-core-modules-widgets/ios/TNSWidgets/TNSWidgets.xcodeproj/project.pbxproj
  tns-core-modules-widgets/ios/TNSWidgets/TNSWidgets.xcworkspace/contents.xcworkspacedata
  tns-core-modules-widgets/ios/TNSWidgets/TNSWidgets.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  tns-core-modules-widgets/ios/build.sh
  tns-core-modules/package.json
  tns-core-modules/platforms/ios/Podfile
  tns-platform-declarations/ios/ios.d.ts
  tns-platform-declarations/ios/objc-x86_64/objc!MaterialComponents.d.ts
Labels: cla: yes

#7327 fix: clear the `resolvedPage` when entry is being cleared, change the passed `View` to be a weak reference
  tns-core-modules/ui/core/properties/properties.ts
  tns-core-modules/ui/core/view-base/view-base.ts
  tns-core-modules/ui/frame/frame-common.ts
  tns-core-modules/ui/styling/style-properties.ts
  tns-core-modules/ui/styling/style-scope.ts
  tns-core-modules/ui/styling/style/style.d.ts
  tns-core-modules/ui/styling/style/style.ts
Labels: cla: yes

#7384 release: cut the 5.4.3 release
  CHANGELOG.md
  tns-core-modules/package.json
  tns-platform-declarations/package.json
Labels: cla: yes

#7387 tests(ui-tests-app): update examples
  e2e/ui-tests-app/app/css/test-page.css
  e2e/ui-tests-app/app/tab-view/tab-view-more-page.css
  e2e/ui-tests-app/app/tab-view/tab-view-more-page.xml
  e2e/ui-tests-app/app/web-view/query-params-page.ts
  e2e/ui-tests-app/app/web-view/web-view-test-page.xml
  tns-core-modules/image-source/image-source.ios.ts
Labels: cla: yes

#7370 fix(FormattedString) Allow Span descendants in FormattedString
  tns-core-modules/text/formatted-string.ts
Labels: cla: yes

#7397 fix(cuteness): allow cleartext HTTP for API 28
  e2e/cuteness.io/app/App_Resources/Android/src/main/AndroidManifest.xml
  e2e/cuteness.io/package.json
  e2e/cuteness.io/webpack.config.js
Labels: cla: yes

#7399 fix(android): a circular reexports
  tns-core-modules/ui/animation/animation-common.ts
  tns-core-modules/ui/animation/animation.android.ts
  tns-core-modules/ui/animation/animation.ios.ts
Labels: cla: yes

#7385 chore: fix github security alert
  tns-core-modules/js-libs/esprima/package.json
Labels: cla: yes

#7396 feat(EditableTextBase) Add support for :focus pseudo class in TextField/TextView
  tns-core-modules/ui/editable-text-base/editable-text-base-common.ts
Labels: cla: yes, css, feature

#7388 chore: merge release to master
  CHANGELOG.md
  tns-core-modules/ui/core/properties/properties.ts
  tns-core-modules/ui/core/view-base/view-base.ts
  tns-core-modules/ui/frame/frame-common.ts
  tns-core-modules/ui/styling/style-properties.ts
  tns-core-modules/ui/styling/style-scope.ts
  tns-core-modules/ui/styling/style/style.d.ts
  tns-core-modules/ui/styling/style/style.ts
Labels: cla: yes

#7402 fix(android-transition): exit transition not executed after app suspend/resume
  tns-core-modules/ui/frame/fragment.transitions.android.ts
Labels: cla: yes

#7405 fix(css-state): _appliedSelectorsVersion assignment
  tns-core-modules/ui/styling/style-scope.ts
Labels: cla: yes

#7400 fix(ios-actionbar): parent/child gesture recognition
  tns-core-modules/ui/gestures/gestures.ios.ts
Labels: cla: yes

#7407 chore: restore temporarily deprecated apis
  tns-core-modules/ui/core/view-base/view-base.ts
  tns-core-modules/utils/utils.ios.ts
Labels: cla: yes

#7404 refactor(EditableTextBase, Button) rename PseudoClass update handlers to be more specific
  tns-core-modules/ui/button/button.android.ts
  tns-core-modules/ui/button/button.ios.ts
  tns-core-modules/ui/editable-text-base/editable-text-base-common.ts
Labels: bug, cla: yes

#7408 chore: remove nativescript-dev-typescript dependency
  e2e/animation/package.json
  e2e/modal-navigation/package.json
  e2e/nested-frame-navigation/package.json
Labels: cla: yes

#7410 tests: include parse checkout
  e2e/config/mocha.opts
  e2e/ui-tests-app/.gitignore
  e2e/ui-tests-app/.vscode/launch.json
  e2e/ui-tests-app/README.md
  e2e/ui-tests-app/app/tabs/background-color-page.xml
  e2e/ui-tests-app/app/tabs/color-page.xml
  e2e/ui-tests-app/app/tabs/default-page.ts
  e2e/ui-tests-app/app/tabs/default-page.xml
  e2e/ui-tests-app/app/tabs/icon-change-page.ts
  e2e/ui-tests-app/app/tabs/icon-change-page.xml
  e2e/ui-tests-app/app/tabs/icon-title-placement-page.xml
  e2e/ui-tests-app/app/tabs/issue-5470-page.xml
  e2e/ui-tests-app/app/tabs/main-page.ts
  e2e/ui-tests-app/app/tabs/swipe-enabled-page.xml
  e2e/ui-tests-app/app/tabs/tabs-position-page.xml
  e2e/ui-tests-app/e2e/config/appium.capabilities.json
  e2e/ui-tests-app/e2e/config/mocha.opts
  e2e/ui-tests-app/e2e/helpers/image-helper.ts
  e2e/ui-tests-app/e2e/helpers/navigation-helper.ts
  e2e/ui-tests-app/e2e/page-object-base-model.ts
  e2e/ui-tests-app/e2e/resources/images/uitestsapp
  e2e/ui-tests-app/e2e/scripts/sparse-checkout.sh
  e2e/ui-tests-app/e2e/suites/button/background/button-background-page.ts
  e2e/ui-tests-app/e2e/suites/button/background/button-background.e2e-spec.ts
  e2e/ui-tests-app/e2e/suites/tab-navigation/bottom-navigation/bottom-navigation-base-page.ts
  e2e/ui-tests-app/e2e/suites/tab-navigation/bottom-navigation/bottom-navigation.e2e-spec.ts
  e2e/ui-tests-app/e2e/suites/tab-navigation/tab-view/issues-from-git.ts
  e2e/ui-tests-app/e2e/suites/tab-navigation/tab-view/tab-view-base-page.ts
  e2e/ui-tests-app/e2e/suites/tab-navigation/tab-view/tab-view-common-tests.e2e-spec.ts
  e2e/ui-tests-app/e2e/suites/tab-navigation/tab-view/tab-view-css-properties.e2e-spec.ts
  e2e/ui-tests-app/e2e/suites/tab-navigation/tabs/tab-tests.e2e-spec.ts
  e2e/ui-tests-app/e2e/suites/tab-navigation/tabs/tabs-view-base-page.ts
  e2e/ui-tests-app/e2e/suites/tab-view/tab-view-base-page.ts
  e2e/ui-tests-app/package.json
Labels: cla: yes

#7411 tests: update ns-dev-appium
  e2e/ui-tests-app/.vscode/launch.json
  e2e/ui-tests-app/e2e/helpers/image-helper.ts
  e2e/ui-tests-app/e2e/helpers/navigation-helper.ts
  e2e/ui-tests-app/e2e/page-object-base-model.ts
  e2e/ui-tests-app/e2e/suites/button/background/button-background-page.ts
  e2e/ui-tests-app/e2e/suites/button/background/button-background.e2e-spec.ts
  e2e/ui-tests-app/e2e/suites/tab-navigation/bottom-navigation/bottom-navigation.e2e-spec.ts
  e2e/ui-tests-app/e2e/suites/tab-navigation/tab-view/tab-view-common-tests.e2e-spec.ts
  e2e/ui-tests-app/e2e/suites/tab-navigation/tab-view/tab-view-css-properties.e2e-spec.ts
  e2e/ui-tests-app/e2e/suites/tab-navigation/tabs/tab-tests.e2e-spec.ts
  e2e/ui-tests-app/package.json
Labels: cla: yes

#7413 chore: update application private apis
  tns-core-modules/application/application.d.ts
Labels: cla: yes

#7403 fix: restore TextField.textChange and Switch.checkedChange event syntax in xml
  tns-core-modules/ui/editable-text-base/editable-text-base-common.ts
  tns-core-modules/ui/editable-text-base/editable-text-base.d.ts
  tns-core-modules/ui/switch/switch-common.ts
  tns-core-modules/ui/switch/switch.d.ts
Labels: cla: yes

#7415 refactor: livesync tests
  .vscode/launch.json
  tests/app/button-page.xml
  tests/app/livesync/app-new-page.css
  tests/app/livesync/app-new-scss-page.scss
  tests/app/livesync/application-page.css
  tests/app/livesync/button-css-page.css
  tests/app/livesync/button-scss-page.scss
  tests/app/livesync/livesync-button-page.scss
  tests/app/livesync/livesync-tests.ts
  tests/app/test-runner.ts
  tests/package.json
Labels: cla: yes

#7417 fix(android): ignore gzip content-encoding for 204 status code
  tns-core-modules-widgets/android/widgets/src/main/java/org/nativescript/widgets/Async.java
Labels: cla: yes

#7418 refactor(builder): handle modules with "/" or "~/"
  tests/app/ui/builder/builder-tests.ts
  tns-core-modules/ui/builder/builder.ts
Labels: cla: yes

#7421 chore: bump widgets to 6.0.0 in core modules
  tns-core-modules/package.json
Labels: cla: yes

#7367 chore: require relative path within tns-core-modules
  tns-core-modules/application/application-common.ts
  tns-core-modules/bundle-entry-points.ts
  tns-core-modules/file-system/file-system.ts
  tns-core-modules/globals/globals.ts
  tns-core-modules/http/http-request/http-request-common.ts
  tns-core-modules/http/http-request/http-request.android.ts
  tns-core-modules/http/http-request/http-request.ios.ts
  tns-core-modules/ui/builder/component-builder/component-builder.ts
  tns-core-modules/ui/core/view-base/view-base.ts
  tns-core-modules/ui/core/view/view-common.ts
  tns-core-modules/ui/dialogs/dialogs-common.ts
  tns-core-modules/ui/enums/enums.ts
  tns-core-modules/ui/frame/frame.android.ts
  tns-core-modules/ui/frame/frame.d.ts
  tns-core-modules/ui/image-cache/image-cache.ios.ts
  tns-core-modules/ui/styling/style-scope.ts
Labels: cla: yes

#7422 chore: bump to 6.1.0
  tns-core-modules-widgets/package.json
  tns-core-modules/package.json
  tns-platform-declarations/package.json
Labels: cla: yes
