Repository NativeScript/NativeScript, pull requests merged in 2019-03, with the labels that each got.

#6973 release: cut the 5.2.2 release
  CHANGELOG.md
Labels: cla: yes, in progress

#6975 chore: merge release in master
  CHANGELOG.md
Labels: cla: yes, in progress

#6968 fix(ios): disable default tab reselect behavior
  tns-core-modules/ui/tab-view/tab-view.ios.ts
Labels: cla: yes, in progress, patch

#6797 [Do Not Merge] chore(e2e): skip specific test suites with known issues on android / ios
  e2e/nested-frame-navigation/.vscode/launch.json
  e2e/nested-frame-navigation/app/app.android.css
  e2e/nested-frame-navigation/app/app.ios.css
  e2e/nested-frame-navigation/app/frame-root/frame-multi-home-page.xml
  e2e/nested-frame-navigation/app/layout-root/layout-home-page.xml
  e2e/nested-frame-navigation/app/layout-root/layout-home-secondary-page.xml
  e2e/nested-frame-navigation/app/players/player-item-detail/player-item-detail-page.xml
  e2e/nested-frame-navigation/app/players/players-items-page.xml
  e2e/nested-frame-navigation/e2e/config.ts
  e2e/nested-frame-navigation/e2e/frame-root.e2e-spec.ts
  e2e/nested-frame-navigation/e2e/frame-tab-root.e2e-spec.ts
  e2e/nested-frame-navigation/e2e/layout-root.e2e-spec.ts
  e2e/nested-frame-navigation/e2e/screen.ts
  e2e/nested-frame-navigation/e2e/tab-root.e2e-spec.ts
Labels: cla: yes, in progress

#6976 fix(ios): disable default tab reselect behavior (#6968)
  tns-core-modules/ui/tab-view/tab-view.ios.ts
Labels: cla: yes, in progress

#6895 feat(android): add openFile to utils
  apps/app/App_Resources/Android/AndroidManifest.xml
  apps/app/App_Resources/Android/xml/provider_paths.xml
  apps/app/ui-tests-app/intent/main-page.ts
  apps/app/ui-tests-app/intent/main-page.xml
  apps/app/ui-tests-app/intent/open-file.ts
  apps/app/ui-tests-app/intent/open-file.xml
  apps/app/ui-tests-app/main-page.ts
  tests/app/App_Resources/Android/AndroidManifest.xml
  tests/app/app/mainPage.ts
  tests/app/testRunner.ts
  tests/package.json
  tns-core-modules/utils/utils.android.ts
  tns-core-modules/utils/utils.d.ts
Labels: cla: yes, e2e test needed, in progress

#6996 ci: uncomment tests
  tests/app/app/mainPage.ts
  tests/app/testRunner.ts
Labels: cla: yes, in progress

#7017 test: separate suites to optimize execute time on CI
  e2e/nested-frame-navigation/e2e/frame-root.e2e-spec.ts
  e2e/nested-frame-navigation/e2e/frame-tab-root.e2e-spec.ts
  e2e/nested-frame-navigation/e2e/layout-root.e2e-spec.ts
  e2e/nested-frame-navigation/e2e/tab-root.e2e-spec.ts
Labels: cla: yes, in progress

#7009 feat(): local icon handling in actionbar and tabview
  apps/app/ui-tests-app/action-bar/icons.ts
  apps/app/ui-tests-app/action-bar/icons.xml
  apps/app/ui-tests-app/action-bar/local-icons.ts
  apps/app/ui-tests-app/action-bar/local-icons.xml
  apps/app/ui-tests-app/action-bar/main-page.ts
  apps/app/ui-tests-app/tab-view/main-page.ts
  apps/app/ui-tests-app/tab-view/tab-view-icon-local.ts
  apps/app/ui-tests-app/tab-view/tab-view-icon-local.xml
  tns-core-modules/ui/action-bar/action-bar-common.ts
  tns-core-modules/ui/action-bar/action-bar.android.ts
  tns-core-modules/ui/action-bar/action-bar.d.ts
  tns-core-modules/ui/action-bar/action-bar.ios.ts
  tns-core-modules/ui/tab-view/tab-view.android.ts
  tns-core-modules/ui/tab-view/tab-view.d.ts
Labels: cla: yes, docs needed, e2e test needed, in progress

#7004 docs: update changelog
  CONTRIBUTING.md
  build/create-release-changelog-pr.js
  build/merge-release-in-master-pr.js
  build/pr-helper.js
  merge-guidance-schema.png
  release-contribution-guide-schema.png
Labels: cla: yes, in progress

#7012 feat(HMR): style views at runtime
  tests/app/app/main-page.css
  tests/app/livesync/livesync-tests.ts
  tests/app/testRunner.ts
  tests/app/ui/builder/builder-tests.ts
  tests/app/ui/builder/component-module.xml
  tns-core-modules/ui/builder/builder.ts
  tns-core-modules/ui/core/view-base/view-base.d.ts
  tns-core-modules/ui/core/view-base/view-base.ts
  tns-core-modules/ui/core/view/view-common.ts
  tns-core-modules/ui/frame/frame-common.ts
Labels: cla: yes, in progress

#6900 fix: WrappedValue.unwrap empty string behavior
  tests/app/data/observable-tests.ts
  tns-core-modules/data/observable/observable.ts
Labels: cla: yes, in progress, ♥ community PR

#7031 test: separate suites to optimize execute time on CI (#7017)
  e2e/nested-frame-navigation/.vscode/launch.json
  e2e/nested-frame-navigation/app/app.android.css
  e2e/nested-frame-navigation/app/app.ios.css
  e2e/nested-frame-navigation/app/frame-root/frame-multi-home-page.xml
  e2e/nested-frame-navigation/app/layout-root/layout-home-page.xml
  e2e/nested-frame-navigation/app/layout-root/layout-home-secondary-page.xml
  e2e/nested-frame-navigation/app/players/player-item-detail/player-item-detail-page.xml
  e2e/nested-frame-navigation/app/players/players-items-page.xml
  e2e/nested-frame-navigation/e2e/config.ts
  e2e/nested-frame-navigation/e2e/frame-root.e2e-spec.ts
  e2e/nested-frame-navigation/e2e/frame-tab-root.e2e-spec.ts
  e2e/nested-frame-navigation/e2e/layout-root.e2e-spec.ts
  e2e/nested-frame-navigation/e2e/screen.ts
  e2e/nested-frame-navigation/e2e/tab-root.e2e-spec.ts
Labels: cla: yes, in progress

#6922 fix(6913): set/unset touchListener.owner onLoaded/onUnloaded
  tns-core-modules/ui/core/view/view.android.ts
Labels: cla: yes, in progress

#7011 fix: navigation b/n single and nested frame pages
  e2e/nested-frame-navigation/app/home/home-page.ts
  e2e/nested-frame-navigation/app/home/home-page.xml
  e2e/nested-frame-navigation/app/some-page/some-page.ts
  e2e/nested-frame-navigation/app/some-page/some-page.xml
  e2e/nested-frame-navigation/app/still-other-page/still-other-page.ts
  e2e/nested-frame-navigation/app/still-other-page/still-other-page.xml
  e2e/nested-frame-navigation/e2e/frame-root.e2e-spec.ts
  e2e/nested-frame-navigation/e2e/screen.ts
  e2e/nested-frame-navigation/e2e/shared.e2e-spec.ts
  tns-core-modules/ui/frame/fragment.transitions.android.ts
Labels: cla: yes, in progress

#7032 fix: expose missing css background* properties on View
  apps/app/ui-tests-app/css/background-image.css
  apps/app/ui-tests-app/css/background-image.xml
  apps/app/ui-tests-app/css/main-page.ts
  tns-core-modules/ui/core/view/view-common.ts
Labels: cla: yes, e2e test needed, in progress

#7038 chore: merge release to master
  apps/app/ui-tests-app/css/background-image.css
  apps/app/ui-tests-app/css/background-image.xml
  apps/app/ui-tests-app/css/main-page.ts
  e2e/nested-frame-navigation/app/home/home-page.ts
  e2e/nested-frame-navigation/app/home/home-page.xml
  e2e/nested-frame-navigation/app/some-page/some-page.ts
  e2e/nested-frame-navigation/app/some-page/some-page.xml
  e2e/nested-frame-navigation/app/still-other-page/still-other-page.ts
  e2e/nested-frame-navigation/app/still-other-page/still-other-page.xml
  e2e/nested-frame-navigation/e2e/frame-root.e2e-spec.ts
  e2e/nested-frame-navigation/e2e/screen.ts
  e2e/nested-frame-navigation/e2e/shared.e2e-spec.ts
  tns-core-modules/ui/core/view/view-common.ts
  tns-core-modules/ui/frame/fragment.transitions.android.ts
Labels: cla: yes, in progress

#6988 fix(ios-webview): report hostname lookup errors in loadFinished event
  tns-core-modules/ui/web-view/web-view.ios.ts
Labels: cla: yes, in progress, ♥ community PR

#6451 fix(http): ensure httpcontent.toFile() creates intermediate directories
  tests/app/http/http-tests.ts
  tests/package.json
  tns-core-modules/http/http-request/http-request.android.ts
  tns-core-modules/http/http-request/http-request.ios.ts
Labels: cla: yes, in progress

#7044 fix(Android): throw new Error if no activity callbacks
  tns-core-modules/application/application.android.ts
Labels: cla: yes, in progress

#7016 test: update test samples
  apps/app/ui-tests-app/action-bar/icons.xml
  apps/app/ui-tests-app/action-bar/local-icons.xml
  apps/app/ui-tests-app/intent/main-page.ts
  apps/app/ui-tests-app/intent/main-page.xml
  apps/app/ui-tests-app/intent/open-file.xml
  apps/app/ui-tests-app/issues/main-page.ts
  apps/app/ui-tests-app/issues/open-file-6895.ts
  apps/app/ui-tests-app/issues/open-file-6895.xml
  apps/app/ui-tests-app/layouts/passThroughParent.ts
  apps/app/ui-tests-app/layouts/passThroughParent.xml
  apps/app/ui-tests-app/main-page.ts
  apps/app/ui-tests-app/scroll-view/layout-outside-scroll.xml
  apps/app/ui-tests-app/tab-view/icon-title-placement.xml
  apps/app/ui-tests-app/tab-view/issue-5470.xml
  e2e/nested-frame-navigation/app/home/home-page.ts
  e2e/nested-frame-navigation/app/home/home-page.xml
  e2e/nested-frame-navigation/e2e/issues.e2e.spec.ts
  e2e/nested-frame-navigation/e2e/screen.ts
Labels: cla: yes, in progress

#7045 chore: update tests app short imports
  tests/app/application-settings/application-settings-tests.ts
  tests/app/data/virtual-array-tests.ts
  tests/app/http/http-string-worker.ts
  tests/app/http/http-tests.ts
  tests/app/pages/page10.ts
  tests/app/pages/tab-view.ts
Labels: cla: yes, in progress

#7046 chore: update deprecations
  tns-core-modules/application/application.android.ts
  tns-core-modules/application/application.d.ts
  tns-core-modules/application/application.ios.ts
  tns-core-modules/image-source/image-source.android.ts
  tns-core-modules/image-source/image-source.d.ts
  tns-core-modules/image-source/image-source.ios.ts
  tns-core-modules/ui/builder/builder.d.ts
  tns-core-modules/ui/core/view-base/view-base.d.ts
  tns-core-modules/ui/core/view-base/view-base.ts
  tns-core-modules/ui/core/view/view.d.ts
  tns-core-modules/ui/frame/frame.d.ts
  tns-core-modules/ui/utils.d.ts
Labels: cla: yes, in progress

#7053 chore: bump versions to 5.4.0
  tns-core-modules-widgets/package.json
  tns-core-modules/package.json
  tns-platform-declarations/package.json
Labels: in progress

#7051 broken links fix
  README.md
Labels: cla: yes, in progress

#7049 release: cut the 5.3.0 release
  CHANGELOG.md
  tns-core-modules/package.json
Labels: cla: yes, in progress

#7052 refactor: restore lazy load requires in http module
  tns-core-modules/http/http-request/http-request.android.ts
  tns-core-modules/http/http-request/http-request.ios.ts
Labels: in progress

#7060 removing `http-post-json`
  tests/app/http/http-tests.ts
Labels: cla: yes, in progress

#7061 chore: merge release to master
  CHANGELOG.md
  tns-core-modules/http/http-request/http-request.android.ts
  tns-core-modules/http/http-request/http-request.ios.ts
Labels: cla: yes, in progress

#7054 refactor(ios): deprecate utils.ios.getter
  apps/app/ui-tests-app/font/all-fonts.ts
  tests/app/TKUnit.ts
  tests/app/application/application-tests.ios.ts
  tests/app/pages/page5.ts
  tests/app/ui/date-picker/date-picker-tests-native.ios.ts
  tests/app/ui/helper.ts
  tests/app/ui/layouts/safe-area-tests.ts
  tests/app/ui/time-picker/time-picker-tests-native.ios.ts
  tns-core-modules/application-settings/application-settings.ios.ts
  tns-core-modules/application/application.ios.ts
  tns-core-modules/debugger/webinspector-network.ios.ts
  tns-core-modules/file-system/file-system-access.ios.ts
  tns-core-modules/fps-meter/fps-native.ios.ts
  tns-core-modules/http/http-request/http-request.ios.ts
  tns-core-modules/platform/platform.ios.ts
  tns-core-modules/timer/timer.ios.ts
  tns-core-modules/ui/animation/animation.ios.ts
  tns-core-modules/ui/core/view/view.ios.ts
  tns-core-modules/ui/date-picker/date-picker.ios.ts
  tns-core-modules/ui/gestures/gestures.ios.ts
  tns-core-modules/ui/image-cache/image-cache.ios.ts
  tns-core-modules/ui/segmented-bar/segmented-bar.ios.ts
  tns-core-modules/ui/styling/background.ios.ts
  tns-core-modules/ui/styling/font.ios.ts
  tns-core-modules/ui/time-picker/time-picker.ios.ts
  tns-core-modules/ui/utils.ios.ts
  tns-core-modules/utils/utils.d.ts
  tns-core-modules/utils/utils.ios.ts
Labels: cla: yes, in progress

#7063 refactor: add better err msg for missing main entry
  tns-core-modules/application/application.ios.ts
  tns-core-modules/ui/frame/frame.android.ts
Labels: cla: yes, in progress

#7067 chore: fix app.start deprecation
  tns-core-modules/application/application.android.ts
  tns-core-modules/application/application.ios.ts
Labels: in progress

#7071 refactor: guard ng and vue entry points
  tns-core-modules/ui/frame/frame.android.ts
Labels: in progress

#7075 chore: merge release to master
  tns-core-modules/application/application.android.ts
  tns-core-modules/application/application.ios.ts
  tns-core-modules/ui/frame/frame.android.ts
Labels: cla: yes, in progress

#7082 fix: revert fromUrl deprecate warning
  tns-core-modules/image-source/image-source.android.ts
  tns-core-modules/image-source/image-source.ios.ts
Labels: cla: yes, in progress, patch

#7084 release: cut the 5.3.1 release
  CHANGELOG.md
  tns-core-modules/package.json
  tns-platform-declarations/package.json
Labels: cla: yes, in progress

#7083 chore: merge release to master
  tns-core-modules/image-source/image-source.android.ts
  tns-core-modules/image-source/image-source.ios.ts
Labels: cla: yes, in progress

#7077 fix(ios): flat action bar incorrect layout after navigation
  tns-core-modules/ui/core/view/view.ios.ts
  tns-core-modules/ui/page/page.ios.ts
  tns-core-modules/ui/tab-view/tab-view.ios.ts
Labels: cla: yes, in progress, patch

#7087 chore: merge release to master
  CHANGELOG.md
  tns-core-modules/ui/core/view/view.ios.ts
  tns-core-modules/ui/page/page.ios.ts
  tns-core-modules/ui/tab-view/tab-view.ios.ts
Labels: cla: yes, in progress
