Repository NativeScript/NativeScript, pull requests merged in 2020-01, with the labels that each got.

#8224 feat: add longPress state argument w/ UILongPressGestureRecognizer (iOS)
  nativescript-core/ui/gestures/gestures.android.ts
  nativescript-core/ui/gestures/gestures.ios.ts
Labels: cla: yes, feature, in progress, os: ios

#8232 test: make image-cache tests async
  tests/app/ui/image-cache/image-cache-tests.ts
Labels: cla: yes

#8207 feat(html-view): Additional properties for HtmlView component
  api-reports/NativeScript.api.md
  e2e/ui-tests-app/app/css/all-non-uniform-border-page.css
  e2e/ui-tests-app/app/css/all-non-uniform-border-page.xml
  nativescript-core/color/color-common.ts
  nativescript-core/color/color.d.ts
  nativescript-core/color/color.ios.ts
  nativescript-core/ui/html-view/html-view-common.ts
  nativescript-core/ui/html-view/html-view.android.ts
  nativescript-core/ui/html-view/html-view.ios.ts
Labels: cla: yes

#8194 fix(android): Request Timeout #6523
  tns-core-modules-widgets/android/widgets/src/main/java/org/nativescript/widgets/Async.java
Labels: cla: yes

#8160 fix(ios/bottom-navigation): Changing tabs programatically messes up styles
  nativescript-core/ui/bottom-navigation/bottom-navigation.ios.ts
Labels: cla: yes

#8136 feat: Add 3D rotation to view - takeover of PR# 5950
  api-reports/NativeScript.api.md
  e2e/animation/app/3d-rotate/page.ts
  e2e/animation/app/3d-rotate/page.xml
  e2e/animation/app/css-animations/3d-rotate/page.css
  e2e/animation/app/css-animations/3d-rotate/page.ts
  e2e/animation/app/css-animations/3d-rotate/page.xml
  e2e/animation/app/css-animations/page.ts
  e2e/animation/app/css-animations/page.xml
  e2e/animation/app/home/home-page.xml
  nativescript-core/matrix/matrix.ts
  nativescript-core/package.json
  nativescript-core/ui/animation/animation-common.ts
  nativescript-core/ui/animation/animation.android.ts
  nativescript-core/ui/animation/animation.d.ts
  nativescript-core/ui/animation/animation.ios.ts
  nativescript-core/ui/animation/keyframe-animation.ts
  nativescript-core/ui/core/view/view-common.ts
  nativescript-core/ui/core/view/view.android.ts
  nativescript-core/ui/core/view/view.d.ts
  nativescript-core/ui/core/view/view.ios.ts
  nativescript-core/ui/styling/style-properties.ts
  nativescript-core/ui/styling/style-scope.ts
  nativescript-core/ui/styling/style/style.d.ts
  nativescript-core/ui/styling/style/style.ts
  nativescript-core/utils/native-helper.d.ts
  nativescript-core/utils/native-helper.ios.ts
  nativescript-core/utils/utils.d.ts
  nativescript-core/utils/utils.ios.ts
  tests/app/ui/animation/animation-tests.ts
  tests/app/ui/animation/css-animation-tests.ts
  tns-platform-declarations/android/org.nativescript.widgets.d.ts
Labels: cla: yes

#8241 feat(ios): set preferredStatusBarStyle in Page VCs
  nativescript-core/ui/page/page.ios.ts
Labels: cla: yes

#8240 fix: return default tab background color when the background color is not explicitely set through css
  api-reports/NativeScript.api.md
  nativescript-core/ui/bottom-navigation/bottom-navigation.android.ts
  nativescript-core/ui/tab-navigation-base/tab-navigation-base/tab-navigation-base.d.ts
  nativescript-core/ui/tab-navigation-base/tab-navigation-base/tab-navigation-base.ts
  nativescript-core/ui/tabs/tabs.android.ts
Labels: cla: yes

#8250 fix: make integer type visible
  nativescript-core/ui/editable-text-base/editable-text-base.android.ts
Labels: cla: yes

#8252 fix(ios): ActionBar style wrong after cancelled swipe back navigation
  nativescript-core/ui/page/page.ios.ts
Labels: cla: yes, e2e test needed

#7943 feat(textview): added maxLines property
  api-reports/NativeScript.api.md
  nativescript-core/ui/text-view/text-view-common.ts
  nativescript-core/ui/text-view/text-view.android.ts
  nativescript-core/ui/text-view/text-view.d.ts
  nativescript-core/ui/text-view/text-view.ios.ts
  tests/app/ui/text-view/text-view-tests-native.android.ts
  tests/app/ui/text-view/text-view-tests-native.d.ts
  tests/app/ui/text-view/text-view-tests-native.ios.ts
  tests/app/ui/text-view/text-view-tests.ts
Labels: cla: yes, ♥ community PR

#8181 fix(ios-text-base): button textAlignment on IOS (UIButton)
  nativescript-core/ui/text-base/text-base.ios.ts
Labels: cla: yes

#8267 fix: invoke done callback in image cache unit test for API Level < 20
  tests/app/ui/image-cache/image-cache-tests.ts
Labels: cla: yes

#8269 fix(android): crash on setting elevation on API21
  nativescript-core/ui/core/view/view.android.ts
Labels: cla: yes

#8275 chore: merge release in master
  CHANGELOG.md
  build/prepare-compat.sh
  e2e/scoped-packages/package.json
  nativescript-core/platforms/ios/Podfile
  nativescript-core/ui/bottom-navigation/bottom-navigation.android.ts
  nativescript-core/ui/core/view/view.android.ts
  nativescript-core/ui/frame/frame.android.ts
  nativescript-core/utils/utils.ios.ts
Labels: cla: yes

#8263 fix(ios): date picker owner not updating its comps on iOS
  nativescript-core/ui/date-picker/date-picker.ios.ts
Labels: cla: yes

#7707 feat(http): better binary support & XHR support
  api-reports/NativeScript.api.md
  nativescript-core/fetch/LICENSE
  nativescript-core/fetch/fetch.js
  nativescript-core/globals/globals.ts
  nativescript-core/globals/polyfills/text/package.json
  nativescript-core/globals/polyfills/text/text.ts
  nativescript-core/globals/polyfills/xhr/xhr.ts
  nativescript-core/http/http-request/http-request.android.ts
  nativescript-core/http/http-request/http-request.ios.ts
  nativescript-core/http/http.d.ts
  nativescript-core/http/http.ts
  nativescript-core/text/text-common.ts
  nativescript-core/text/text.android.ts
  nativescript-core/text/text.d.ts
  nativescript-core/text/text.ios.ts
  nativescript-core/xhr/xhr.ts
  tests/app/fetch/fetch-tests.ts
  tests/app/http/http-string-worker.ts
  tests/app/http/http-tests.ts
  tests/app/test-runner.ts
  tests/app/xhr/xhr-tests.ts
  tns-core-modules-widgets/android/widgets/src/main/java/org/nativescript/widgets/Async.java
  tns-platform-declarations/android/org.nativescript.widgets.d.ts
Labels: cla: yes, ♥ community PR

#8290 fix: remove the password type for Integer-type keyboard in TextField
  nativescript-core/ui/text-field/text-field.android.ts
Labels: cla: yes

#8286 feat: Add Android APIs usage list
  nativescript-core/platforms/android/native-api-usage.json
  tests/app/App_Resources/Android/native-api-usage.json
Labels: cla: yes

#8291 feat: Add iOS APIs usage list
  nativescript-core/platforms/ios/native-api-usage.json
  tests/app/App_Resources/iOS/native-api-usage.json
Labels: cla: yes
