Repository NativeScript/NativeScript, pull requests merged in 2021-03, with the labels that each got.

#9253 feat(webpack): filter common undesirable warnings by default
  packages/webpack5/package.json
  packages/webpack5/src/configuration/base.ts
Labels: cla: yes, webpack

#9243 fix(bottom-navigation): fragment handling
  nativescript-core/ui/bottom-navigation/bottom-navigation.android.ts
  nativescript-core/ui/tabs/tabs.android.ts
Labels: cla: yes, support: sev2

#9270 fix(bottom-navigation): android light/dark theme change on device crash
  nativescript-core/ui/bottom-navigation/bottom-navigation.android.ts
Labels: cla: yes

#9286 feat: file replacement handling for TS and pure file copy replacements
  packages/webpack5/__tests__/configuration/__fixtures__/workspace-with-platform-replacements.json
  packages/webpack5/__tests__/configuration/__fixtures__/workspace-without-replacements.json
  packages/webpack5/__tests__/configuration/__fixtures__/workspace.json
  packages/webpack5/__tests__/configuration/angular.spec.ts
  packages/webpack5/__tests__/configuration/base.spec.ts
  packages/webpack5/__tests__/helpers/fileReplacements.spec.ts
  packages/webpack5/src/configuration/angular.ts
  packages/webpack5/src/configuration/base.ts
  packages/webpack5/src/helpers/fileReplacements.ts
  packages/webpack5/src/helpers/index.ts
  packages/webpack5/src/index.ts
Labels: cla: yes

#9277 fix(ios): incorrect declaration of 'jsArrayToNSArray' and 'nsArrayToJSArray'
  packages/core/utils/native-helper.d.ts
  packages/core/utils/native-helper.ios.ts
Labels: cla: yes

#9290 fix: read __CSS_PARSER__ from config
  packages/webpack5/src/configuration/base.ts
Labels: cla: yes
