Repository NativeScript/NativeScript, pull requests merged in 2021-01, with the labels that each got.

#9136 fix(core): const initializer in an ambient context
  packages/core/platform/index.d.ts
Labels: cla: yes

#9148 fix(android): BottomNavigation fragment child already has a parent
  packages/core/ui/bottom-navigation/index.android.ts
Labels: cla: yes, os: android, severity: high, tabs

#9153 types: missing typings for iosIgnoreSafeArea
  packages/core/ui/core/view/index.d.ts
Labels: cla: yes

#9155 ci: fix npm_install for core on CI (docs)
  CHANGELOG.md
  package.json
  packages/core/index.d.ts
  packages/core/index.ts
  packages/core/package.json
  packages/core/ui/bottom-navigation/index.android.ts
  packages/core/ui/core/view/index.d.ts
  packages/ui-mobile-base/package.json
  packages/webpack/helpers/angular-config-parser.js
  packages/webpack/package.json
  tools/scripts/build-docs.sh
Labels: cla: yes

#9156 ci: fix npm_install for core on CI (docs)
  build-docs.sh
Labels: cla: yes

#9160 fix(android): BottomNavigation fragment child already has a parent
  nativescript-core/ui/bottom-navigation/bottom-navigation.android.ts
Labels: cla: yes

#9172 Fix: Angular no longer has issues with plugins that aren't named "nativescript"
  packages/webpack/host/resolver.ts
Labels: cla: yes

#9177 fix(ios): force release of nsdata after saving image
  packages/core/image-source/index.ios.ts
Labels: cla: yes

#9174 tried improving, I am a first time contributor so happy to start with NativeScript. Thanks.
  .prettierignore
  README.md
Labels: cla: yes

#9178 fix: some eslint fixes
  .eslintrc.json
  .prettierignore
  package.json
Labels: cla: yes

#9175 feat: setSelection method for editable text components
  packages/core/ui/editable-text-base/editable-text-base-common.ts
  packages/core/ui/editable-text-base/index.android.ts
  packages/core/ui/editable-text-base/index.d.ts
  packages/core/ui/editable-text-base/index.ios.ts
Labels: cla: yes

#9163 feat: reusable views
  apps/ui/src/issues/issue-7469-page.css
  apps/ui/src/issues/issue-7469-page.ts
  apps/ui/src/issues/issue-7469-page.xml
  apps/ui/src/issues/main-page.ts
  packages/core/ui/core/view-base/index.d.ts
  packages/core/ui/core/view-base/index.ts
Labels: cla: yes

#9161 feat(core): box-shadow support
  apps/toolbox/src/app.css
  apps/toolbox/src/main-page.xml
  apps/toolbox/src/main-view-model.ts
  packages/core/platforms/android/widgets-release.aar
  packages/core/ui/core/view/index.d.ts
  packages/core/ui/core/view/view-common.ts
  packages/core/ui/layouts/layout-base.ios.ts
  packages/core/ui/styling/background.android.ts
  packages/core/ui/styling/background.d.ts
  packages/core/ui/styling/background.ios.ts
  packages/core/ui/styling/box-shadow.ts
  packages/core/ui/styling/style-properties.ts
  packages/core/ui/styling/style/index.ts
  packages/types-android/src/lib/android/org.nativescript.widgets.d.ts
  packages/ui-mobile-base/android/widgets/src/main/java/org/nativescript/widgets/Utils.java
Labels: cla: yes

#9066 feat(core): convenient color utility methods to avoid additional external libs
  packages/core/color/color-common.ts
  packages/core/color/index.d.ts
Labels: cla: yes

#8980 feat(core): RootLayout option with api to fluidly handle dynamic layers
  apps/toolbox/src/main-page.xml
  apps/toolbox/src/main-view-model.ts
  packages/core/global-types.d.ts
  packages/core/ui/layouts/index.d.ts
  packages/core/ui/layouts/index.ts
  packages/core/ui/layouts/root-layout/index.android.ts
  packages/core/ui/layouts/root-layout/index.d.ts
  packages/core/ui/layouts/root-layout/index.ios.ts
  packages/core/ui/layouts/root-layout/root-layout-common.ts
  packages/webpack/templates/webpack.react.js
  workspace.json
Labels: cla: yes, ready for test

#8909 feat(core): a11y support
  packages/core/accessibility/accessibility-common.ts
  packages/core/accessibility/accessibility-css-helper.ts
  packages/core/accessibility/accessibility-properties.ts
  packages/core/accessibility/accessibility-service-common.ts
  packages/core/accessibility/accessibility-service.android.ts
  packages/core/accessibility/accessibility-service.d.ts
  packages/core/accessibility/accessibility-service.ios.ts
  packages/core/accessibility/accessibility-types.ts
  packages/core/accessibility/font-scale-common.ts
  packages/core/accessibility/font-scale.android.ts
  packages/core/accessibility/font-scale.d.ts
  packages/core/accessibility/font-scale.ios.ts
  packages/core/accessibility/index.android.ts
  packages/core/accessibility/index.d.ts
  packages/core/accessibility/index.ios.ts
  packages/core/application/application-common.ts
  packages/core/application/index.android.ts
  packages/core/application/index.d.ts
  packages/core/application/index.ios.ts
  packages/core/trace/index.ts
  packages/core/ui/action-bar/index.android.ts
  packages/core/ui/action-bar/index.ios.ts
  packages/core/ui/button/button-common.ts
  packages/core/ui/core/view-base/index.d.ts
  packages/core/ui/core/view-base/index.ts
  packages/core/ui/core/view/index.android.ts
  packages/core/ui/core/view/index.d.ts
  packages/core/ui/core/view/index.ios.ts
  packages/core/ui/core/view/view-common.ts
  packages/core/ui/page/index.android.ts
  packages/core/ui/page/index.d.ts
  packages/core/ui/page/index.ios.ts
  packages/core/ui/page/page-common.ts
  packages/core/ui/slider/index.d.ts
  packages/core/ui/slider/index.ios.ts
  packages/core/ui/slider/slider-common.ts
  packages/core/ui/styling/font-common.ts
  packages/core/ui/styling/font.android.ts
  packages/core/ui/styling/font.d.ts
  packages/core/ui/styling/font.ios.ts
  packages/core/ui/styling/style-properties.ts
  packages/core/ui/styling/style/index.ts
  tools/assets/App_Resources/Android/src/main/res/values/ids.xml
Labels: cla: yes

#9165 fix: --env.uglify broken
  .prettierignore
  packages/webpack/package.json
  packages/webpack/templates/webpack.angular.js
  packages/webpack/templates/webpack.javascript.js
  packages/webpack/templates/webpack.react.js
  packages/webpack/templates/webpack.svelte.js
  packages/webpack/templates/webpack.typescript.js
  packages/webpack/templates/webpack.vue.js
Labels: cla: yes

#9154 Ios modal status bar
  packages/core/ui/page/index.ios.ts
Labels: cla: yes

#9132 fix(ios) Navigation via swipe leads to crash
  packages/core/ui/frame/index.ios.ts
Labels: cla: yes

#9121 fix: no need for batchUdated if no selector
  packages/core/ui/styling/style-scope.ts
Labels: cla: yes

#9120 Faster background color
  packages/core/ui/styling/background.android.ts
Labels: cla: yes

#9016 added license badge and added some cool emojis in order to make it at…
  README.md
Labels: cla: yes

#8998 Bugfix/issue 5976
  packages/core/ui/gestures/index.ios.ts
Labels: cla: yes, ready for test

#8798 fix(android): FlexboxLayout support for isPassThroughParentEnabled
  .eslintrc.json
  apps/ui/src/flexbox/flexbox-ispassthroughparent-page.ts
  apps/ui/src/flexbox/flexbox-ispassthroughparent-page.xml
  apps/ui/src/flexbox/flexbox-main-page.ts
  migrations.json
  packages/core/color/known-colors.ts
  packages/core/data/observable-array/index.ts
  packages/core/data/observable/index.d.ts
  packages/core/module-name-resolver/non-bundle-workflow-compat.ts
  packages/core/ui/animation/animation-interfaces.ts
  packages/core/ui/animation/index.android.ts
  packages/core/ui/animation/index.ios.ts
  packages/core/ui/core/view-base/index.ts
  packages/core/ui/core/view/index.d.ts
  packages/core/ui/core/view/index.ios.ts
  packages/core/ui/core/view/view-common.ts
  packages/core/ui/core/view/view-helper/index.ios.ts
  packages/core/ui/editable-text-base/index.android.ts
  packages/core/ui/frame/frame-common.ts
  packages/core/ui/frame/index.d.ts
  packages/core/ui/frame/index.ios.ts
  packages/core/ui/gestures/index.android.ts
  packages/core/ui/layouts/flexbox-layout/flexbox-layout-common.ts
  packages/core/ui/layouts/flexbox-layout/index.ios.ts
  packages/core/ui/page/page-common.ts
  packages/core/ui/styling/background.android.ts
  packages/core/ui/styling/style-scope.ts
  packages/core/utils/native-helper.d.ts
  packages/ui-mobile-base/android/widgets/src/main/java/org/nativescript/widgets/FlexboxLayout.java
  packages/ui-mobile-base/android/widgets/src/main/java/org/nativescript/widgets/LayoutBase.java
  workspace.json
Labels: cla: yes, ready for test

#8898 Fix extending android application and activity
  packages/webpack/templates/webpack.angular.js
Labels: cla: yes, ready for test

#9182 feat(core): box shadow (add missing demo)
  apps/toolbox/src/app.css
  apps/toolbox/src/box-shadow.ts
  apps/toolbox/src/box-shadow.xml
  apps/toolbox/src/main-page.xml
  apps/toolbox/src/main-view-model.ts
  apps/toolbox/src/root-layout.ts
  apps/toolbox/src/root-layout.xml
  packages/core/ui/core/view/index.d.ts
  packages/core/ui/core/view/view-common.ts
  packages/core/ui/styling/background.android.ts
  packages/core/ui/styling/background.ios.ts
Labels: cla: yes

#9159 fix: ObservableArray splice with start only
  packages/core/__tests__/observable/observable-array.ts
  packages/core/data/observable-array/index.ts
Labels: cla: yes
