Repository NativeScript/NativeScript, pull requests merged in 2022-02, with the labels that each got.

#9773 fix(ios): force layout of view when changing the safe area insets
  packages/core/ui/core/view/index.ios.ts
Labels: cla: yes

#9776 chore: fix typo in moduleid-compat-loader.js
  packages/webpack/helpers/moduleid-compat-loader.js
Labels: cla: yes

#9777 fix: UIImage leaking after Image is disposed
  packages/core/ui/image/index.ios.ts
Labels: cla: yes

#9761 perf(ios): uifont and formatted string optimizations plus uiimage scaling
  packages/core/image-asset/index.ios.ts
  packages/core/image-source/index.ios.ts
  packages/core/platforms/ios/src/NativeScriptUtils.h
  packages/core/platforms/ios/src/NativeScriptUtils.m
  packages/core/platforms/ios/src/UIView+NativeScript.h
  packages/core/platforms/ios/src/UIView+NativeScript.m
  packages/core/platforms/ios/src/module.modulemap
  packages/core/platforms/ios/typings/objc!NativeScriptUtils.d.ts
  packages/core/references.d.ts
  packages/core/ui/styling/font-common.ts
  packages/core/ui/styling/font.ios.ts
  packages/core/ui/text-base/index.ios.ts
Labels: cla: yes

#9605 feat: tab view android icon rendering mode
  apps/ui/src/tab-view/tab-view-icon-local-page.ts
  apps/ui/src/tab-view/tab-view-icon-page.ts
  packages/core/ui/tab-view/index.android.ts
  packages/core/ui/tab-view/index.d.ts
  packages/core/ui/tab-view/tab-view-common.ts
  packages/types-android/src/lib/android/org.nativescript.widgets.d.ts
  packages/ui-mobile-base/android/widgets/src/main/java/org/nativescript/widgets/TabIconRenderingMode.java
  packages/ui-mobile-base/android/widgets/src/main/java/org/nativescript/widgets/TabLayout.java
  packages/ui-mobile-base/android/widgets/src/main/java/org/nativescript/widgets/TabStrip.java
Labels: hacktoberfest, hacktoberfest-accepted

#9598 fix(android): `text-transform: capitalize` consistency
  packages/core/ui/text-base/index.android.ts
Labels: cla: yes, hacktoberfest, hacktoberfest-accepted

#9617 fix: handle tabview background color in iOS 15
  packages/core/ui/tab-view/index.ios.ts
Labels: cla: yes, hacktoberfest, hacktoberfest-accepted

#9775 feat(ios): allow dynamic ProMotion frame refresh rate changes
  packages/core/application/index.android.ts
  packages/core/application/index.d.ts
  packages/core/application/index.ios.ts
  packages/core/index.d.ts
  packages/core/index.ts
Labels: cla: yes

#9763 Background/foreground events
  packages/core/application/application-common.ts
  packages/core/application/index.android.ts
  packages/core/application/index.d.ts
  packages/core/application/index.ios.ts
Labels: cla: yes

#9769 feat(webpack): read nativescript.config.ts main if set before package.json
  packages/core/config/config.interface.ts
  packages/webpack5/__tests__/helpers/platform.spec.ts
  packages/webpack5/scripts/jest.setup.ts
  packages/webpack5/src/helpers/config.ts
  packages/webpack5/src/helpers/platform.ts
Labels: cla: yes

#9747 feat(webpack): support importing .mjs files
  packages/webpack5/__tests__/configuration/__snapshots__/angular.spec.ts.snap
  packages/webpack5/__tests__/configuration/__snapshots__/base.spec.ts.snap
  packages/webpack5/__tests__/configuration/__snapshots__/javascript.spec.ts.snap
  packages/webpack5/__tests__/configuration/__snapshots__/react.spec.ts.snap
  packages/webpack5/__tests__/configuration/__snapshots__/svelte.spec.ts.snap
  packages/webpack5/__tests__/configuration/__snapshots__/typescript.spec.ts.snap
  packages/webpack5/__tests__/configuration/__snapshots__/vue.spec.ts.snap
  packages/webpack5/src/configuration/base.ts
Labels: cla: yes

#9792 fix(android): api17 crash on a11y service
  packages/core/accessibility/accessibility-service.android.ts
Labels: cla: yes

#9791 feat: Binding expression parser additions and improvements
  packages/core/ui/core/bindable/bindable-expressions.ts
  packages/core/ui/core/bindable/index.ts
Labels: cla: yes

#9790 feat(switch): :checked pseudo and color fixes
  apps/toolbox/src/app.css
  apps/toolbox/src/main-page.xml
  apps/toolbox/src/pages/switch.ts
  apps/toolbox/src/pages/switch.xml
  packages/core/ui/switch/index.android.ts
  packages/core/ui/switch/index.ios.ts
  packages/core/ui/switch/switch-common.ts
Labels: cla: yes

#9779 chore: cleanup automated app tests
  apps/automated/project.json
  apps/automated/src/http/http-string-worker.ts
  apps/automated/src/test-runner.ts
  apps/automated/src/ui/animation/animation-tests.ts
  apps/automated/src/ui/button/button-tests.ts
  apps/automated/src/ui/layouts/flexbox-layout-tests.ts
  apps/automated/src/ui/styling/style-properties-tests.ts
  apps/automated/src/ui/styling/style-tests.ts
Labels: cla: yes

#9778 [WIP] chore: update ui-mobile-base to gradle7
  packages/ui-mobile-base/android/build.gradle
  packages/ui-mobile-base/android/gradle.properties
  packages/ui-mobile-base/android/gradle/wrapper/gradle-wrapper.jar
  packages/ui-mobile-base/android/gradle/wrapper/gradle-wrapper.properties
  packages/ui-mobile-base/android/widgets/build.gradle
  packages/ui-mobile-base/android/widgets/gradle/wrapper/gradle-wrapper.jar
  packages/ui-mobile-base/android/widgets/gradle/wrapper/gradle-wrapper.properties
  packages/ui-mobile-base/android/widgets/gradlew
  packages/ui-mobile-base/android/widgets/gradlew.bat
  packages/ui-mobile-base/android/widgets/src/main/java/org/nativescript/widgets/AbsoluteLayout.java
  packages/ui-mobile-base/android/widgets/src/main/java/org/nativescript/widgets/AnimatorHelper.java
  packages/ui-mobile-base/android/widgets/src/main/java/org/nativescript/widgets/Async.java
  packages/ui-mobile-base/android/widgets/src/main/java/org/nativescript/widgets/BorderDrawable.java
  packages/ui-mobile-base/android/widgets/src/main/java/org/nativescript/widgets/BottomNavigationBar.java
  packages/ui-mobile-base/android/widgets/src/main/java/org/nativescript/widgets/BoxShadowDrawable.java
  packages/ui-mobile-base/android/widgets/src/main/java/org/nativescript/widgets/CSSValue.java
  packages/ui-mobile-base/android/widgets/src/main/java/org/nativescript/widgets/CommonLayoutParams.java
  packages/ui-mobile-base/android/widgets/src/main/java/org/nativescript/widgets/ContentLayout.java
  packages/ui-mobile-base/android/widgets/src/main/java/org/nativescript/widgets/CustomTransition.java
  packages/ui-mobile-base/android/widgets/src/main/java/org/nativescript/widgets/CustomTypefaceSpan.java
  packages/ui-mobile-base/android/widgets/src/main/java/org/nativescript/widgets/Dock.java
  packages/ui-mobile-base/android/widgets/src/main/java/org/nativescript/widgets/DockLayout.java
  packages/ui-mobile-base/android/widgets/src/main/java/org/nativescript/widgets/FlexLine.java
  packages/ui-mobile-base/android/widgets/src/main/java/org/nativescript/widgets/FlexboxLayout.java
  packages/ui-mobile-base/android/widgets/src/main/java/org/nativescript/widgets/FragmentBase.java
  packages/ui-mobile-base/android/widgets/src/main/java/org/nativescript/widgets/GridLayout.java
  packages/ui-mobile-base/android/widgets/src/main/java/org/nativescript/widgets/GridUnitType.java
  packages/ui-mobile-base/android/widgets/src/main/java/org/nativescript/widgets/HorizontalScrollView.java
  packages/ui-mobile-base/android/widgets/src/main/java/org/nativescript/widgets/ImageView.java
  packages/ui-mobile-base/android/widgets/src/main/java/org/nativescript/widgets/ItemSpec.java
  packages/ui-mobile-base/android/widgets/src/main/java/org/nativescript/widgets/LayoutBase.java
  packages/ui-mobile-base/android/widgets/src/main/java/org/nativescript/widgets/LinearGradientDefinition.java
  packages/ui-mobile-base/android/widgets/src/main/java/org/nativescript/widgets/Orientation.java
  packages/ui-mobile-base/android/widgets/src/main/java/org/nativescript/widgets/OriginPoint.java
  packages/ui-mobile-base/android/widgets/src/main/java/org/nativescript/widgets/SegmentedBarColorDrawable.java
  packages/ui-mobile-base/android/widgets/src/main/java/org/nativescript/widgets/StackLayout.java
  packages/ui-mobile-base/android/widgets/src/main/java/org/nativescript/widgets/TabIconRenderingMode.java
  packages/ui-mobile-base/android/widgets/src/main/java/org/nativescript/widgets/TabItemSpec.java
  packages/ui-mobile-base/android/widgets/src/main/java/org/nativescript/widgets/TabLayout.java
  packages/ui-mobile-base/android/widgets/src/main/java/org/nativescript/widgets/TabStrip.java
  packages/ui-mobile-base/android/widgets/src/main/java/org/nativescript/widgets/TabViewPager.java
  packages/ui-mobile-base/android/widgets/src/main/java/org/nativescript/widgets/TabsBar.java
  packages/ui-mobile-base/android/widgets/src/main/java/org/nativescript/widgets/Utils.java
  packages/ui-mobile-base/android/widgets/src/main/java/org/nativescript/widgets/VerticalScrollView.java
  packages/ui-mobile-base/android/widgets/src/main/java/org/nativescript/widgets/ViewHelper.java
  packages/ui-mobile-base/android/widgets/src/main/java/org/nativescript/widgets/WrapLayout.java
  packages/ui-mobile-base/android/widgets/src/main/java/org/nativescript/widgets/image/AsyncTask.java
  packages/ui-mobile-base/android/widgets/src/main/java/org/nativescript/widgets/image/BitmapOwner.java
  packages/ui-mobile-base/android/widgets/src/main/java/org/nativescript/widgets/image/Cache.java
  packages/ui-mobile-base/android/widgets/src/main/java/org/nativescript/widgets/image/DiskLruCache.java
  packages/ui-mobile-base/android/widgets/src/main/java/org/nativescript/widgets/image/Fetcher.java
  packages/ui-mobile-base/android/widgets/src/main/java/org/nativescript/widgets/image/Utils.java
  packages/ui-mobile-base/android/widgets/src/main/java/org/nativescript/widgets/image/Worker.java
  packages/ui-mobile-base/ios/build.sh
Labels: cla: yes

#9795 fix: android boolean keyboardType should not set inputType
  packages/core/ui/text-field/index.android.ts
Labels: cla: yes
