Repository NativeScript/NativeScript, pull requests merged in 2022-11, with the labels that each got.

#10044 fix(ios): ensure view layout when using large titles
  packages/core/ui/page/index.ios.ts
Labels: cla: yes

#10070 fix(core): CSS style not working properly in Android modal pages
  packages/core/ui/styling/css-selector/index.ts
Labels: cla: yes

#10077 fix(core): android fix for `path.normalize`
  packages/core/file-system/file-system-access.android.ts
Labels: cla: yes

#10076 fix(android): File manipulation threw exception inside worker
  packages/core/platforms/android/core.aar
  packages/core/platforms/android/widgets-release.aar
  packages/ui-mobile-base/android/widgets/src/main/java/org/nativescript/widgets/FileHelper.java
  packages/ui-mobile-base/android/widgets/src/main/java/org/nativescript/widgets/Utils.java
Labels: cla: yes

#10062 fix(android/application): add fallback for `startActivity`
  packages/core/application/index.android.ts
Labels: cla: yes, hacktoberfest, hacktoberfest-accepted

#10060 fix(ios) animation does not play if nativeView.layer is undefined
  packages/core/ui/animation/index.ios.ts
Labels: cla: yes, hacktoberfest, hacktoberfest-accepted

#10055 fix(android): Tappable spans aren't visible on single-line labels
  packages/core/ui/text-base/index.android.ts
Labels: cla: yes, hacktoberfest, hacktoberfest-accepted

#10049 fix(android): Modal status bar props applied to wrong window
  packages/core/ui/page/index.android.ts
Labels: cla: yes

#10072 feat: FontWeight allow passing number
  packages/core/ui/styling/font-common.ts
  packages/core/ui/styling/font-interfaces.ts
  packages/core/ui/styling/font.android.ts
  packages/core/ui/styling/font.d.ts
  packages/core/ui/styling/font.ios.ts
Labels: cla: yes

#10075 fix(core): iOS Tab page display issue if showing message dialog
  packages/core/ui/frame/index.ios.ts
Labels: cla: yes

#10032 fix(ios): Ensure autocorrect not applied silently on IOS16
  packages/core/ui/editable-text-base/index.ios.ts
Labels: cla: yes

#10008 feat(core): support for external XML UI compilers
  packages/core/ui/builder/index.ts
  packages/core/ui/repeater/index.ts
Labels: cla: yes

#10080 fix(webpack): close compiler after run
  packages/webpack5/src/bin/index.ts
Labels: cla: yes

#10081 feat: TypeScript 4.8+ support and NativeClass decorator improvements
  apps/automated/package.json
  apps/automated/project.json
  apps/automated/src/ui/styling/style-properties-tests.ts
  apps/toolbox/package.json
  apps/toolbox/project.json
  apps/ui/package.json
  apps/ui/project.json
  nx.json
  package.json
  packages/core/project.json
  packages/core/ui/styling/font.d.ts
  packages/core/ui/styling/style-properties.ts
  packages/core/ui/styling/style/index.ts
  packages/core/ui/text-base/formatted-string.ts
  packages/core/ui/text-base/span.ts
  packages/types-android/project.json
  packages/types-ios/project.json
  packages/types-minimal/project.json
  packages/types/project.json
  packages/ui-mobile-base/project.json
  packages/webpack5/package.json
  packages/webpack5/project.json
  packages/webpack5/src/transformers/NativeClass/index.ts
  tools/scripts/project.json
Labels: cla: yes

#10078 fix: wrong check on isRunningLayout
  packages/core/ui/page/index.ios.ts
Labels: cla: yes

#10083 fix(core): new normalize method for android is only for API >= 26
  packages/core/file-system/file-system-access.android.ts
Labels: cla: yes

#10084 chore(core): refactor android sdk version use
  packages/core/accessibility/accessibility-service.android.ts
  packages/core/accessibility/index.android.ts
  packages/core/connectivity/index.android.ts
  packages/core/file-system/index.ts
  packages/core/fps-meter/fps-native.android.ts
  packages/core/platform/index.android.ts
  packages/core/ui/action-bar/index.android.ts
  packages/core/ui/animation/index.android.ts
  packages/core/ui/button/index.android.ts
  packages/core/ui/core/view/index.android.ts
  packages/core/ui/editable-text-base/index.android.ts
  packages/core/ui/html-view/index.android.ts
  packages/core/ui/list-picker/index.android.ts
  packages/core/ui/page/index.android.ts
  packages/core/ui/segmented-bar/index.android.ts
  packages/core/ui/styling/font.android.ts
  packages/core/ui/text-base/index.android.ts
  packages/core/ui/time-picker/index.android.ts
  packages/core/utils/index.android.ts
  packages/core/utils/index.d.ts
  packages/core/utils/layout-helper/index.android.ts
  packages/core/utils/utils-common.ts
Labels: cla: yes

#10040 fix(core): Color.isValid returned true for null/undefined
  apps/automated/src/color/color-tests-common.ts
  packages/core/color/color-common.ts
Labels: cla: yes

#10094 fix(android): ApplicationSettings not returning precise stored numbers
  packages/core/application-settings/index.android.ts
Labels: cla: yes

#10090 chore: missing `SDK_VERSION` refactoring after PR merge
  packages/core/file-system/file-system-access.android.ts
Labels: cla: yes

#10089 feat(utils): dismissKeyboard, copyToClipboard, setWindowBackgroundColor, getCurrentActivity and getResource
  apps/toolbox/src/main-page.ts
  apps/toolbox/src/main.ts
  apps/toolbox/src/pages/box-shadow.ts
  apps/toolbox/src/pages/webview.xml
  packages/core/index.d.ts
  packages/core/index.ts
  packages/core/utils/index.android.ts
  packages/core/utils/index.d.ts
  packages/core/utils/index.ios.ts
  packages/core/utils/native-helper.android.ts
  packages/core/utils/native-helper.d.ts
  packages/core/utils/native-helper.ios.ts
Labels: cla: yes

#10097 fix(core): prevent a circular reference because of `SDK_VERSION`
  packages/core/utils/utils-common.ts
  packages/core/utils/utils.android.ts
  packages/core/utils/utils.ios.ts
Labels: cla: yes

#10096 fix(core): frame `navigatingTo` event were not fired on iOS
  packages/core/ui/frame/index.ios.ts
  packages/core/ui/page/index.ios.ts
Labels: cla: yes

#10098 feat(android): Support drawable in ImageSource
  apps/automated/src/image-source/image-source-tests.ts
  packages/core/image-source/index.android.ts
  packages/core/platforms/android/widgets-release.aar
  packages/types-android/src/lib/android/org.nativescript.widgets.d.ts
  packages/ui-mobile-base/android/widgets/src/main/java/org/nativescript/widgets/Utils.java
Labels: cla: yes

#10052 fix(core): android refactor EditableTextBase
  packages/core/ui/editable-text-base/index.android.ts
Labels: cla: yes, hacktoberfest

#9995 feat(core): support font-variation-settings
  apps/toolbox/webpack.config.js
  packages/core/platforms/ios/src/NativeScriptUtils.h
  packages/core/platforms/ios/src/NativeScriptUtils.m
  packages/core/platforms/ios/typings/objc!MaterialComponents.d.ts
  packages/core/platforms/ios/typings/objc!NativeScriptUtils.d.ts
  packages/core/ui/index.ts
  packages/core/ui/styling/font-common.ts
  packages/core/ui/styling/font.android.ts
  packages/core/ui/styling/font.d.ts
  packages/core/ui/styling/font.ios.ts
  packages/core/ui/styling/style-properties.ts
  packages/types-ios/src/lib/ios/objc-x86_64/objc!NativeScriptUtils.d.ts
Labels: cla: yes

#9190 fix(android): prevent “flashing” activity on app start
  packages/core/ui/frame/index.android.ts
Labels: cla: yes

#9199 fix: android use Nestedscrollview for vertical scroll-view
  packages/core/platforms/android/widgets-release.aar
  packages/core/ui/scroll-view/index.android.ts
  packages/types-android/src/lib/android/org.nativescript.widgets.d.ts
  packages/ui-mobile-base/android/widgets/src/main/java/org/nativescript/widgets/VerticalScrollView.java
Labels: cla: yes

#10103 fix(webpack): prevent hmr from patching __onLiveSync multiple times
  packages/webpack5/src/loaders/nativescript-hot-loader/hmr.runtime.ts
Labels: cla: yes

#10110 chore: nx-cloud setup
  .gitignore
  apps/automated/project.json
  apps/toolbox/project.json
  apps/ui/project.json
  nx.json
  package.json
  packages/core/project.json
  tools/scripts/run-automated.js
Labels: cla: yes

#10114 feat(types-ios): 16.1
  packages/types-ios/src/lib/ios/ios.d.ts
  packages/types-ios/src/lib/ios/objc-x86_64/objc!AVFoundation.d.ts
  packages/types-ios/src/lib/ios/objc-x86_64/objc!AVRouting.d.ts
  packages/types-ios/src/lib/ios/objc-x86_64/objc!Accelerate.d.ts
  packages/types-ios/src/lib/ios/objc-x86_64/objc!AudioToolbox.d.ts
  packages/types-ios/src/lib/ios/objc-x86_64/objc!AuthenticationServices.d.ts
  packages/types-ios/src/lib/ios/objc-x86_64/objc!AutomaticAssessmentConfiguration.d.ts
  packages/types-ios/src/lib/ios/objc-x86_64/objc!BackgroundAssets.d.ts
  packages/types-ios/src/lib/ios/objc-x86_64/objc!CloudKit.d.ts
  packages/types-ios/src/lib/ios/objc-x86_64/objc!ColorSync.d.ts
  packages/types-ios/src/lib/ios/objc-x86_64/objc!CoreFoundation.d.ts
  packages/types-ios/src/lib/ios/objc-x86_64/objc!CoreGraphics.d.ts
  packages/types-ios/src/lib/ios/objc-x86_64/objc!CoreLocation.d.ts
  packages/types-ios/src/lib/ios/objc-x86_64/objc!CoreMedia.d.ts
  packages/types-ios/src/lib/ios/objc-x86_64/objc!CoreMotion.d.ts
  packages/types-ios/src/lib/ios/objc-x86_64/objc!CoreSpotlight.d.ts
  packages/types-ios/src/lib/ios/objc-x86_64/objc!CoreText.d.ts
  packages/types-ios/src/lib/ios/objc-x86_64/objc!Darwin.d.ts
  packages/types-ios/src/lib/ios/objc-x86_64/objc!DeviceDiscoveryExtension.d.ts
  packages/types-ios/src/lib/ios/objc-x86_64/objc!FileProvider.d.ts
  packages/types-ios/src/lib/ios/objc-x86_64/objc!Foundation.d.ts
  packages/types-ios/src/lib/ios/objc-x86_64/objc!GameController.d.ts
  packages/types-ios/src/lib/ios/objc-x86_64/objc!GameKit.d.ts
  packages/types-ios/src/lib/ios/objc-x86_64/objc!HealthKit.d.ts
  packages/types-ios/src/lib/ios/objc-x86_64/objc!HomeKit.d.ts
  packages/types-ios/src/lib/ios/objc-x86_64/objc!ImageCaptureCore.d.ts
  packages/types-ios/src/lib/ios/objc-x86_64/objc!MapKit.d.ts
  packages/types-ios/src/lib/ios/objc-x86_64/objc!Matter.d.ts
  packages/types-ios/src/lib/ios/objc-x86_64/objc!MediaPlayer.d.ts
  packages/types-ios/src/lib/ios/objc-x86_64/objc!MetalPerformanceShadersGraph.d.ts
  packages/types-ios/src/lib/ios/objc-x86_64/objc!NativeScriptUtils.d.ts
  packages/types-ios/src/lib/ios/objc-x86_64/objc!PDFKit.d.ts
  packages/types-ios/src/lib/ios/objc-x86_64/objc!PassKit.d.ts
  packages/types-ios/src/lib/ios/objc-x86_64/objc!PencilKit.d.ts
  packages/types-ios/src/lib/ios/objc-x86_64/objc!ProximityReader.d.ts
  packages/types-ios/src/lib/ios/objc-x86_64/objc!PushToTalk.d.ts
  packages/types-ios/src/lib/ios/objc-x86_64/objc!SQLite3.d.ts
  packages/types-ios/src/lib/ios/objc-x86_64/objc!SharedWithYou.d.ts
  packages/types-ios/src/lib/ios/objc-x86_64/objc!SharedWithYouCore.d.ts
  packages/types-ios/src/lib/ios/objc-x86_64/objc!Social.d.ts
  packages/types-ios/src/lib/ios/objc-x86_64/objc!StoreKit.d.ts
  packages/types-ios/src/lib/ios/objc-x86_64/objc!UIKit.d.ts
  packages/types-ios/src/lib/ios/objc-x86_64/objc!VideoSubscriberAccount.d.ts
  packages/types-ios/src/lib/ios/objc-x86_64/objc!WebKit.d.ts
  packages/types-ios/src/lib/ios/objc-x86_64/objc!WidgetKit.d.ts
  packages/types-minimal/src/lib/ios/objc-x86_64/objc!AVFoundation.d.ts
  packages/types-minimal/src/lib/ios/objc-x86_64/objc!AudioToolbox.d.ts
  packages/types-minimal/src/lib/ios/objc-x86_64/objc!CoreGraphics.d.ts
  packages/types-minimal/src/lib/ios/objc-x86_64/objc!CoreMotion.d.ts
  packages/types-minimal/src/lib/ios/objc-x86_64/objc!Foundation.d.ts
  packages/types-minimal/src/lib/ios/objc-x86_64/objc!PDFKit.d.ts
  packages/types-minimal/src/lib/ios/objc-x86_64/objc!UIKit.d.ts
  packages/types-minimal/src/lib/ios/objc-x86_64/objc!WebKit.d.ts
Labels: cla: yes

#10106 fix(webpack): support angular 15.x
  packages/webpack5/__tests__/configuration/__snapshots__/angular.spec.ts.snap
  packages/webpack5/__tests__/configuration/angular.spec.ts
  packages/webpack5/package.json
  packages/webpack5/src/configuration/angular.ts
Labels: cla: yes

#10117 fix(ios/utils): filter out null values from dataSerialize
  packages/core/utils/native-helper.ios.ts
Labels: cla: yes
