Repository NativeScript/NativeScript, pull requests merged in 2023-10, with the labels that each got.

#10396 fix(testing): e2e flag no longer needed, testID is now applicable in dev or prod builds
  packages/core/accessibility/index.android.ts
  packages/core/global-types.d.ts
  packages/core/platforms/android/core.aar
  packages/core/ui/core/view/index.android.ts
  packages/core/ui/core/view/index.ios.ts
  packages/core/ui/core/view/view-common.ts
  packages/core/ui/text-base/index.android.ts
  packages/webpack5/__tests__/configuration/__snapshots__/angular.spec.ts.snap
  packages/webpack5/__tests__/configuration/__snapshots__/base.spec.ts.snap
  packages/webpack5/__tests__/configuration/__snapshots__/javascript.spec.ts.snap
  packages/webpack5/__tests__/configuration/__snapshots__/react.spec.ts.snap
  packages/webpack5/__tests__/configuration/__snapshots__/svelte.spec.ts.snap
  packages/webpack5/__tests__/configuration/__snapshots__/typescript.spec.ts.snap
  packages/webpack5/__tests__/configuration/__snapshots__/vue.spec.ts.snap
  packages/webpack5/src/configuration/base.ts
  packages/webpack5/src/index.ts
Labels: cla: yes, hacktoberfest, hacktoberfest-accepted

#10399 feat(css): text-stroke support
  apps/toolbox/src/pages/labels.ts
  apps/toolbox/src/pages/labels.xml
  packages/core/platforms/android/widgets-release.aar
  packages/core/platforms/ios/src/UIView+NativeScript.h
  packages/core/platforms/ios/src/UIView+NativeScript.m
  packages/core/ui/index.ts
  packages/core/ui/label/index.android.ts
  packages/core/ui/styling/css-shadow.ts
  packages/core/ui/styling/css-stroke.spec.ts
  packages/core/ui/styling/css-stroke.ts
  packages/core/ui/styling/style/index.ts
  packages/core/ui/text-base/index.android.ts
  packages/core/ui/text-base/index.d.ts
  packages/core/ui/text-base/index.ios.ts
  packages/core/ui/text-base/text-base-common.ts
  packages/types-android/src/lib/android/org.nativescript.widgets.d.ts
  packages/types-ios/src/lib/ios/objc-x86_64/objc!UIKit.d.ts
  packages/ui-mobile-base/android/widgets/src/main/java/org/nativescript/widgets/StyleableTextView.java
Labels: cla: yes, hacktoberfest, hacktoberfest-accepted

#10401 fix(webpack): Adjust appComponents Env
  packages/webpack5/src/configuration/base.ts
Labels: cla: yes

#10404 fix(ios): Setting of property mask on 'undefined' during view disposal
  packages/core/ui/core/view/index.ios.ts
Labels: cla: yes

#10405 fix(core): box-shadow 'none' handling
  packages/core/ui/styling/css-shadow.spec.ts
  packages/core/ui/styling/css-shadow.ts
  packages/core/ui/styling/css-stroke.spec.ts
  packages/core/ui/styling/css-stroke.ts
  packages/core/ui/styling/css-utils.ts
  packages/core/utils/index.d.ts
Labels: cla: yes, hacktoberfest

#10409 fix(ios): Add/remove shadow for reusable views
  packages/core/ui/core/view/index.ios.ts
Labels: cla: yes

#10413 fix(ios): Proper shadow position after translate transform
  packages/core/ui/core/view/index.ios.ts
  packages/core/ui/styling/background.ios.ts
Labels: cla: yes

#10417 fix(core): Page frame reference not unset on native view disposal
  packages/core/ui/frame/frame-common.ts
  packages/core/ui/page/index.d.ts
  packages/core/ui/page/index.ios.ts
  packages/core/ui/page/page-common.ts
Labels: cla: yes, hacktoberfest, hacktoberfest-accepted

#10414 fix(android): Do not try to rehydrate destroyed dialogs
  packages/core/ui/core/view/index.android.ts
Labels: cla: yes

#10420 chore: 8.6.1 next
  packages/core/package.json
Labels: cla: yes

#10422 feat(webpack): add USER_PROJECT_PLATFORMS_IOS for embedding options
  packages/webpack5/src/platforms/ios.ts
Labels: cla: yes
